pytorch/rl

test/test_rb.py
test/test_tensordict.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/tensordict/tensordict.py
torchrl/data/tensordict/utils.py

Solves #47 by resetting the `batch_size` of trajectories to a void `torch.Size` object.

Replay buffers storing trajectories

---

README.md

"python setup.py install" actually has installation errors
either "python setup.py develop" or "pip install -e ."

Fix minor typos and installation in README.md

---

torchrl/envs/transforms/transforms.py
torchrl/record/recorder.py
torchrl/trainers/helpers/trainers.py
torchrl/trainers/trainers.py

Adds another recorder to the default trainer that will record explorative rollouts. This can give an empirical idea of what exploration looks like.

Record exploration rollouts

---

torchrl/objectives/costs/ppo.py
torchrl/objectives/costs/reinforce.py
torchrl/objectives/returns/advantages.py
torchrl/objectives/returns/functional.py

Fixes the GAE value loss.
Also renamed the `"value_target"` key to `"value_error"` for more clarity (for both GAE and TD).

Fix GAE error + naming issue

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py
torchrl/trainers/helpers/envs.py

`TransformedEnv` can now be created incrementally by adding transforms one at a time.
This is useful if a transform takes as argument `transform = MyTransform(..., env.observation_spec)` for instance. In that case, incrementing the transforms will ensure that `observation_spec` matches what the transform will see.
Old usage
```python
env = my_env()
transfroms = []
transfroms.append(transform1)
transfroms.append(transform2)
env = TransformedEnv(env, Compose(*transforms))
```
New usage
```python
env = my_env()
env = TransformedEnv(env)
env.append_transform(transform1)
env.append_transform(transform2)
```

Extend transforms in `TransformedEnv` to keep track of specs

---

test/test_env.py
torchrl/data/tensordict/tensordict.py
torchrl/envs/vec_env.py

Fixes bugs in vectorized envs, specifically when the policy returns more keys than expected (e.g. `"hidden"` etc)

Fix bugs in keys retrieval in vectorized envs

---

test/test_tdmodules.py
torchrl/modules/td_module/common.py

Fixes #128 
Add `__getitem__` method to `TDSequence` to make it index-able, equivalent to `torch.nn.Sequential`

Make TDSequence index-able by adding `__getitem__` dunder method.

---

test/test_tensordict.py
torchrl/data/tensordict/tensordict.py

Make `_TensorDict` subclasses accept string as key for `__getitem__`, `__settitem__`, and `__delitem__` methods.
Fixes: #126 #127 
NOTE:
Refactored `test/tensordict.py` file to pytest parametrize the Class directly instead of individual methods.

`tensordict.__setitem__(string)`, `tensordict.__getitem__(string)`, and `tensordict.__delitem__(string)` for subclasses

---

test/test_cost.py
test/test_exploration.py
test/test_helpers.py
test/test_modules.py
test/test_tdmodules.py
torchrl/collectors/collectors.py
torchrl/data/tensor_specs.py
torchrl/data/tensordict/tensordict.py
torchrl/envs/common.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py
torchrl/modules/distributions/continuous.py
torchrl/modules/models/exploration.py
torchrl/modules/td_module/__init__.py
torchrl/modules/td_module/actors.py
torchrl/modules/td_module/common.py
torchrl/modules/td_module/deprec.py
torchrl/modules/td_module/exploration.py
torchrl/modules/td_module/probabilistic.py
torchrl/modules/td_module/sequence.py
torchrl/objectives/costs/impala.py
torchrl/objectives/costs/ppo.py
torchrl/objectives/costs/redq.py
torchrl/objectives/costs/reinforce.py
torchrl/objectives/costs/sac.py
torchrl/trainers/helpers/collectors.py
torchrl/trainers/helpers/envs.py
torchrl/trainers/helpers/models.py

This PR refactors from the ground up the `ProbabilisticTDModule` class, which is at the base of many RL policies.
The former class was messy, with a lot of ad-hoc rules hard to understand even for the eng that coded them (hm!)
In this PR:
- We propose a new `ProbabilisticTensorDictModule` and `ProbabilisticActor` class
- We refactor gSDE to fit the new logic (cleaner now)
- We make the test abide by the new rules
- We solve a bug in the lazy `_CustomOpTensorDict` classes
- `spec` is now completely optional for all `TDModule` classes
- the `safe` flag for TDModules is restricted to the `"action"` key. We can think later on how to make this more general if needed
- casting of the tensordicts from device to device during rollouts in the data collectors are not done inplace anymore, to …

[WIP] Refactor the probabilistic TDModule class

---

torchrl/modules/distributions/continuous.py

`NormalParamWrapper` should leave other input untouched, in case they're needed for some other purpose (e.g. intermediate hidden value used for value computation etc.)

Make `NormalParamWrapper` pass other inputs 

---

examples/ddpg/ddpg.py
examples/dqn/dqn.py
examples/ppo/ppo.py
examples/redq/redq.py
examples/sac/sac.py
test/mocking_classes.py
test/test_collector.py
test/test_env.py
test/test_tdmodules.py
test/test_tensordict.py
torchrl/collectors/collectors.py
torchrl/data/tensor_specs.py
torchrl/data/tensordict/tensordict.py
torchrl/envs/common.py
torchrl/envs/libs/dm_control.py
torchrl/envs/libs/gym.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py
torchrl/envs/vec_env.py
torchrl/modules/distributions/continuous.py
torchrl/modules/td_module/common.py
torchrl/modules/td_module/sequence.py
torchrl/record/recorder.py
torchrl/trainers/helpers/collectors.py
torchrl/trainers/helpers/envs.py

This PR:
- makes sure `env.to(device)` behaves as expected for regular envs, parallel, serial and transformed instances
- makes sure that environment creation on device behaves as expected
- allows tensordicts to be created empty but on device, such that all tensors are then placed on device afterwards

Refactoring environment device setting/casting

---

test/test_tensordict.py
torchrl/data/tensordict/tensordict.py
torchrl/data/tensordict/utils.py

Implemented ellipsis indexing by creating function convert_ellipsis_to_idx to convert ellipsis into slice(None), depending on batch size of TensorDict. 
For example, for td = TensorDict({'a': torch.zeros(3, 4, 5), 'b': torch.ones(3, 4, 5, 6)}, batch_size=[3, 4, 5])
tensordict[..., 0] becomes tensordict[(slice(None), slice(None), 0)]
Added tests for __getitem__ and __setitem__ into tests/test_tensordict.py.

Add ellipsis indexing for TensorDict

---

torchrl/envs/libs/gym.py

Makes seeding robust to new gym API where seeding has to be achieved through `.reset(seed=seed)`, but registered envs may not support that.
What we want to avoid is calling the part under `except` too often, as it has a significant overhead. Hence we use an attribute that tracks if `reset` can be used for seeding or not, and not we always use `seed`.
cc @yidingjiang

Gym seeding logic and robustness

---

torchrl/trainers/helpers/trainers.py

Changing the default schedule to be consistent with regular rainbow dqn.

Change the default trainer scheduler to None

---

build_tools/setup_helpers/extension.py
test/test_tensor_spec.py
torchrl/data/tensor_specs.py

https://github.com/facebookresearch/rl/issues/220

Refactor CompositeSpec tests

---

test/test_memmap.py

- Added a test if the created MemmapTensor is on the same device as the input tensor. 
- Added a test if device is correct when .to(device) is called.
- Added a test if the device arg for MemmapTensor init is respected.
- Added a test if all entries are zeros when MemmapTensor is created with size.
- Added a test if MemmapTensor can be created with a given data type and shape.
This PR closes #221.

Implement unittests for MemmapTensor.

---

torchrl/envs/__init__.py
torchrl/envs/gym_like.py

Proposes a `set_info_dict_reader` method for gym-like environments that'll read the info dictionary and write down the values on a `TensorDict` in a way defined by the user.
This will allow users to use `GymWrapper` and `GymEnv` without effort in cases where the info dictionary is weird and unpredictable.
cc @BoboBananas

[Feature] custom info_dict reader methods

---

test/test_tensordict.py
torchrl/data/tensordict/tensordict.py

Allows for TensorDict creation like this
```python
>>> td = TensorDict({}, batch_size=[100])
>>> 
>>> for i in range(100):
>>>     td[i] = TensorDict({"a": torch.randn(10), "b": torch.zeros(1)}, [])
>>> 
>>> print(td)
TensorDict(
fields={
a: Tensor(torch.Size([100, 10]), dtype=torch.float32),
b: Tensor(torch.Size([100, 1]), dtype=torch.float32)},
batch_size=torch.Size([100]),
device=cpu,
is_shared=False)
```
The tensordict is populated with zero-valued key-value pairs when first initialized, hence creating an empty tensor that is to be populated.
cc @BoboBananas

Empty TensorDict population in loops

---

test/test_tensordict.py
torchrl/data/tensordict/memmap.py
torchrl/data/tensordict/metatensor.py
torchrl/data/tensordict/tensordict.py
torchrl/data/utils.py

```python
from torchrl.data import TensorDict
import torch
td1 = TensorDict({"a": torch.randn(4, 1)}, [4])
td2 = TensorDict({"b": torch.randn(4, 1), "td": td1}, [4])
print(td2)
td1 = TensorDict({"a": torch.randn(4, 1)}, [])
td2 = TensorDict({"b": torch.randn(4, 1), "td": td1}, [4])
print(td2)
td1 = TensorDict({"a": torch.randn(4, 1)}, [])
td2 = TensorDict({"b": torch.randn(4, 1)}, [4])
td2["td"] = td1
print(td2)
td1 = TensorDict({"a": torch.randn(4, 1)}, [])
td2b = TensorDict({"b": torch.randn(4, 1)}, [4])
td2b["td"] = td1
td2b[:] = td2
print(td2)
```

[Feature] Nested tensordicts

---

test/test_tensordict.py
torchrl/data/tensordict/memmap.py
torchrl/data/tensordict/metatensor.py

Implements new tests for tensordict created on device.
We may miss some bugs if we only test TensorDicts on cpu.
We create a new "device" param for tensordicts in `test_tensordict.py::TestTensorDict`

[Test]: TensorDict: test tensordict created on cuda and sub-tensordict indexed along 2nd dimension

---

test/test_tensordict.py
torchrl/__init__.py
torchrl/data/tensordict/memmap.py
torchrl/data/tensordict/metatensor.py
torchrl/data/tensordict/tensordict.py

Refactors the `MetaTensor` instantiation in `TensorDict` to avoid duplicated creations when one `TensorDict` is used to create another one, and to create `MetaTensors` only when they are needed.
This change brings a 30% speedup in the creation of a `TensorDict`.

[Feature]: faster meta-tensor API for TensorDict

---

CONTRIBUTING.md

Moves `pip install` to `python setup.py` in CONTRIBUTING.md

[Doc]: remove pip install from CONTRIBUTING.md

---

CONTRIBUTING.md
README.md
torchrl/data/tensordict/tensordict.py

Updated documentation to troubleshooting in case the generation of the artifact in MacOs M1 machines have incompatibility problems with the architecture because it is being generated for x86_64 architecture instead of arm64 architecture.
After some errors in the execution of the generated artifact, showing an error with this message `(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))`, we realized that we need to define the target architecture before the generation of the artifact in MacOs M1.

[Doc] MacOs M1 troubleshooting

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

Added 2 functions for #281 Feature Request. 
- TransformedEnv::insert_transform
- Compose::insert
it support negative indexes as well. Index must be between [-len(list), len(list)]
+ added test_insert. 
Test plan:
1. insert in empty 
2. insert at front, back, the medial 
3. insert with negative indexes. (2 cases: at the medial, and at front) 
4. checking "empty_cache"
5. checking exceptions for index out of bound (neg , pos) and wrong type of input args.
6. keeping metadata after exceptions 
- [ x] New feature (non-breaking change which adds core functionality)
- [x ] I have read the [CONTRIBUTION](https://github.com/facebookresearch/rl/blob/main/CONTRIBUTING.md) guide (**required**)
- [ x] My change requires a change to the documentation.
- [ x] I have updated the tests accordingly …

[Feature] Transforms: `Compose.insert` and `TransformedEnv.insert_transform`

---

setup.py

when building locally I was getting the below build warning. Changing import order seems to fix it.
```
/Users/bvaughan/anaconda3/lib/python3.7/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
"Distutils was imported before Setuptools. This usage is discouraged "
```

[BugFix] Fix a build warning, setuptools/distutils import order

---

setup.py

previous change breaks pre-commit hook because ufmt sorts imports, reverting.
https://github.com/facebookresearch/rl/pull/307

ufmt issue if imports in order requested by distutils

---

test/test_tensordict.py
torchrl/data/tensordict/tensordict.py

Inverse operations on Tensordicts can return the original data. This is currently not the case for tensordict.permute.
We need to return the original tensordict when calling tensordict.permute(a, b, c) we get an instance of a PermutedTensorDict and if we call again the same method with the same parameters in the resulting PermutedTensorDict 
`assert tensordict.permute(dims_list, dim).permute(dims_list, dim) is tensordict`
`close #278`

[Feature] Truly invertible tensordict permutation of dimensions

---

torchrl/trainers/helpers/envs.py

When the standard deviation of a state value is 0, we used to clamp at 1e-5. If the state variance then becomes non-null, its value will likely explore.
We make sure that this does not happen by setting the loc to 0 and scale to 1.0 whenever the std is 0.

[BugFix]: Safe state normalization when std=0

---

examples/ddpg/ddpg.py
examples/dqn/dqn.py
examples/ppo/ppo.py
examples/redq/redq.py
examples/sac/sac.py

Training examples try to return a `state_dict` of an object that has been stopped. We prevent this to happen by not returning this `state_dict`.

[BugFix]: make training example gracefully exit

---

setup.py

Exclude the tutorials folder from the setup.py installation

[Setup]: Exclude tutorials from wheels

---

torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/tensordict/tensordict.py

Solves an error with the replay buffer when updating the indices of a stored tensordict.

[BugFix]: Tensor map for subtensordict.set_

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

Fixing Compose which ignored child inv_calls
Compose.inv wasnt actually doing anything when called when ignoring child inv_transforms. This PR fix it.

[BugFix] Fixed compose which ignored inv_transforms of child

---

test/smoke_test_deps.py

The `OSError` could be raised randomly depending on the CI testing machine. Causing tests not to pass.
Try again the test in case this exception is raised.

[Test] pass the OS error in case the file isn't closed

---

test/test_tensor_spec.py
torchrl/data/tensor_specs.py
torchrl/version.py

This pull request has the following changes:
* Add tests to cover equality check for all the `TensorSpec` subclasses. Equality function returns True if all the fields are the same and class is the same.
* Since majority of subclasses and their dependencies are marked with `@dataclass` - there was no need to implement `__eq__` in many of them. So this PR only adds `__eq__` implementation to a few exceptions.
* Add `__eq__` to the class `ContinuousBox`. Default `__eq__` implementation doesn't work as expected for multi-dimensional tensor comparison. If you have two tensors with more than 1 value then their equality returns not a boolean, but a tensor of the same dimension, which raises "Truth value is ambiguous" error. This PR uses `torch.equal` method instead
* Add `__eq__` to the class …

[Feature] Implement __eq__ for TensorSpec

---

test/test_collector.py
test/test_transforms.py
torchrl/collectors/collectors.py
torchrl/envs/transforms/transforms.py
torchrl/envs/vec_env.py

Implemented Lock support in VecNorm
The lock parameter is optional, to avoid overhead if no locking is needed, if provided the VecNorm will acquire it to make the updates multiprocessing safe
Updated tests:
test_vecnorm_parallel
test_vecnorm_parallel_auto
test_parallelenv_vecnorm
As lock is stored in extra state, fixed up some locations in code making assumptions of the layout/contents of the state_dicts, this code seemed internal or part of tests so I don't think the change should be breaking in general
close #312

[BugFix] Add lock to vec norm transform

---

torchrl/data/tensordict/tensordict.py

Fix for #367 
This code snippet should display tensors of size [2, 1] and not [150, 2, 1]:
```python
from torchrl.data import TensorDict
import torch
import string
z = TensorDict({str(k): TensorDict({k: torch.arange(300).reshape(150, 2) for k in string.ascii_lowercase}, batch_size=[150, 2]) for k in [0, 1, 2, 3, 4]}, batch_size=[150])
print(z[0])
```
TODO:
cc @ezhang7423

[BugFix] Representation of indexed nested tensordict

---

test/test_tensordictmodules.py
torchrl/modules/tensordict_module/probabilistic.py

Currently TensorDictModule forces you to have the exact same name of TEnsorDict outputs as the name of the dist you want to build. This PR supports remmaping the TEnsorDictModule output to the right dist name.
This change is required since having the constraint on the names limits the use of ProbabilisticTensorDictModule to a single module. If we want to use 2 modules in a TensorDictSequence, we cannot preserve the dist params at the end of the sequence: One will get overwritten by the other module output.

[Feature] Add `ProbabilisticTensorDictModule` dist key mapping support 

---

test/mocking_classes.py
test/test_collector.py
test/test_env.py
test/test_trainer.py
torchrl/collectors/collectors.py
torchrl/envs/common.py
torchrl/envs/transforms/transforms.py
torchrl/envs/vec_env.py
torchrl/trainers/trainers.py

Allows to seed multiple environments with the same seed.
This is interesting in contexts where we need to test multiple strategies across the same init (e.g. meta-RL and MCP planner)
cc @Benjamin-eecs @nicolas-dufour

[Feature] static_seed flag for envs, vectorized envs and collectors

---

.circleci/unittest/linux/scripts/environment.yml
.circleci/unittest/linux_stable/scripts/environment.yml

Our CI is broken because of the recent gym upgrade to 0.26.0.
We temporarily fix the gym version to 0.25.1 until we figure out how to account for BC breaking changes.

[BugFix] Temporarily fix gym to 0.25.1 to fix CI

---

test/test_tensordict.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/tensordict/tensordict.py
torchrl/envs/transforms/transforms.py
torchrl/modules/functional_modules.py

Replaces uses of `recursive` kwargs with `recurse` 
PyTorch uses the kwarg `recurse` as a flag for recursion in operations. This library uses the kwarg `recursive` for the same purpose.
This PR brings rl into alignment with PyTorch.
close #406

[Naming] Recurse kwarg to match pytorch

---

.circleci/unittest/linux/scripts/setup_env.sh
.circleci/unittest/linux_optdeps/scripts/setup_env.sh
.circleci/unittest/linux_stable/scripts/setup_env.sh
test/smoke_test_deps.py
test/test_env.py
test/test_libs.py
torchrl/data/tensor_specs.py
torchrl/envs/common.py
torchrl/envs/gym_like.py
torchrl/envs/libs/gym.py

The return types of gym 0.26 have changed and require an update of our env wrapping.
- We have to convert lists of size 1 in arrays otherwise some pixels end up with shape [1, H, W, 3] when the spec indicates they should be [H, W, 3], see [here](https://github.com/facebookresearch/rl/blob/d8742dfcd894f241bcf912b65f06d3c458cf6cd6/torchrl/data/tensor_specs.py#L239-L247) for context.
- Since 0.26.0 also returns a truncation output, we have to account for that. We do it the hacky way for now (see [here](https://github.com/facebookresearch/rl/blob/d8742dfcd894f241bcf912b65f06d3c458cf6cd6/torchrl/envs/gym_like.py#L95-L107)) and leave the option of registering the trunctation for later.
- We also use the [`LegacyPixelEnvironmentWrapper`](https://github.com/facebookresearch/rl/blob/fc04fca216e40ff …

[BugFix] Fix gym 0.26 compatibility

---

test/test_trainer.py

Fixes the CI flacky test in `test_trainer.py:test_recorder` by allowing few attempts for the video length check with a slight delay if needed.

[BugFix] Looser check for test_recorder assertion

---

test/test_exploration.py
torchrl/modules/tensordict_module/common.py
torchrl/modules/tensordict_module/exploration.py

Makes it possible to pass spec directly to exploration wrappers. Also checks that the spec can be found, otherwise throws an exception unless explicitly asked not to.

[Feature] Allow spec to be passed directly to exploration wrappers

---

torchrl/collectors/collectors.py

Collectors expect an exploration_mode when created. The current config will pass an empty string by default, which when passed to the policy is interpreted as a fall back on the default "mode" behaviour. However we'd like the collector to fall back on random by default. Since this is somethings that has to do with the collector, this is where the change should take place.

[BugFix] Collector revert to default exploration mode if empty string is passed

---

torchrl/objectives/costs/utils.py
torchrl/trainers/helpers/losses.py
torchrl/trainers/helpers/trainers.py

Renamed `_TargetNetUpdate` to `TargetNetUpdater` in `torchrl.objectives.costs.utils`, making it a public class since it is imported by other classes for the purpose of type annotation.
Replaced all references to the above accordingly, including in docstrings.
Addresses #416

[Naming] Rename _TargetNetUpdate to TargetNetUpdater, making it public

---

test/test_cost.py
test/test_exploration.py
test/test_tensordict.py
test/test_transforms.py
torchrl/collectors/utils.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/tensordict/metatensor.py
torchrl/data/tensordict/tensordict.py
torchrl/modules/functional_modules.py
torchrl/objectives/costs/ddpg.py
torchrl/objectives/costs/dqn.py
torchrl/trainers/trainers.py

This PR enables `TensorDict` to be used without a defined device. 
- If the device is defined, all elements must life on the same device, if it is undefined, elements can live on different devices.
- If the `TensorDict` has no device, then adding elements with an explicit device will _not_ set the device on the `TensorDict`. 
- If the `TensorDict` has a defined device, then elements added to the `TensorDict` will be moved to this device.
See `test/test_tensordict.py:test_tensordict_device` for many examples of intended behaviour.
This change required a number of existing code and tests to be updated where either there was an attempt to access `tensordict.device` (which raises a `RuntimeError` if device is not set) or the test relied on the previous behaviour of the `TensorDict` device …

[Feature] TensorDict without device

---

test/test_tensordict.py
torchrl/data/tensordict/tensordict.py

Enable use of arguments of subclasses of `Sequence` to specify the desired shape for `TensorDict.expand`
close #417 

Make TensorDict.expand accept Sequence arguments

---

torchrl/modules/tensordict_module/exploration.py

This PR fixes the additive noise operator
This change is required because additive noise wasn't doing what it was supposed to do, it never called _add_noise on actions.

[BugFix] Fixed Additive noise

---

test/test_tensordict.py
torchrl/data/tensordict/tensordict.py

For all the `TensorDictBase` child classes, refactoring `set*()` methods, so that `dict -> TensorDict` casting happens only in `_process_input()`. 
Removing duplicate code and making it consistent across the child classes.
close #431 

[Refactor] Refactoring `set*()` methods for `TensorDictBase` class

---

torchrl/envs/transforms/transforms.py

Bug fix for Issue #437 (CatTensors)
Prepended 'next_' to the out_key defaults, added a type check to prevent non-string inputs to out_key, and fixed a spelling mistake in the docstring
A bug fix for #437 

[BugFix] CatTensors: Prepended `next_` to the out_key

---

torchrl/data/replay_buffers/replay_buffers.py

Another patch for #413.
Solving #452

[BugFix] Wrong call to `device_safe` in replay buffer code

---

torchrl/trainers/helpers/envs.py

Re cast dm control actions back to float32
The motivation is that we want to be able to work with float32 actions when using dm_control,

[BugFix]: Fixed dm_control action type casting

---

.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/linux_optdeps/scripts/install.sh
README.md

We changed how one installs functorch: functorch is now included in the PyTorch binary. This PR removes the old installation command which effectively does nothing right now. We'll be removing support for the old installation command after we migrate people off of it.
Test Plan:
- wait for CI

[CI, Doc] Update functorch source installation command

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

Fixes the setting of `env.batch_locked` and `env._inplace_update` for TransformedEnv, as passing them through a Pipe caused a attribute error when calling `__new__`.

[BugFix] TransformedEnv attributes inheritance

---

test/mocking_classes.py
test/test_collector.py
test/test_helpers.py

Cleans up the instantiation of mocking envs to use `__new__` and `__init__` more consistantly

[Feature] Cleanup mocking envs init and new

---

torchrl/trainers/helpers/collectors.py

Added support for single collector in  sync_async_collector

[Feature] Added support for single collector in  sync_async_collector

---

test/test_transforms.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py
torchrl/envs/transforms/vip.py

1. VIP model code in `torchrl/transforms/vip.py`.
2. Testing code appended to `test/test_transforms.py`.
3. Ensured that all tests pass.
New pre-trained visual encoder for RL from FAIR. 

[Feature] VIP Integration

---

torchrl/record/recorder.py
torchrl/trainers/helpers/logger.py
torchrl/trainers/loggers/wandb.py
torchrl/trainers/trainers.py

Minor changes to recorder and logger.

[Refactoring] Minor tweaks to recorder and logger

---

torchrl/envs/common.py
torchrl/envs/model_based/common.py

Allows to deactivate typechecks in envs
We want to be able to deactivates typechecks since it can block code execution when the dtype gets changes (ex autocast to float16)

[Feature]: Deactivate typechecks in envs

---

torchrl/envs/transforms/r3m.py
torchrl/envs/transforms/transforms.py

Fixes a wrongful call to `.parent` in `TensorDictPrimer` at initialization

[BugFix] Fix TensorDictPrimer init

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

Makes it possible to initialize CatTensor in a lazy manner: `CatTensor(out_key="smth")`, such that the in_keys will be retrieved automatically from the parent environment.

[Feature] Lazy initialization of CatTensors

---

test/_utils_internal.py
test/mocking_classes.py
test/test_collector.py
test/test_functorch.py
test/test_tensordict.py
test/test_transforms.py
torchrl/__init__.py
torchrl/_utils.py
torchrl/collectors/collectors.py
torchrl/data/tensordict/memmap.py
torchrl/data/tensordict/metatensor.py
torchrl/data/tensordict/tensordict.py
torchrl/data/tensordict/utils.py
torchrl/envs/common.py
torchrl/envs/vec_env.py
torchrl/modules/__init__.py
torchrl/modules/functional_modules.py
torchrl/modules/models/exploration.py
torchrl/modules/models/models.py
torchrl/trainers/__init__.py
torchrl/trainers/loggers/tensorboard.py
torchrl/trainers/loggers/wandb.py
torchrl/trainers/trainers.py

- monkey-patches a few more functorch functions
- implements tests for `nn.Module` vmap with tensordicts
Following suggestions from @zou3519 we remove and add a batch dimension when vmapping over a tensordict.
Some commended code shows attempts to register TensorDIct in pytree but that failed + it requires to decompose and recompose the tensordict multiple times, while doing complex operations to keep track of the modified batch size. Besides the fact that it did not work, it also seemed suboptimal from a compute time perspective.

[Refactoring] Import at root to enable vmap monkey-patching

---

torchrl/envs/libs/dm_control.py

This PR handles the import of the `torchrl.envs.libs.dm_control`, when the `dm_control` library is not installed. Specifically, it raises the `ImportError`.
close #506 

[BugFix] Changing the dm_control import to fail if not installed

---

.circleci/config.yml
.github/workflows/nightly_build.yml
README.md

Added code coverage to the CI pipeline
Internal task

[CI] Add coverage with codecov

---

torchrl/csrc/segment_tree.h

Usage of relative imports in cpp files allows to not rely on folder structure

[Quality] Use relative imports for local c++ deps

---

test/test_tensordict.py
torchrl/data/tensordict/tensordict.py

Implement new function `make_tensordict()` that can automatically create tensordict from keyword arguments. When batch_size is unspecified, it assumes maximum possible batch_size based on the input source dict. 
Closes #518 

[Feature] Add make_tensordict() function

---

README.md
examples/EXAMPLES.md

see title
minor readme fixes and improvements

[Doc] Misc readme fixes

---

torchrl/trainers/helpers/envs.py

[BugFix] Replacing inference_mode decorator with no_grad to fix state_dict loading error

---

torchrl/envs/common.py
torchrl/envs/env_creator.py
torchrl/envs/transforms/transforms.py
torchrl/envs/vec_env.py

In some instances, the meta data of the base_env in a transformed env are sent to cpu when the meta data is passed to a process.

[BugFix] Transformed ParallelEnv meta data are broken when passing to device

---

.circleci/unittest/linux_optdeps/scripts/environment.yml
test/test_helpers.py
test/test_loggers.py

Fix optional broken optional imports

[BugFix] Fix optional imports

---

.circleci/unittest/linux/scripts/setup_env.sh
examples/configs/replay_buffer/circular.yaml
examples/configs/replay_buffer/prioritized.yaml
test/test_configs.py

Minor changes to configs and config test to fit new function signature
`torchrl.data.replay_buffers.storages.Storage`'s init now has argument `max_size` instead of the previous `size`.
Changing `size` to `max_size in the configs and tests too.
Also skipping tests that require halfcheetah rendering on OSX to avoid `mujoco.FatalError: gladLoadGL error`. 
Those tests pass on my mac. MuJoCo (or its dependencies) might not be installed properly in the test environment, but I couldn't fix it.

minor test fix to pass ci

---

test/test_collector.py
torchrl/collectors/collectors.py

This PR fixes a bug with data collectors that saw some keys being omitted from the output when e.g. random actions were applied during initialisation.
Data collectors will now attempt to determine keys from the policy spec if it is supplied and complete, otherwise they will perform a short rollout with the policy to determine which keys will be returned.
Closes #505 
I still need to add a test, currently seeing an error on one particular test I don't understand.

[BugFix] Restore missing keys in data collector output

---

test/mocking_classes.py
test/smoke_test.py
test/smoke_test_deps.py
test/test_collector.py
test/test_cost.py
test/test_distributions.py
test/test_env.py
test/test_exploration.py
test/test_functorch.py
test/test_helpers.py
test/test_loggers.py
test/test_modules.py
test/test_postprocs.py
test/test_rb.py
test/test_shared.py
test/test_tensor_spec.py
test/test_tensordict.py
test/test_tensordictmodules.py
test/test_trainer.py
test/test_transforms.py

[Lint] reorganize imports

---

test/test_exploration.py
test/test_modules.py
torchrl/modules/models/exploration.py
torchrl/modules/models/models.py
torchrl/modules/models/utils.py

Implemented a `device` argument for modules in `torchrl.modules.models` to allow them to be directly constructed on a particular device, rather than first constructing it then moving it with `.to()`. This follows the behaviour of most modules in `torch.nn`. Updated `test_modules.py` to make use of this.
However, an arbitrary `nn.Module` subclass does not necessarily support the `device` argument, in particular for modules that do not contain parameters or buffers. The utility function added in `torchrl/modules/models/utils.py` addresses this. This functionality is tested in `test_mlp` in `test_modules.py`, parameterised with both `nn.ReLU` (which does not support `device`) and `nn.PReLU` (which does).
Addresses #507
What types of changes does your code introduce? Remove all that do not …

[Feature] Implemented `device` argument for `modules.models`

---

torchrl/modules/tensordict_module/exploration.py

Fixes a bug where a field in a tensorspec could be none but is not caught by AdditiveGaussian exploration wrapper

[BugFix] Additive gaussian exploration spec fix

---

test/test_exploration.py
test/test_helpers.py
test/test_tensordictmodules.py
torchrl/collectors/collectors.py
torchrl/data/tensor_specs.py
torchrl/modules/tensordict_module/common.py
torchrl/modules/tensordict_module/sequence.py
torchrl/trainers/helpers/models.py
torchrl/trainers/loggers/wandb.py

Fixes a bunch of device-related bugs in the way specs are created in TensorDictModules and how init rollouts are achieved in data collectors

[BugFix] Various device fix

---

test/test_collector.py
torchrl/collectors/collectors.py
torchrl/modules/models/models.py

This PR makes changes to the collector classes in order that users can pass simple `nn.Module`s as policies.
It checks that the signature of the `forward` method matches the `next_` entries in the environment's `observation_spec`. The first returned value is assumed to be the action while remaining return values are simply enumerated and labelled `output1`, `output2`, etc.
Closes #544

[Feature] Allow collectors to accept regular modules as policies

---

test/test_tensordict.py
torchrl/data/tensordict/memmap.py
torchrl/data/tensordict/tensordict.py

Makes TensorDict comparison fault-tolerant

[BugFix] TensorDict comparison

---

test/test_collector.py
torchrl/collectors/collectors.py

[BugFix] Fix SyncDataCollector reset

---

torchrl/data/replay_buffers/storages.py

When a replay buffer is being created, the storage is printed on the log. This print being printed in alphabetical order was a nice to have and this change brings in that.
Close issue #508

[Feature] Log printing in alphabetical order when creating a replay buffer

---

docs/source/reference/data.rst
test/mocking_classes.py
test/test_actors.py
test/test_cost.py
test/test_env.py
test/test_helpers.py
test/test_modules.py
test/test_tensor_spec.py
test/test_trainer.py
test/test_utils.py
torchrl/_utils.py
torchrl/data/tensor_specs.py
torchrl/envs/libs/gym.py
torchrl/modules/tensordict_module/actors.py
torchrl/objectives/dqn.py
torchrl/trainers/helpers/envs.py
torchrl/trainers/helpers/models.py

Added alternative to one-hot encoding for action spaces with categorical features.
Implementing feature #538.
Checklist from #538:
Current implementation seems to couple different parts of TorchRL quite tightly as there is quite a few places where it is assumed that the action space is one-hot. Perhaps, a more generic action-space object that encapsulates manipulation with values and that is shared across losses, actors, hooks, etc. (as a `nn.Module` maybe) might be a worth investment in future.
The mode is turned on by `export CATEGORICAL_ACTION_ENCODING=True` command, and it is turned off by default. Another alternative could be to provide it through the config-file, however this, again, would require a bit …

[Feature] Categorical encoding for action space

---

test/test_rb.py
torchrl/data/replay_buffers/rb_prototype.py
torchrl/data/replay_buffers/samplers.py
torchrl/data/replay_buffers/storages.py

The prototype modular Replay Buffer has a bug (#606) when storage is shared across buffers. This happens because the different parts implicitly assume to always be aware of changes in storage, which was no true. This change introduces an API for storage to signal back to the buffers that changes were made. Buffers can then handle this signal however and whenever they see fit.
close #606 
If you are unsure about any of these, don't hesitate to ask. We are …

[BugFix] ReplayBuffer's storage now signal back when changes happen

---

test/test_tensordict.py
torchrl/data/tensordict/tensordict.py

I began adding support for a null `dim` argument in `TensorDict.squeeze`. However, this code is still buggy as `TensorDict.unsqueeze` is called during the process of creating a SqueezedTensorDict, and `unsqueeze` should not support a null `dim` argument.
This resolves #592.

Add support for null `dim` argument in `TensorDict.squeeze`

---

test/test_memmap.py
torchrl/data/tensordict/memmap.py

Fixes the behaviour of memmap tensors where, when a tensor is deserialized, two objects are opened.
This PR guarantees that when a memmap tensor is passed to another process, no file is opened until an operation is made on the memmap tensor.
Furthermore, if the same tensor has already been sent on this process with different index, one can simply use `tensor1.copy_(tensor2)` to re-use the memmap array from `tensor1` and re-write the index of `tensor2` onto `tensor1`. That way, the memmap array is never opened for `tensor2`.

[BugFix] `copy_` changes the index if the dest and source memmap tensors share the same file location

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

TransformedEnv of a TransformedEnv should just append the transforms, not create a new TransformedEnv
close #602 
Failing tests investigation is in progress

[Feature] Unfold transforms for folded `TransformedEnv`

---

torchrl/data/replay_buffers/rb_prototype.py

Calls `ReplayBuffer.extend` with stacked tensordicts rather than stacked tensordicts or a list of tensordicts depending on the input.
cc @adityagoel4512

[BugFix] make TensorDictReplayBuffer.extend call super().extend with stacked_td

---

docs/source/reference/modules.rst
test/test_cost.py
test/test_tensordictmodules.py
torchrl/modules/tensordict_module/common.py
torchrl/objectives/dqn.py

Made DQNLoss and DistribtutionalDQNLoss compatible with value networks that are regular nn.Module. A custom helper function is written that checks if an nn.Module has certain properties (namely in_keys and out_keys that match a certain signature). If there is a signature mismatch, it throws an error. If there are no in_keys and out_keys attributes, then the nn.Module is wrapped in the given wrapper_type with the (optional) desired in_keys and out_keys list.
`close #607 `
If you are unsure about any of these, don't hesitate …

[Feature] Make DQN compatible with nn.Module

---

test/test_rb.py

Replaced torch.testing.assert_allclose with torch.testing.assert_close
`close  #643 `

[BugFix] Fix broken unit tests caused by removal of torch.testng.assert_allclose

---

test/test_modules.py
torchrl/modules/models/models.py

Creation of the GRUNet to control agents in QMIX

[Feature] Qmix - Gru Net

---

test/test_transforms.py
torchrl/data/replay_buffers/rb_prototype.py
torchrl/envs/transforms/transforms.py

Once a transform has been assigned a parent, it can't be assigned another parent anymore. A check in the Transform.set_parent method was added which raises an exception if the parent has already been set. A reset_parent method was also added so existing operations such as appending new transforms work with the new check.
Following code should raise an exception because we are reassigning t1's parent:
```
env =  TransformedEnv(GymEnv("Pendulum-v1"))
t1 = RewardScaling(0, 1)
t2 = RewardClipping(0.1, 0.5)
env.append_transform(t1)
env.append_transform(t2)
env.append_transform(t1)
print(env.transform[-1])
```
`close #636`

[BugFix] Prevent transform parent from being reassigned

---

examples/dreamer/dreamer_utils.py
test/test_env.py
test/test_transforms.py
torchrl/envs/transforms/r3m.py
torchrl/envs/transforms/transforms.py
torchrl/envs/transforms/vip.py
torchrl/record/recorder.py
torchrl/trainers/helpers/envs.py

Refactoring change to fix the naming inconsistency of variables in different modules. In the transforms module and related module in RL renamed all useage of key_in to in_keys e.g. keys_inv_in becomes in_keys_inv 
Working on this change to close https://github.com/pytorch/rl/issues/611. close #611 

[Naming] Rename keys_in to in_keys in transforms.py and related modules

---

test/test_helpers.py
test/test_transforms.py
torchrl/envs/transforms/transforms.py
torchrl/envs/transforms/utils.py

Relies on `transform.step` instead of `forward` which we will reserve for Replay buffers.
`transform.step` will ultimately work on the `tensordict["next"]` nested tensordict only.

[Feature] Move `transform.forward` to `transform.step`

---

torchrl/trainers/helpers/trainers.py

Possible bug: using the make_trainer helper function in a script can raise an error if you want to use GPU, because mini batches seem to be placed by default in CPU if you don't use a replay buffer. I added a line to register a "process_optim_batch" operation so it places the mini batches to whatever device the networks are in, avoiding this error.
I was trying to run the PPO example on GPU and kept complaining about the data and the weights being in different devices (CPU and GPU).

[BugFix] make_trainer possible bug for on-policy cases

---

.github/workflows/docs.yml
.github/workflows/nightly_build.yml
.github/workflows/wheels.yml
benchmarks/storage/benchmark_sample_latency_over_rpc.py
docs/source/reference/data.rst
examples/distributed/distributed_replay_buffer.py
examples/torchrl_features/memmap_speed_distributed.py
test/smoke_test.py
test/test_collector.py
test/test_cost.py
test/test_env.py
test/test_rb.py
test/test_shared.py
test/test_trainer.py
test/test_transforms.py
torchrl/collectors/collectors.py
torchrl/data/__init__.py
torchrl/data/postprocs/postprocs.py
torchrl/data/tensordict/__init__.py
torchrl/data/utils.py
torchrl/envs/common.py
torchrl/envs/model_based/common.py
torchrl/modules/models/exploration.py
torchrl/modules/planners/cem.py
torchrl/modules/tensordict_module/actors.py
torchrl/modules/tensordict_module/common.py
torchrl/modules/tensordict_module/exploration.py
torchrl/modules/tensordict_module/probabilistic.py
torchrl/modules/tensordict_module/sequence.py
torchrl/trainers/trainers.py

Updates to #650 TensorDict deprecation in favour of standalone [TensorDict](https://github.com/pytorch-labs/tensordict/). CI should be passing and I've killed remaining references to the TorchRL `TensorDict` class.
I haven't touched the tutorials as instructed.

Relying on the standalone tensordict -- phase 1 updates

---

.pre-commit-config.yaml

The lint pipeline on CircleCI appears to be failing for all commits at the moment. 
This PR changes the repo to GitHub per the [flake8 docs](https://flake8.pycqa.org/en/latest/user/using-hooks.html#usage-with-the-pre-commit-git-hooks-framework).

[BugFix] Use GitHub for flake8 pre-commit hook

---

torchrl/trainers/helpers/collectors.py

The method __make_collector_ in _trainers/helpers/collectors_ is supposed to return a _MultiDataCollector. However, it can return a SyncDataCollector in the case of synchronous data collection with only 1 environment. So maybe it should return a _DataCollector.
Change only required for documentation, it does not produce any error.

[Doc] _make_collector helper function 

---

torchrl/trainers/trainers.py

The example provided in the docstring of the BatchSubSampler class can not be executed. Just changed the TensorDict shape so it runs correctly. 
I tried to run the example to better understand the BatchSubSampler class and I got this error:
> RuntimeError: batch_size are incongruent, got [torch.Size([2, 10]), torch.Size([13, 10])], -- expected torch.Size([13, 10])

[Doc] BatchSubSampler class docstrings example

---

torchrl/objectives/ppo.py

The PPOLoss class executes
`self.advantage_module = advantage_module.to(self.device)
`
whether the optional parameter advantage_module is provided or not. I just added and if statement to solve the problem.
I was trying to run the advantage for PPO outside the objective class, and got the following error:
> AttributeError: 'NoneType' object has no attribute 'to'

[BugFix] PPO objective crashes if advantage_module is None

---

setup.py

Installing torchrl does not require tensordict. This PR fixes this.

[Doc] Fix missing tensordict install for doc

---

test/test_modules.py
torchrl/modules/models/models.py

Collectors and BatchSubSample produce batches with shape (Batch, Length, Channels, Height, Width), but shapes with more than 4 dimensions raise an error when passed through a CNN. 
I just added an adjustment so that for batches with 5 dimensions, then Batch and Length dimension are collapsed before the forward pass and expanded right after it.
I was trying to train on an Atari 2600 environment and the forward pass raised the following error:
> RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [8, 32, 4, 84, 84]

[BugFix] ConvNet forward method with tensors of more than 4 dimensions

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

Implement `standard_normal` kwarg for RewardScaling 
Fixes #646 
Brings consistency to RewardScaling wrt ObservationNorm by implementing the `standard_normal` kwarg with the existing regular transform

[Feature] add `standard_normal` for RewardScaling

---

test/_utils_internal.py
test/smoke_test_deps.py
test/test_collector.py
test/test_env.py
test/test_libs.py
test/test_transforms.py
torchrl/envs/libs/gym.py

Replaces direct gym version checks with `@implement_for` decorated functions (primarily `gym.py` and tests), except some places in tests where direct check still looks better (less complicated). Extracted gym environments version definition logic in tests.
This simplifies the logic of functions that check for gym versions, improves readability and makes it easier to adapt for bc-braking changes in gym. Proposed by @vmoens.

[Refactoring] Replace direct gym version checks with decorated functions (#)

---

.github/workflows/docs.yml
docs/source/index.rst

This PR updates the docs CI/CD to pull in the tensordict documentation and host it at `/tensordict`. It also adds a banner to the existing docs to direct users there.
The build of the TensorDict docs happens over in the tensordict repo. The built docs are pushed to the `gh-pages` branch and pulled in here. 
cf. pytorch-labs/tensordict#61
It is currently not trivial to host TensorDict docs through pytorch-labs organisation, so it's easier to host under the TorchRL docs for now until a permanent solution is found.

[Docs] Host TensorDict docs inside TorchRL docs

---

.github/workflows/docs.yml

Docs build was failing because `git-subtree` is not installed in the runner.
Rather than installing , we just use a clone instead and clean up the nested Git repo.

[BugFix] Fix docs build

---

torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

Some transform configuration can't be worked out if the parent env is not set.
We raise meaningful error messages in those cases.
TODO: test the error messages
cc @altre

[BugFix] Proper error messages for orphan transform creation

---

.circleci/unittest/linux_examples/scripts/run_test.sh
README.md
docs/source/reference/objectives.rst
docs/source/reference/trainers.rst

Adds the missing A2C doc and runs test in the example test pipeline.
@albertbou92

[Doc, Test] Add A2C script test and doc

---

test/test_rb.py
torchrl/data/replay_buffers/storages.py

Initialising the class LazyTensorStorage with a nested TensorDict raises the following error
> RuntimeError: the number of sizes provided (1) must be greater or equal to the number of dimensions in the TensorDict (2)
It it due to a call to _tensor.expand_ . I just added the the dimensions of tensor to the output shape, and now it does not crash anymore.
The error can be reproduced with the following code:
```
import torch
from torchrl.data.replay_buffers.storages import LazyTensorStorage
dummy_td = TensorDict({
"key1": torch.ones(3, 4),
"key2": torch.ones(3, 4),
"next": TensorDict({
"next_key1": torch.ones(3, 4),
"next_key2": torch.ones(3, 4),
}, [3, 4])
}, [3, 4])
mystorage = LazyTensorStorage(1000)
mystorage._init(dummy_td)
```
What types of changes …

[BugFix] Initialising the classes LazyTensorStorage  with a nested TensorDict raises error

---

.circleci/unittest/linux_examples/scripts/run_test.sh

Removes `init_random_frames` from the A2C flags in the example tests

[BugFix] Fix init_random_frames in A2C example test

---

README.md
knowledge_base/VERSIONING_ISSUES.md

This PR:
- Documents an issue with PyTorch versioning
- Proposes some workarounds to make the library work with older PyTorch versions installed.
- Links such documentation in the troubleshooting section of the README
When using torch at lower version than 1.13 and installing the package stable version via pip, an undefined symbol error appears when trying to import the module. 
Related to https://github.com/pytorch/rl/issues/689.

[Doc] Document undefined symbol error with torch version < 1.13

---

test/test_rb.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/writers.py

In the class _RoundRobinWriter_, in the _extend_ method, seems like some of the conditions could be unnecessary. Maybe I am missing something, but if 
`cur_size = self._cursor
`
seems like the last two conditions are duplicated code. The code raises no error, but maybe the extra conditions can be removed.

[BugFix] RoundRobinWriter, possible duplicated code in the extend method

---

docs/source/reference/trainers.rst
test/test_trainer.py
torchrl/trainers/trainers.py

The new type of hook, `OptimizerHook`, is added as suggested in #704.
See the suggested change in #704.
Backward compatibility with the existing `optimizer` parameter of `Trainer.__init__` is respected.
Minor breaking change: previously `grad_norm` key in the `losses_td` is now `grad_norm_0`.
The change made in the documentation is very initial: `optimizer` hook is just briefly mentioned in the list of possible hooks and the `OptimizerHook` class is added to the "Trainer and hooks" table. Probably, wider documentation coverage of the new hook type is …

[Feature] Add OptimizerHook

---

README.md

Correct links to tutorials in README.
Closes #723

[Docs] Update tutorial links in readme

---

torchrl/envs/transforms/transforms.py

Fixes a bug related to #727 where colliding in_keys and out_key from CatTensor produce no output

[BugFix] Avoid wrongfully erasing observation keys from tensordict in CatTensors

---

docs/source/reference/collectors.rst

Some more doc for data collectors

[Doc] More doc for data collectors

---

docs/source/reference/envs.rst
test/_utils_internal.py
test/test_libs.py
torchrl/envs/utils.py

Exposes `test_fake_tensordict` to the users as a sanity check for custom environments.

[Feature] Port test_fake_tensordict to torchrl

---

README.md
docs/source/reference/modules.rst
test/test_cost.py
test/test_exploration.py
test/test_helpers.py
test/test_modules.py
test/test_tensordictmodules.py
torchrl/modules/__init__.py
torchrl/modules/tensordict_module/__init__.py
torchrl/modules/tensordict_module/actors.py
torchrl/modules/tensordict_module/probabilistic.py
torchrl/objectives/a2c.py
torchrl/objectives/ppo.py
torchrl/objectives/redq.py
torchrl/objectives/reinforce.py
torchrl/objectives/sac.py
torchrl/trainers/helpers/collectors.py
torchrl/trainers/helpers/models.py
tutorials/sphinx-tutorials/coding_ddpg.py
tutorials/sphinx-tutorials/tensordict_module.py
tutorials/sphinx-tutorials/torchrl_demo.py

This PR adopts the prototype refactored `ProbabilisticTensorDictModule` and `ProbabilisticTensorDictSequential` classes introduced in pytorch-labs/tensordict#104
Currently WIP while I work through the failing tests, but new usage should be clear. Most important changes are in:
- `torchrl/modules/tensordict_module/probabilistic.py` - refactors `SafeProbabilisticModule` and introduces the new `SafeProbabilisticSequential` class
- `torchrl/modules/tensordict_module/actors.py` - note the change to `ActorValueOperator` in particular
Most other changes are just updating usage.
This PR supercedes #719, though I will leave that open for now until it's clear we want to move ahead with the approach laid out in this PR and pytorch-labs/tensordict#104
TODO:

[Refactor] Adopt prototype ProbabilisticTensorDictModule and ProbabilisticTensorDictSequential

---

torchrl/data/tensor_specs.py
torchrl/objectives/value/advantages.py

We return the `'value_target'` in the GAE output keys to allow the value error to be computed without  pain.

[Feature] Make GAE return a 'value_target' entry

---

test/test_rb.py
torchrl/data/replay_buffers/samplers.py

Adds a SamplerWithoutReplacement for the modular RB

[Feature] SamplerWithoutReplacement

---

.github/workflows/docs.yml
CONTRIBUTING.md

This PR updates the workflow [docs.yml](https://github.com/pytorch/rl/blob/main/.github/workflows/docs.yml) to run it during a PR. However, it will deploy the documentation only when the commit lands on master.
**WARNING**: The use of dispatch may be affected by this change. A dispatch event may not deploy the documentation on gh-pages.
TorchRL CI (on CircleCI) tests all the features of the library, except the build of the documentation.
This would be of little concern if that doc was static, but it actually runs a bunch of tutorial scripts that may break at times.
This PR allows to build the documentation during each PR.
If you are …

[Doc, CI] Update doc workflow to run on PR and only publishes doc on main.

---

examples/a2c/a2c.py
examples/a2c/config.yaml
examples/ppo/config.yaml
examples/ppo/ppo.py
test/test_cost.py
test/test_helpers.py
torchrl/objectives/a2c.py
torchrl/objectives/ppo.py
torchrl/objectives/reinforce.py
torchrl/objectives/value/advantages.py
torchrl/trainers/helpers/losses.py
torchrl/trainers/trainers.py

Changes the advantage API such that 
1. computing the value error is done in a standardized way using the target value computed by the advantage module
2. removes the possibility of using the advantage module inside PPOLoss to give a better control over its behaviour to the user

[Feature] Better advantage API for higher order derivatives

---

test/test_transforms.py
torchrl/envs/common.py
torchrl/envs/transforms/transforms.py

NoopReset should not be used after a batched env but inside (ie tied to every singe env).
We add an error message for this

[BugFix] Fix NoopReset in parallel settings

---

test/test_tensordictmodules.py
torchrl/modules/tensordict_module/probabilistic.py
tutorials/sphinx-tutorials/tensordict_module.py
tutorials/sphinx-tutorials/torchrl_demo.py

pytorch-labs/tensordict#109 fully adopts the prototype probabilistic modules. Here we update the imports in TorchRL accordingly.
Should be merged alongside the tensordict changes.

[Refactor] Drop prototype imports

---

torchrl/envs/common.py

This cahnge adds annotations for abstract methods and fixes a repeated override
Code cleaning

Minor cleaning in BaseEnv classes

---

torchrl/envs/common.py

1. Removed  identical `set_seed` override in `_EnvWrapper`
2. Updated type hints in `set_seed` of `EnvBase`
3. Made `_init_env()` abstract in `_EnvWrapper`
We now enforce inheritors of  `_EnvWrapper` to implement `_init_env()`
I have checked that the tests in `test_env.py` which I am able to run (without external libraries and cuda) are all passing and linted.

Cleaning in envs `common.py`

---

torchrl/objectives/value/advantages.py

Reset the default value_key in the advantages modules as the first key may not be the value.
An additional check is run to make sure the key can be found in the outputs from the module
cc @albertbou92

[BugFix] Reinstantiate custom value key for multioutput value networks

---

test/test_transforms.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

Add a transform that counts the steps from a reset and sets the done state to True after a certain number of steps.
This transform can be used in parallel / multi env settings, as the counter has the size of the env.batch_size. The "step_counter" key will be added to the output of tensordict when reset or step in the environment.

[Feature] Add Step Counter transform

---

test/mocking_classes.py
test/test_env.py
torchrl/envs/vec_env.py

[BugFix] Batched environments with non empty batch size

---

torchrl/envs/libs/gym.py

Previously only bounded tensors are created from gym specs.
In this PR we create unbounded tensor specs if all the high and low values of the gym Box are inf

Allow undounded boxes creation from gym spaces

---

torchrl/collectors/collectors.py
torchrl/envs/common.py

Improves the error messages or remove unreadable error messages during program closure as pointed in #762.
To test the feature with envs and  collectors: error messages after this PR should be more readable in these two cases:
```
python -c """
import gym
from torchrl.envs.libs.gym import GymWrapper
gym_env = gym.make('CartPole-v1')
env = GymWrapper(gym_env)                        
"""                                              
```
and for collectors:
```
MAX_IDLE_COUNT=10 python -c """
import gym
from torchrl.envs.libs.gym import GymWrapper
from torchrl.envs import EnvCreator, ParallelEnv
gym_env = gym.make('CartPole-v1')
env = ParallelEnv(4, EnvCreator(lambda: GymWrapper(gym_env)))
from torchrl.collectors.collectors import RandomPolicy, MultiaSyncDataCollector
c = …
```

[Feature] Better error messages during GC

---

test/test_libs.py
torchrl/envs/libs/brax.py
torchrl/envs/vec_env.py

[BugFix] Sorting nested keys

---

README.md

[Doc] README index

---

.circleci/config.yml
packaging/build_wheels.sh
packaging/pkg_helpers.bash
packaging/windows/internal/cuda_install.bat
packaging/windows/internal/vc_env_helper.bat
packaging/windows/internal/vc_install_helper.sh
packaging/windows/internal/vs2017_install.ps1

- Add `binary_win_wheel` job to CircleCI 
- Run this job in `build` workflow for:
- `cu_version=cpu,cu116,cu117`
- `python_version=3.7,3.8,3.9,3.10`
TorchRL is currently built and tested for OsX and Linux only and there is some demand for a windows built.
- New feature
- Add build for Windows wheels in CircleCI for the CUDA and Python versions mentioned above.
- Add scripts needed to run the build in `packaging/windows` (slightly modified from Torchvision's ones)

Add windows wheel build to CircleCI

---

examples/dreamer/dreamer_utils.py
test/test_helpers.py
test/test_transforms.py
torchrl/envs/transforms/transforms.py
torchrl/trainers/helpers/envs.py

FlattenObservation has default first and last dim `0` and `-3` which may not be intuitive. Let's remove the defaults.

[Refactor] Simplify FlattenObservation default kwargs

---

test/test_tensor_spec.py
torchrl/data/tensor_specs.py

Should fix #815. Just checking the shape of an input `val` tensor, before splitting it. Add add one line in tests to check the false case.

[BugFix] Fix MultOneHotDiscreteTensorSpec.is_in

---

test/test_tensor_spec.py
test/test_trainer.py
torchrl/envs/transforms/transforms.py

Just a minor improvement to the code quality as mentioned in #818. That remove the creation of a list (via for comprehension) when we call the function `all()`.

[CodeQuality] call all() without making a list

---

torchrl/collectors/collectors.py
torchrl/envs/libs/brax.py
torchrl/envs/libs/jumanji.py
torchrl/envs/libs/vmas.py
torchrl/envs/vec_env.py
torchrl/modules/tensordict_module/common.py
torchrl/objectives/deprecated.py
torchrl/objectives/redq.py
torchrl/objectives/sac.py

[Minor] Better error reporting

---

test/test_env.py
torchrl/envs/gym_like.py

`info_key_reader` crashes when the device is not the default "cpu".
This PR solves this issue.

[BugFix] Device of info specs

---

knowledge_base/MUJOCO_INSTALLATION.md
test/test_libs.py
torchrl/data/tensor_specs.py
torchrl/envs/common.py
torchrl/envs/gym_like.py
torchrl/envs/libs/gym.py
torchrl/envs/utils.py

Introduces some changes in the env API to allow for:
- Reading infos at reset
- Completing reset data when info is missing
- using zero instead of rand for fake_tensordict (@matteobettini)
- better checks in check_env_spec and better error messages

[BugFix] Fix envs specs and info reading

---

test/test_libs.py
torchrl/envs/libs/vmas.py

This PR reintroduces the dtype checks for vmas which were removed in #825

[Feature] Dtype in vmas tests

---

torchrl/data/tensor_specs.py
torchrl/envs/transforms/r3m.py
torchrl/envs/transforms/vip.py

Fixes a bug where nested composite specs lead to an error when calling the r3m obs spec transform.

[BugFix] Fix R3M observation spec transform

---

torchrl/trainers/trainers.py

Removed the `value.any()` for `solved` key in Recorder
In `mj_envs`,  `solved` key is returned at every step that indicates whether the task has reached the goal. Adding `value.any()` returns a single indicator for all the trajectories. An example use case of `solved` key is [here](https://github.com/vikashplus/mj_envs/blob/77274c05f085d052b7efb65fab9cb15269281f9b/mj_envs/envs/env_base.py#L356)
- [ x] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)

Updating Recorder to accomodate "solved" key

---

README.md
torchrl/collectors/collectors.py

This one line PR modifies the way the step_count is set in collectors.
With the current
```
step_count += 1
```
The step_count is not set in the case the get method returns a cloned object, which happens if 
```
self._tensordict = env.reset() 
```
Is created from a _reset method that returns LazyStacks

[BugFIx] Changed "set_count" set in collectors

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

Adds a `keep_dims` kwarg to `ObservationNorm.init_stats` to get "unsqueezed" summary stats + fixes a bug in standard normal conversion.
Aslo fixes a bug in RewardSum tensordict intantiation.

[Feature, BugFix] ObservationNorm keep_dims and RewardSum init

---

test/test_shared.py
test/test_transforms.py
torchrl/envs/transforms/transforms.py

Adapts the CatFrames transform to match the preallocation of #841 
@albertbou92 can you have a look at the registering of the buffers? In your case I thing that doing `transform.to(device)` will not map the buffers and may lead to a bug (although moving transforms during training may not make much sense)

[Feature] Refactor CatFrames using a proper preallocated buffer

---

.github/workflows/nightly_build.yml
.github/workflows/wheels.yml

- For `nightly-build` Github Actions workflow, add jobs 
- `build-wheel-windows`
- `test-wheel-windows`
- `upload-wheel-windows`.
- For `wheels` Github Actions workflow:  add `build-wheel-windows` job and `os:windows` case to `test-wheel`
There is a need for a TorchRL build for Windows, hence the need for those Github actions (as for Linux and MacOS which are already supported).

[CI] Add Github-Actions workflows for Windows wheels & nightly-build

---

test/test_transforms.py
torchrl/envs/transforms/r3m.py
torchrl/envs/transforms/vip.py

Allows R3M and VIP to be initialized with the torchvision's weights instead of the dedicated weights from the papers.
cc @ShahRutav 
Testing this PR:
```python
from torchrl.envs import R3MTransform, VIPTransform
from torchvision.models import ResNet18_Weights, ResNet34_Weights, \
ResNet50_Weights
model_map = {
"resnet18": ResNet18_Weights,
"resnet34": ResNet34_Weights,
"resnet50": ResNet50_Weights,
}
for model in ("resnet18", "resnet34", "resnet50"):
for download in (True, "IMAGENET1K_V1"):
if isinstance(download, str):
for i in range(2):
if i == 0:
download == getattr(model_map[model], download)
R3MTransform(in_keys=["pixels"], model_name=model, download=download)
else:
R3MTransform(in_keys=["pixels"], model_name=model, download=download)
model_map = {
"resnet50": ResNet50_Weights,
}
for …
```

[Feature] Loading R3M and VIP from ResNet

---

examples/td3/td3.py
test/test_collector.py
test/test_cost.py
test/test_postprocs.py
test/test_trainer.py
test/test_transforms.py
torchrl/collectors/collectors.py
torchrl/collectors/utils.py
torchrl/data/postprocs/postprocs.py
torchrl/envs/common.py
torchrl/envs/transforms/transforms.py
torchrl/envs/vec_env.py
torchrl/modules/models/recipes/impala.py
torchrl/trainers/trainers.py
tutorials/sphinx-tutorials/coding_ddpg.py
tutorials/sphinx-tutorials/coding_dqn.py

`StepCount` and the collectors both assign a `"step_count"` key that it would be wise to use only once.
This PR solves this issue.
cc @riiswa

[BugFix] Avoid collision of "step_count" key from transform and collector

---

examples/dreamer/dreamer_utils.py
test/test_helpers.py
test/test_rb.py
test/test_transforms.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py
torchrl/trainers/helpers/envs.py
tutorials/sphinx-tutorials/coding_dqn.py

Refactors the buffer init of `CatFrames`. 
After this PR, buffers won't be filled with 0s but with copies of the first frame. The advantage of doing so is that the values are not drastically different from the rest of the rollout.
We also set a default `"_reset"` key in the tensordict to keep track of the successive calls to `reset` and `_call`: in `"_reset"` has non-zero elements, then a copy of the data must be executed during the transform.
This in-turn impact the `check_envs` method that must now ignore private keys in the tensordict.
We also remove the default values for `N` and `cat_dim` which we rename `dim` for consistency with other transforms.
cc @matteobettini again because of the `"_reset"` key.
cc @albertbou92

[Refactor] Better init for CatFrames buffers + removing default init values

---

torchrl/envs/common.py

Run checks when creating a fake tensordict as the nested TD batch_size needs to be updated.

[BugFix] Run checks when creating fake_td

---

test/_utils_internal.py
test/test_rb.py
test/test_specs.py
torchrl/data/tensor_specs.py
torchrl/envs/common.py
torchrl/envs/transforms/transforms.py

Changes the memory location of the tensors for the bounded tensorspecs. The goal is to free space on devices by storing these on RAM instead.
To make the rollout collection faster, we also disable the observation spec checking by default. This can be reinstantiated via `CHECK_SPEC_ENCODE=True python myscript.py`.

[Refactor] Box device

---

.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/linux/scripts/setup_env.sh
.github/workflows/test-linux-cpu.yml

Migrate unit tests from CircleCI to GitHub Actions
The direction is to move unit tests to GitHub Actions. 
No change to functionality.
- [x ] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)

Linux CPU unit test workflow using GitHub Actions

---

.circleci/unittest/helpers/coverage_run_parallel.py
.circleci/unittest/linux/scripts/run_test.sh
.circleci/unittest/linux_examples/scripts/run_test.sh
.circleci/unittest/linux_libs/scripts_brax/run_test.sh
.circleci/unittest/linux_libs/scripts_envpool/run_test.sh
.circleci/unittest/linux_libs/scripts_gym/run_test.sh
.circleci/unittest/linux_libs/scripts_habitat/run_test.sh
.circleci/unittest/linux_libs/scripts_jumanji/run_test.sh
.circleci/unittest/linux_libs/scripts_vmas/run_test.sh
.circleci/unittest/linux_olddeps/scripts_gym_0_13/run_test.sh
.circleci/unittest/linux_optdeps/scripts/run_test.sh
.circleci/unittest/linux_stable/scripts/run_test.sh

Fix for #879 - I could verify that the coverage script used in circleci does not properly collect coverage data when multiprocessing is used. In order to fix this, it. was neccessary to change the way the coverage script is invoked. While coverage.py supports collecting coverage information even if the covered process launches subprocesses,it is not supported to pass command line arguments to the script in that case ( since subprocesses don't get that commandline ).
I created a helper script called coverage_run_parallel.py which writes a temporary config file for coverage.py ( cleaned up on exit, including abnormal exit ) and invokes that script in turn, passing the info to use that config via environment variables.
Test Plan:
Running the code coverage scripts locally ( on an M1 Mac …

[Bugfix] Codecov does not cover multiprocessed tests #879

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

Fixes a bug when re-expanding a `Compose` transform onto a new `Compose` transform:
```python
Compose(*other_compose.clone())
```
as the `other_compose` keeps the original `_container` and hence refuses to reassign the transforms to the other `Compose`.

[BugFix] Compose cloning fix

---

docs/source/reference/trainers.rst

Adds the `torchrl.record` first level classes to the doc

[Doc] Add record utils to doc

---

docs/source/reference/data.rst
docs/source/reference/envs.rst
test/test_rb.py
test/test_transforms.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/samplers.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

Introduces the `RandomCropTensorDict` transform, which samples random sub-trajectories from a tensordict.
We also introduce the following bc-breaking changes to the RB API:
- sampled tensordicts now have the shape of the tensordict that were used to populate the buffer. Setting back the shape is done via a temporary key `"_batch_size"`.
- As a result, the `"index"` and `"_weight"` keys are also expanded to the right to match the tensordict shape. During priority updates, the index is reduced to its original shape.
- When passing a tensordict with a multiple priority values per entry index, we use a `"reduction"` method specified by the sampler to reduce the priority to a single value. This can be `"max"` (max value of the error is indicative of the priority of the trajectory), `"min"`, …

[Feature] RandomCropTensorDict transform

---

examples/dreamer/dreamer.py

Fixes the Dreamer training loop which cannot be executed as is because the replay buffer grows too big to be contained on disk.

[BugFix] Fix dreamer training loop

---

test/test_specs.py
torchrl/data/tensor_specs.py

As mentioned in the closed PR #783 we want to update the methods `to_onehot` and `to_categorical` to support value conversion in addition to spec conversion.
This is what currently happens
```pytho
spec = torchrl.data.MultOneHotDiscreteTensorSpec([5,10])
sample = spec.rand((2,3))
sample.shape
torch.Size([2, 3, 15])
sample_np =spec.to_numpy(sample)
sample_np.shape
(2, 3, 2)
```
```python
spec = torchrl.data.MultOneHotDiscreteTensorSpec([5,10])
sample = spec.rand((2,3))
sample.shape
torch.Size([2, 3, 15])
sample_np =spec.to_numpy(sample)
sample_np.shape
(2, 3, 15)
sample_cat = spec.to_categorical(sample)
sample_cat.shape
torch.Size([2, 3, 2])
```
To keep the current behaviour (conversion of the spec), I decided that `val` will be an optional parameter. The documentation will be well written …

[Feature] Rework `to_one_hot` and `to_categorical` to take a tensor as parameter

---

torchrl/envs/gym_like.py

This PR updates the sole usage of `TensorDict.set_default` to `TensorDict.setdefault`.
cf. https://github.com/pytorch-labs/tensordict/pull/235

[Refactor] set_default -> setdefault

---

torchrl/envs/transforms/transforms.py

Propagate `*args` and `**kwargs` to TransformedEnv's `state_dict`.
Since TorchRL's environments are `nn.Module`, they contain a `state_dict`. However, the TransformedEnv 's `state_dict` class does not accept any `*args` or `*kwargs`. This PR fixes that.
Example: I implemented an [example notebook](https://github.com/fedebotu/lightning-torchrl) of PyTorch Lightning + TorchRL based on the pendulum tutorial with the `LightningModule` containing both `env` and `policy`. The following error is raised:
```bash
TypeError: state_dict() got an unexpected keyword argument 'destination'
```
which happens because of the `TransformedEnv` class. With the simple change of this PR this does not happen anymore.

[BugFix] Propagate args to TransformedEnv's `state_dict`

---

torchrl/envs/libs/vmas.py

After the specs gained a shape, some redundant extends where left in vmas, causing the specs to be potentially extended twice and leading to an error
This PR fixes that

[BugFix] Vmas expanded specs

---

torchrl/envs/common.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py

Solves bug following check skips in transforms following https://github.com/pytorch-labs/tensordict/pull/259

[BugFix] Deprecate tensordict.set check skips in transforms

---

torchrl/data/replay_buffers/storages.py

Tells users to avoid loading a memmap storage when uninitialized

[Minor] Warning when loading memmap storage on uninitialized td

---

test/test_specs.py
torchrl/data/tensor_specs.py

This PR changes the behaviour of `torch.stack` when the arguments are `TensorSpec` or `CompositeSpec` variants. It checks for equality among the specs being stacked, and if they all match, it actually performs the stack (rather than returning a lazy stacked spec).
To facilitate this, I have added `squeeze` and `unsqueeze` methods to all specs. Stacking is done by computing the new shape and then calling something like `spec.clone().unsqueeze(stack_dim).expand(new_shape)`. I added `squeeze` since you can't have `unsqueeze` without `squeeze` 😄 
Some of the tests probably need rethinking. I've made small changes to get them to pass, but there is new behaviour here which ideally would be tested for explicitly.

[Feature] Contiguous stacking of matching specs

---

test/test_specs.py
torchrl/data/tensor_specs.py

This PR makes a few changes to lazy stacked specs:
- Remove unneeded placeholder methods in `LazyStackedTensorSpec`
- Implement the `device` property for `LazyStackedTensorSpec`
- Implement `to_numpy` for the two lazy stacked spec variants.
Would be great if you could check my understanding of what's required for `to_numpy` is correct.

[Feature] Various improvements to LazyStacked specs

---

test/test_rb.py
torchrl/data/replay_buffers/__init__.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/samplers.py

Implements an `__iter__` method for replay buffer.
The goal is to be able to go through a replay buffer with a for loop.
The sampler without repetition should lead to a finite loop, and the drop-last argument should match the behaviour of dataloaders.
TODO:

[Feature, Refactor] Iterable replay buffers

---

test/test_specs.py
torchrl/data/tensor_specs.py

[Refactor] Binary spec inherits from discrete spec

---

torchrl/collectors/collectors.py

This PR addresses #846 with a warning solution.
In a few words we separate the 2 concepts:
- `frames_per_batch`: tracking the actual frames_per_batch collected
- `requested_frames_per_batch`: tracking the frames_per_batch reuqested by the user
Since in the current implementation in torchrl  the `frames_per_batch` can be more than the `requested_frames_per_batch` requested by the user.
We warn when `frames_per_batch` > `requested_frames_per_batch`

[Feature] Warn when collectors collect more frames than requested

---

test/test_collector.py
test/test_env.py
test/test_libs.py
test/test_transforms.py
torchrl/collectors/collectors.py
torchrl/envs/common.py
torchrl/envs/transforms/transforms.py
torchrl/envs/vec_env.py

There are many places where _reset is just intantieated using the batch_size, while in reality it needs to follow the done_spec.
In particular, in transforms, how do we enforce this?

[BugFix] make "_reset", "step_count", and other done_based keys follow done_spec

---

examples/discrete_sac/discrete_sac.py
examples/iql/iql_online.py
examples/td3/td3.py
test/test_rb.py
test/test_rb_distributed.py
test/test_trainer.py
test/test_transforms.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/samplers.py
torchrl/trainers/helpers/replay_buffer.py

Makes all args keyword only args in replay buffers for clarity.
Improve docstrings.
Fixes the following bugs:
- Iterating multiple times over a replay buffer leads to an empty iterator the second time and on
- include_info=False (default) leads to rubbish in the index entry, which harms training
cc @BY571 @matteobettini

[BugFix,Feature,Doc] Fix replay buffers sampling info, docstrings and iteration

---

test/test_rb.py
torchrl/collectors/collectors.py
torchrl/data/replay_buffers/replay_buffers.py

RB transforms are called even if they're empty, resulting in tensordict casting of the data which is presumably unwanted.

[BugFix] Only call replay buffer transforms when there are

---

.circleci/config.yml

Habitat now requires python 3.9

[CI] Fix python version in habitat

---

test/test_collector.py
torchrl/collectors/collectors.py

[BugFix] Fix collector reset with truncation

---

torchrl/objectives/ppo.py

Right now in order to be able to log entropy in PPO you need a non zero entropy coeff.
This allows to log entropy even if we are not incentivizing it

[Feature] PPO allow entropy logging when entropy_coeff is 0

---

torchrl/envs/libs/brax.py
torchrl/envs/libs/jax_utils.py

Fixes compatibility with Brax 0.9.0 version

[CI] Fix Brax 0.9.0

---

torchrl/objectives/ppo.py

In the ClipPPOLoss, the advantage normalisation is done after computing gain1 and before computing gain2. 
Shouldn't it be computed at the beginning, before both gain1 and gain2? This PR simply proposes to normalise the advantage at the beginning of the loss.

[BugFix] Advantage normalisation in ClipPPOLoss is done after computing gain1

---

README.md
docs/source/reference/envs.rst
torchrl/envs/utils.py

Imported the refactored `set_/interaction_type` utils and `InteractionType` enum for future use.
This is to address https://github.com/pytorch/rl/issues/1016

[Refactor] Import enum and interaction_type utils

---

torchrl/modules/tensordict_module/actors.py

The following figures are poorly rendered:
- [Actor Value Operator](https://pytorch.org/rl/reference/generated/torchrl.modules.tensordict_module.ActorValueOperator.html)
- [Actor Critic Operator](https://pytorch.org/rl/reference/generated/torchrl.modules.tensordict_module.ActorCriticOperator.html)
- [Actor Value Operator](https://pytorch.org/rl/reference/generated/torchrl.modules.tensordict_module.ActorCriticWrapper.html)
Solve the figures display problems

[Doc] fix figures display issues in documentation of actors.py

---

torchrl/objectives/value/advantages.py

This is the behaviour stated in the docstring, and the current default value of `False` makes it impossible to override `skip_existing` with the `set_skip_existing` context manager.

[BugFix] Change default of skip_existing to None

---

torchrl/objectives/value/advantages.py

The default of having differentiable advantages was motivated by the meta-rl use case, but this can be handled by the losses without harming regular usage of these classes.
cc @albertbou92

[Refactor] Make advantages non-differentiable by default (except in losses)

---

test/test_specs.py
torchrl/data/tensor_specs.py

Add indexing support to remaining specs:
Already supported by previous PR #1081 :
Note: although indexing & tests have been implemented for BoundedTensorSpec & MultiDiscreteTensorSpec, a NotImplementedError is currently set to prevent a different behavior with the other specs until https://github.com/pytorch/pytorch/issues/100080 is addressed.
Address feature request of adding indexing to specs: https://github.com/pytorch/rl/issues/1051.

[Feature] Indexing specs

---

torchrl/objectives/common.py
torchrl/objectives/ddpg.py
torchrl/objectives/iql.py
torchrl/objectives/td3.py

[BugFix] Set exploration mode to MODE in all losses by default

---

.circleci/unittest/linux_libs/scripts_gym/batch_scripts.sh
test/test_libs.py
torchrl/envs/gym_like.py

extract the info dict from the form of obs,info returned from .reset() of a gym env
extract the info dict from the form of obs,info returned from .reset() of a gym env, so that the function `info_dict_reader` would get an info of type dict {} instead of list of dicts [{}]

[BugFix] extract the info dict from a list

---

torchrl/objectives/ppo.py

When making value estimator inside the PPOLoss, value_key with the literal "state_value" was passed to the estimator, instead of the value_key passed from PPOLoss.init(). So, KeyError  will be raised if working with ActorCriticOperator or custom value_key.
See codes below:
```python
""" versions of libraries
torchrl 0.1.1
gym 0.26
torch 2.0
mujoco
"""
from torchrl.envs.libs.gym import GymEnv
from torchrl.envs.transforms import TransformedEnv,DoubleToFloat
from torchrl.modules import ActorCriticOperator, ProbabilisticActor, ValueOperator, Actor
from torchrl.modules import MLP
from torchrl.modules.distributions import TanhNormal
from torchrl.objectives.value import GAE
from torchrl.objectives.ppo import ClipPPOLoss
from torchrl.collectors import SyncDataCollector
from tensordict.nn import …
```

[BugFix] make value estimator with value_key from the PPOLoss init arg

---

torchrl/envs/transforms/transforms.py

If you use `ToTensorImage` with the unsqueeze parameter set, the observations are unsqueezed correctly. However, the observation spec isn't updated. This PR fixes that issue.
This is necessary for methods like `fake_tensordict()` where the generated tensordict depends on the observation spec. This change makes sure the observation dict is updated accordingly so methods like `fake_tensordict()` work properly.
close #1160

Fix bug where ToTensorImage unsqueeze would not update the observation spec

---

test/test_cost.py
torchrl/objectives/value/functional.py
torchrl/objectives/value/utils.py

Implement a version of for `vec_td_lambda_return_estimate` optimized for the case where gamma is a scalar.
In the case gamma is a scalar one can do the same optimization as done in #1141. Instead of constructing a big gamma tensor [B, T, T], one can split and pad the consecutive traces:
```python
reward = [r00, r01, r02, r03, r10, r11]
done = [False, False, False, True, False, False]
```
into
```python
r_transformed = [
[r00, r01, r02, r03],
[r10, r11, 0, 0]
]
```
and then apply a gamma filter to this transformed input.
- [x ] Bug fix (non-breaking change which fixes an issue)
Closes #1148 
If you are unsure about any of these, don't …

[Performance] Accelerate TD lambda return estimate 

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

Allows rewardsum to work offline
cc @BY571

[Feature] Allow sequential transforms to work offline

---

.circleci/config.yml

We moved this unittest job to GHA in a previous PR. This removes those jobs from CCI entirely.

[Nova] Remove windows Unittests from CCI

---

benchmarks/test_objectives_benchmarks.py
torchrl/objectives/value/functional.py

`_fast_vec_gae`, '_fast_td_lambda_return_estimate`, and `reward2go` need to construct a geometric series of the form `[1, g, g**2, g**3, .....]. This patch introduces a helper function such that the same logic is used by all three functions.

[Performance] Improve performance and streamline the generating of the gammalambda tensor

---

torchrl/modules/distributions/continuous.py

Close #1202.
The [doc string](https://github.com/pytorch/rl/blame/f3e9a1d03909d797c06f4db33635f38dc7f7efff/torchrl/modules/distributions/continuous.py#L307) of `TruncatedNormal` says that the default value of `tanh_loc` is `True`, however in the [code](https://github.com/pytorch/rl/blame/f3e9a1d03909d797c06f4db33635f38dc7f7efff/torchrl/modules/distributions/continuous.py#L325), it is set to `False`.
This PR fixes the issue by updating the default value in the doc string to `False`, reflecting the code.
Close #1202.

[Doc] Fix default value of `tanh_loc` in the documentation of `TruncatedNormal`.

---

test/test_cost.py
torchrl/objectives/a2c.py
torchrl/objectives/common.py
torchrl/objectives/ddpg.py
torchrl/objectives/deprecated.py
torchrl/objectives/dqn.py
torchrl/objectives/dreamer.py
torchrl/objectives/iql.py
torchrl/objectives/ppo.py
torchrl/objectives/redq.py
torchrl/objectives/reinforce.py
torchrl/objectives/sac.py
torchrl/objectives/td3.py
torchrl/objectives/value/advantages.py

We have various loss modules in RL. 
They work as
```
loss_module = LossModule(network, …)
loss_module(data)
```
These loss modules access the actual data by keys. Some keys are configurable via ctor,
https://github.com/pytorch/rl/blob/3c8197b41e351de2ebefbe2df5d5900d82e43882/torchrl/objectives/ppo.py#L125
others are hardcoded,
https://github.com/pytorch/rl/blob/714d6459e7b58f3b5601c26d612211527582327a/torchrl/objectives/ddpg.py#L139
This is refactored such that all relevant keys can be set via
```
loss_module.set_keys(sample_log_prob=“some_other_key”)
```
The same is done for the advantage modules.
```
advantage_module.set_keys(advantage="other_advantage")
```
Closes #1174 
Go over all the following points, and …

[Refactor] the usage of tensordict keys in loss modules

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

In some instances, images might already be in the 0...1 range instead of 0...255 range. This is true in Unity, for example. This PR aims to add some flexibility by only scaling the image if the dtype = torch.uint8. This behavior is consistent with [torchvision's ToTensor transform](https://pytorch.org/vision/stable/generated/torchvision.transforms.ToTensor.html).
I also updated the documentation a little bit so that way the number of channels isn't hardcoded to 3. The code seems like it doesn't rely on the dimension being 3, so I thought that making it more general shouldn't hurt. For example, grayscale images will have 1 channel rather than 3.
See description.
Go over all the following points, and put an `x` in …

[Feature, Refactor] Scale in ToTensorImage based on the dtype and new from_int parameter

---

test/test_cost.py
torchrl/objectives/a2c.py
torchrl/objectives/ddpg.py
torchrl/objectives/iql.py

Fix missing ("next", "dispatch") key of in_keys from IQL, DDPG, and A2C loss module.

[BugFix] Fix missing ("next", "observation") key in dispatch of losses

---

test/test_cost.py
torchrl/objectives/value/advantages.py

This PR allows advantages to call once and only once the value model.
If `adv.shifted` is set to `True` and if the params at `t` and `t+1` match, the value net is called only once.
In all other cases, vmap is used to batch the calls to the value net.
cc @tcbegley @apbard

[Feature] Single call to value network in advantages

---

torchrl/envs/common.py

`rand_action()` in common needs to be parametericto action key

[BugFix] Parametric `rand_action()` in `BaseEnv`

---

.circleci/config.yml

Looks like the GHA Lint job has been running fine for the past few days, we can probably remove the old CircleCI lint job at this point.

Remove old CircleCI Lint

---

test/test_rb.py
torchrl/data/replay_buffers/writers.py

Fix the bug of `RoundRobinWriter.extend(data)` with data.batch_size > twice of storage.max_size.
bug reproduction:
```python
from torchrl.data.replay_buffers import TensorDictReplayBuffer,LazyTensorStorage
import torch
td=TensorDict({"a": torch.rand(10,2)}, batch_size=[10])
rb=TensorDictReplayBuffer(storage=LazyTensorStorage(4))
rb.extend(td)   # IndexError: index 4 is out of bounds for dimension 0 with size 4
```

[BugFix] Fix the bug of `RoundRobinWriter.extend(data)` 

---

test/test_rlhf.py
torchrl/data/rlhf/dataset.py

This PR fixes a bug that arose from valid_size not being used in the constructor of TokenizedDataLoader.
The bug was not caught by the tests because it was only relevant if we used a validation split of the data. To ensure that tests catch a similar regression in the future we parametrized `split` in the test.

[BugFix] valid_size not saved as attribute

---

test/test_actors.py
test/test_tensordictmodules.py
torchrl/modules/tensordict_module/actors.py
torchrl/modules/tensordict_module/common.py

This PR adds a class method that builds an ActorValueOperator out of a base LMHeadModel-like model, it also adds a VmapModule wrapper useful to hide a batch dimension and satisfy the wrapped module

[Feature] RLHF networks

---

docs/source/reference/data.rst
docs/source/reference/modules.rst
test/test_rlhf.py
torchrl/data/__init__.py
torchrl/data/rlhf/__init__.py
torchrl/data/rlhf/utils.py
torchrl/modules/__init__.py
torchrl/modules/tensordict_module/__init__.py

See https://github.com/pytorch/rl/pull/1315 for discussion

[Feature, NOMERGE] RLHF Rollouts (reopened)

---

test/mocking_classes.py
test/test_env.py
torchrl/envs/common.py
torchrl/envs/utils.py
torchrl/envs/vec_env.py

Depends on #1347 
Fixes #1269
Draws from #1270 which should be closed after

[BugFix] Batched envs compatibility with custom keys

---

test/test_tensordictmodules.py
torchrl/data/tensor_specs.py
torchrl/modules/tensordict_module/common.py
torchrl/modules/tensordict_module/exploration.py
torchrl/modules/tensordict_module/probabilistic.py

The safe module is very unsafe ;)
Fixes #1278

[BugFix] SafeModule not safely handling specs

---

test/test_tensordictmodules.py
test/test_transforms.py
torchrl/_utils.py
torchrl/data/tensor_specs.py
torchrl/envs/transforms/rlhf.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py
torchrl/envs/vec_env.py
torchrl/modules/tensordict_module/common.py
torchrl/modules/tensordict_module/probabilistic.py
torchrl/modules/tensordict_module/rnn.py

The problem this PR solves is that we made changes in the way unravel_key(s) work but we'll revert that in tenrordict.
In the meantime, torchrl has been adapted.
Rather than reverting the PR in torchrl which will break the CI, we will do the following:
- Merge this PR in torchrl to emulate the behaviour of unravel_key in tensordict after https://github.com/pytorch-labs/tensordict/pull/473 is merged
- Merge https://github.com/pytorch-labs/tensordict/pull/473 in tensordict
- Revert imports in torchrl to tensordict instead of emulated functions
I expect this will temporarily impact negatively the benchmarks but they should recover afterwards.

[Refactor] More unravel fixes

---

.circleci/unittest/linux_examples/scripts/10_nvidia.json
.circleci/unittest/linux_examples/scripts/run_all.sh
.github/workflows/test-linux-examples.yml

[CI] Migrate examples

---

test/test_cost.py
torchrl/data/replay_buffers/storages.py
torchrl/modules/__init__.py
torchrl/objectives/common.py
torchrl/objectives/ppo.py
torchrl/objectives/value/advantages.py
tutorials/sphinx-tutorials/coding_ppo.py

[BugFix] Fix tutorials

---

.github/workflows/test-windows-optdepts-gpu.yml

Windows GPU job is working (at least from an env perspective). This is the most expensive remaining job on CCI, so this PR migrated it to GHA. Will remove the GHA job in a follow-up.

[CI] Windows GPU Tests

---

.circleci/config.yml

https://github.com/pytorch/rl/pull/1386 Moved the Windows GPU job to GHA. This PR removes the original CCI job.

[CI] Deprecate Windows GPU CCI

---

.circleci/unittest/linux_libs/scripts_envpool/setup_env.sh
.github/workflows/test-linux-envpool.yml

Migrating the Envpool CCI test to GHA. Will deprecate the CCI job in a follow-up.
Passing job link: https://github.com/pytorch/rl/actions/runs/5558582448/jobs/10153849785?pr=1283

Envpool Tests to Nova

---

.circleci/config.yml

Removes the Envpool job from CCI since it has been migrated to GHA.

Remove Envpool from CCI

---

test/test_rb.py
torchrl/data/replay_buffers/replay_buffers.py

This PR makes the ReplayBuffer pickable. Also a pickable test for the replay buffers.
Tries to solve the following issue: https://github.com/pytorch/rl/issues/1408
It is convenient to have ReplayBuffer and other classes pickable for features like distributed training, were sometimes need to be serialised.

[BugFix] Pickable buffer

---

torchrl/objectives/a2c.py
torchrl/objectives/common.py
torchrl/objectives/dqn.py
torchrl/objectives/ppo.py

[Fix] Remove loss device

---

test/test_tensordictmodules.py
torchrl/modules/tensordict_module/rnn.py

`LSTMModule` does not work when using fixed-size padded/masked segments. This is likely due to `view` not making the underlying tensors contiguous like `reshape` does.
Example script which causes an error:
```python
import torch
import tqdm
from tensordict.nn import TensorDictModule as Mod, TensorDictSequential as Seq
from torch import nn
from torchrl.collectors import SyncDataCollector
import tensordict
from torchrl.data import LazyTensorStorage, TensorDictReplayBuffer
from torchrl.envs import (
Compose,
ExplorationType,
GrayScale,
InitTracker,
ObservationNorm,
Resize,
RewardScaling,
set_exploration_type,
StepCounter,
ToTensorImage,
TransformedEnv,
)
from torchrl.envs.libs.gym import GymEnv
from torchrl.modules import ConvNet, EGreedyWrapper, LSTMModule, MLP, QValueModule
from …
```

[BugFix] Fix LSTM use with padded/masked segments

---

.github/workflows/test-macos-cpu.yml

Despite runners running MacOS 12.6, we see wheels for mujoco being fetched for MacOS 10.6 despite MacOS 11.0 wheels being available. This is due to a strange pattern used for MacOS versioning - where essentially setting SYSTEM_VERSION_COMPAT determines what is the MacOS SDK version Python believes is being used. More info at https://github.com/deepmind/mujoco/issues/1004 and https://eclecticlight.co/2020/08/13/macos-version-numbering-isnt-so-simple/.

Fix MacOS Mujoco Failure

---

docs/source/reference/envs.rst
examples/a2c/utils.py
examples/cql/utils.py
examples/ddpg/utils.py
examples/distributed/collectors/multi_nodes/ray_train.py
examples/dreamer/dreamer_utils.py
examples/ppo/utils.py
examples/sac/utils.py
examples/td3/utils.py
test/test_transforms.py
torchrl/envs/__init__.py
torchrl/envs/libs/isaacgym.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

Closes #1437 
As per the discussion below, we also introduce a ``dTypeCastTransform``.
This class is tested through Double2Float: we do this as transform tests take a long time to run and double2float tests cover all functionalities of the parent class. This is not optimal but it saves about a minute of CI runtime.

[Feature] Auto-DoubleToFloat

---

torchrl/data/tensor_specs.py

Make `CompositeSpec.unsqueeze` match the expected behavior.
```python
from torchrl.data import CompositeSpec, UnboundedContinuousTensorSpec
spec = CompositeSpec({
"a": UnboundedContinuousTensorSpec((10, 16))
}, shape=[10])
print(spec.unsqueeze(-1))
```
should give
```
CompositeSpec(
a: UnboundedContinuousTensorSpec(
shape=torch.Size([10, 1, 16]),
space=None,
device=cpu,
dtype=torch.float32,
domain=continuous), device=cpu, shape=torch.Size([10, 1]))
```

[BugFix] CompositeSpec.unsqueeze

---

.circleci/unittest/linux/scripts/run_all.sh

[mo-gymnasium](https://github.com/Farama-Foundation/MO-Gymnasium/commit/e7d1930cee84a0c22e1b0eca1087051c38de4e11) requires an [older version of mujoco](https://github.com/Farama-Foundation/MO-Gymnasium/blob/e7d1930cee84a0c22e1b0eca1087051c38de4e11/pyproject.toml#L50) than the current one which is [used by dm_control](https://github.com/deepmind/dm_control/blob/d6f9cb4e4a616d1e1d3bd8944bc89541434f1d49/setup.py#L204).
This PR fixes that by upgrading mujoco despite the strong requirement from mo-gymnasium, hoping for the best

[CI] Fix Mujoco version 

---

.github/workflows/test-windows-optdepts-gpu.yml

Moving these jobs off of the expensive and high-demand 8xlarge Windows GPU runner.

Move to More Efficient Windows Runner

---

test/mocking_classes.py
test/test_transforms.py
torchrl/envs/transforms/transforms.py

When the `_MAX_NOOPS_TRIALS` were exceeded the transform was calling a final `rand_step()` without a `step_mdp()`.
This PR add the `step_mdp()` call and 
- Improves the error message.
- Adds tests to test for the edge case behaviors of the transform.
- Fixes the documentation of the tranform.
Some things could be discussed. I left a TODO in front, which we will remove before merging.

[BugFix] Fix NoopResetEnv behavior when trials exceeded.

---

examples/multiagent/sac.py
examples/multiagent/sac.yaml
torchrl/envs/libs/vmas.py

Ths PR introduces a flag when constructing vmas environments that allows users to choose whether they want one hot or categorical actions when the actions are discrete.
Defaults to categorical for bc-comaptibility

[Feature] VMAS: choose between categorical or one-hot actions

---

torchrl/data/tensor_specs.py

`check_env_specs` fails when a composite spec is empty but the related tensordict is missing from the data structure. We tolarate this by skipping tests for missing specs.

[BugFix] Empty-spec tolerance

---

docs/source/reference/modules.rst
examples/multiagent/iql.py
examples/multiagent/qmix_vdn.py
test/test_actors.py
test/test_exploration.py
torchrl/modules/__init__.py
torchrl/modules/tensordict_module/__init__.py
torchrl/modules/tensordict_module/actors.py
torchrl/modules/tensordict_module/exploration.py

Action masks where introduced in #1421.
This PR has the job of making the components in the training pipeline use this mask.
The components that need updating are:
- q modules and actors
- e-greedy
This addresses some of the issues brought up in  #1404
cc @Kang-SungKu @1030852813 @fedebotu

[Feature] Making action masks compatible with q value modules and e-greedy

---

examples/multiagent/sac.py
torchrl/objectives/cql.py
torchrl/objectives/decision_transformer.py
torchrl/objectives/redq.py
torchrl/objectives/sac.py
torchrl/objectives/td3.py

In SAC, when the entropy target is set to "auto", it is computed using the shape of the action.
In multi-agent settings this shape included the number of agents, which should not be the case.
This PR fixes that

[BugFix] Multiagent "auto" entropy fix in SAC

---

tutorials/sphinx-tutorials/multiagent_ppo.py

Fixes #1509
This PR adds `torch.no_grad()` for the suggested rendering code in the multiagent PPO tutorial.
This will not be needed in future VMAS versions where the simulator will automatically detach incoming gradients, but still this change helps to have no erra\ors in all vmas versions.

[BugFix] Add `torch.no_grad()` for rendering in multiagent PPO tutorial

---

README.md
test/_utils_internal.py
test/test_libs.py
torchrl/collectors/collectors.py
torchrl/envs/__init__.py
torchrl/envs/batched_envs.py
torchrl/envs/common.py
torchrl/envs/libs/envpool.py
torchrl/envs/vec_envs.py

[BugFix] Fix envpool

---

.github/unittest/linux_libs/scripts_d4rl/setup_env.sh
.github/unittest/linux_libs/scripts_gym/setup_env.sh
.github/unittest/linux_libs/scripts_robohive/setup_env.sh
.github/unittest/linux_olddeps/scripts_gym_0_13/setup_env.sh
docs/source/reference/envs.rst
test/test_loggers.py
torchrl/envs/libs/gym.py
torchrl/envs/libs/habitat.py
torchrl/envs/libs/isaacgym.py
torchrl/envs/libs/pettingzoo.py
torchrl/envs/utils.py

Some CI fixes
- Windows does not find temp directory when closing it
- public mjkey is gone, now uploaded in pytorch S3

[CI] Fix CI

---

test/test_collector.py
test/test_transforms.py

Skipping tests that involve nested multiprocessing in python 3.11
cc @albanD since you implemented the fix :)

[Test] Skip tests in python 3.11

---

test/test_cost.py

depends on https://github.com/pytorch-labs/tensordict/pull/528

[Test] Test state_dict and loss modules

---

test/test_cost.py
torchrl/objectives/common.py

[BugFix] Instantiate 2 losses with different keys

---

torchrl/record/loggers/csv.py

When resuming an experiment it is nice to keep the same folder for the logger

[Feature] make csv logger `exist_ok` on logging folder

---

test/test_collector.py
torchrl/collectors/collectors.py

The collector state loading was previously not loading the collected frames.
This fixes the issue and introduces a test to check the non regression on all collectors

[BugFix] Load collector frames and iter

---

torchrl/envs/batched_envs.py

is_set is much slower in some cases, and the speed of `_reset` and `_step` is bound by the slowest worker anyway.

[Refactor] Use `wait` instead of `is_set` to get results in ParallelEnv

---

torchrl/objectives/ddpg.py

Before we were only selecting the actor input and output keys when computing the actor loss (which involves a forward critic pass).
This is limiting as the critic can have extra inputs (for example a fully observable state or a centralized state in MARL)
This PR fixes that by extending the selected keys.

[BugFix] DDPG select also critic input for actor loss

---

test/test_collector.py
test/test_env.py

OSX tests fail because the number of threads defined in sub-processes impact those from the main process.

[Test] Skip threading tests in OSX

---

test/test_env.py
torchrl/envs/common.py

Solves a bug when `run_type_checks=True` where a composite spec is queried with a non-existent `get` method.
Also adds tests for `env._run_type_checks`.
Note that this test may fail if the env is substituted with a GymEnv as GymEnv (and others) do the casting of the obs/reward/done internally during the step computation. This trades off security (ie, we can make sure that the dtype is always appropriate) to consistency between gym and torchrl (the dtype in torchrl can differ wrt gym at the expense of loosing information).

[BugFix] Fix run_type_checks

---

.github/unittest/linux/scripts/environment.yml
.github/workflows/test-linux-gpu.yml
.github/workflows/test-linux-stable-gpu.yml

Using distributed collectors with Ray results in an exception 
```
ValueError: no signature found for builtin type <class 'types.GenericAlias'>
```
(cf #1539)
This PR updates python to 3.8 for GPU tests to avoid this error.

[Versioning] Use python 3.8 for GPU tests

---

.pre-commit-config.yaml
setup.cfg
test/test_transforms.py
torchrl/envs/transforms/vip.py

Add TorchFix (https://github.com/pytorch/test-infra/tree/main/tools/torchfix) flake8 plugin.
To make it pass:
1. Update `from functorch import` to `from torch.func import vmap`.
2. Update deprecated `torch.norm` to `torch.linalg.norm`.

[Lint] Add TorchFix linter

---

examples/a2c/a2c_atari.py
examples/a2c/utils_atari.py
examples/ppo/ppo_atari.py
examples/ppo/utils_atari.py

Some minor fixes in the PPO and A2C examples, related to the end-of-lives tranform.

[BugFix] Minor fixes PPO / A2C examples

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

All transforms should be pickable to be compatible, for example, with distributed collection.

[BugFix] Make VecNorm Transform pickable

---

torchrl/data/replay_buffers/replay_buffers.py

This is a patch for #1574
It fixes the core problem highlighted in that issue but there are still points that will need attention in a future refactoring of this class as I am not sure it is compatible with all the cases it aims to support. I am happy to elucidate more about this if needed.

[BugFix] Vectorized priority update in replay buffers

---

examples/multiagent/sac.py
tutorials/sphinx-tutorials/multiagent_ppo.py

Fix the multi-agent tutorial after the recent "termianted" introduction

[Docs] Fix multi-agent tutorial

---

examples/ddpg/ddpg.py
test/test_cost.py
torchrl/objectives/ddpg.py

[Refactor] Refactor DDPG loss in standalone methods

---

torchrl/collectors/collectors.py

In collectors  `init_random_frames`  is rounded to the closest upper multiple of `frames_per_batch`.
This PR introduces a warning and docstring that make users aware of this previously silent behaviour.

[Feature] Warning for `init_random_frames` rounding in collectors

---

torchrl/data/replay_buffers/storages.py
tutorials/sphinx-tutorials/pretrained_models.py

We allow memmap storages to sit on a "device", which basically means that when accessed, the data will be sent to that device.
This is confusing and suboptimal, and will break once we have memory mapped tensors that are actually tensors (see https://github.com/pytorch/tensordict/pull/541)

[Deprecation] Deprecate ambiguous device for memmap replay buffer

---

docs/source/reference/data.rst
test/test_rb.py
torchrl/data/__init__.py
torchrl/data/replay_buffers/__init__.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/writers.py

A Writer class for composable replay buffers that keeps the top elements based on some ranking key.

[Feature] Max Value Writer

---

torchrl/_extension.py
torchrl/data/replay_buffers/samplers.py
torchrl/modules/distributions/continuous.py

Allows to import torchrl when _torchrl.so isn't available.
Wdyt @matteobettini ?

[BugFix] Gracefully handle C++ import error in TorchRL

---

examples/cql/utils.py
examples/ddpg/ddpg.py
examples/ddpg/utils.py
examples/decision_transformer/dt_config.yaml
examples/decision_transformer/odt_config.yaml
examples/decision_transformer/utils.py
examples/discrete_sac/discrete_sac.py
examples/iql/iql_online.py
examples/sac/sac.py
examples/sac/utils.py
examples/td3/td3.py

Passing the same scratch directory to a replay buffer during multiple runs will write data at the exact same location, which will make the run interfere and eventually fail.

[BugFix] Avoid overlapping temporary dirs during training

---

test/test_collector.py
torchrl/collectors/collectors.py

Ensures that all private keys (even nested ones) are excluded from collector output

[Feature] Exclude all private keys in collectors

---

test/test_utils.py
torchrl/_utils.py

Makes `implement_for` lazy: the import that checks the package version will only occur the first time the function is run.
This allows us to skip the gym imports during torchrl import, and speeds up the lib import itself.
@matteobettini

[Feature] Lazy imports for implement_for during torchrl import

---

examples/cql/cql_online.py
examples/ddpg/ddpg.py
examples/discrete_sac/discrete_sac.py
examples/dqn/dqn.py
examples/dreamer/dreamer.py
examples/iql/iql_online.py
examples/redq/redq.py
examples/sac/sac.py
examples/td3/td3.py
torchrl/data/replay_buffers/storages.py

We used to put the MemmapTensors on the training device, but the swap to MemoryMappedTensor will break this.
Instead of calling `tensordict.contiguous()` (which could be made more efficient) we call `as_tensor`. This will raise a warning after we introduce MemoryMappedTensor, and a follow-up PR will need to change that logic.

[Refactor] Put all buffers on CPU in examples

---

torchrl/data/tensor_specs.py

Deprecation warning incorrectly suggests that `maximum` will be deprecated in favor of `low`, instead of `high`.
Closes #1654

[BugFix] Fix incorrect deprecation warning

---

test/test_rb.py
torchrl/data/replay_buffers/writers.py

When TensorDictMaxValueWriter receives a batch of data via `extend()` but any sample if better than what the buffer contains, raises *** ValueError: not enough values to unpack (expected 2, got 0) when trying to obtain the insertion info `keys, values = zip(*data_to_replace.items())` raises . This PR fixes this use case.

[Bug] TensorDictMaxValueWriter raises error when no sample in a batch is accepted

---

torchrl/objectives/value/advantages.py

3 fixes
Fix twice an initialisation of terminated using tensordict.get(done).
Fix a call of function with parameter "terminated=done"
Most likely a copy pasting mistake during the terminated/done refactor

[BugFix] Fix "done" instead of "terminated" mistakes

---

.github/unittest/linux_examples/scripts/run_test.sh
examples/dreamer/config.yaml
examples/dreamer/dreamer.py

A device argument is missing in dreamer's example and tests, which makes the code not runnable on machines without gpu.

[Minor] Update dreamer example tests

---

test/test_libs.py
torchrl/envs/libs/vmas.py

This PR allows VMAS to use the MARL api with grouping.
Users will be able to provide a group_map to VMAS.
By default this will try to group agents named `name_n` into a group named "name".
In case at least one agent does not follow this convention and not group map is specified, VMAS will try to group all agents under the "agent" group

[Feature] Introduce grouping in VMAS

---

torchrl/envs/utils.py

The assertion checked for data0 == data1, but the error message prints out that data0 shape is not data0 shape.  Very clear error, simple fix.
- [x ] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)

[BugFix] assertion error message, envs/util.py

---

test/test_rb.py
torchrl/data/replay_buffers/writers.py

When calling extend, a new tensor containing the new index values is created but its device was not specified, which caused problem when the data was in GPU. Now it is created in whatever device the data is.

[BugFix] MaxValueWriter cuda compatibility

---

docs/requirements.txt
docs/source/conf.py
tutorials/sphinx-tutorials/dqn_with_rnn.py
tutorials/sphinx-tutorials/pendulum.py

Copies the corrected tutorials from https://github.com/pytorch/tutorials/pull/2653 and https://github.com/pytorch/tutorials/pull/2643

[Doc] Update pendulum and rnn tutos

---

test/test_exploration.py
torchrl/modules/tensordict_module/exploration.py

we should make sure the params of exploration-wrapper is float, or the params decay maybe abnormal.
If the user passes an int into the wrapper (e.g. "1" instead of "1.0", like stupid me), the params will always be `0` and don't change throughout the `step` is called:
```python
policy = TensorDictModule(
module=torch.nn.Linear(4, 4, bias=False),
in_keys="observation",
out_keys="action",
)
p = OrnsteinUhlenbeckProcessWrapper(
policy,
eps_init=1,
)
for i in range(10):
p.step()
print(p.eps.item())
```
result is 
```
0
0
0
0
0
0
0
0
0
0
```
if we pass a float, the function of wrapper is normal:
```python
policy = TensorDictModule(
module=torch.nn.Linear(4, 4, bias=False),
in_keys="observation",
out_keys="action",
)
p = OrnsteinUhlenbeckProcessWrapper(
policy,
eps_init=1.0,
)
for i in …
```

[BugFix] make sure the params of exploration-wrapper is float

---

torchrl/envs/transforms/gym_transforms.py

EndOfLifeTransform should check if the current number of lives in the tensordict is higher that the number of lives after the step (meaning on has been lost). However, the sign is the opposite. This PR changes that.

[Fix] EndOfLifeTransform fix in end of life detection

---

.github/workflows/benchmarks.yml
.github/workflows/benchmarks_pr.yml
benchmarks/test_collectors_benchmark.py
benchmarks/test_objectives_benchmarks.py

[CI] Fix benchmark on gpu

---

torchrl/objectives/utils.py

[BugFix] Fix hold_out_net

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

In the `RewardSum` transform, reset keys where checked to be valid only when not directly provided by the user.
https://github.com/pytorch/rl/blob/07fcfb1cff2e897fff406ef45c2e5ff7ea57a14f/torchrl/envs/transforms/transforms.py#L4773
This led to silent errors when the users provides reset keys manually but there are not as many as the in_keys gathered automatically from the reward_spec.
This PR runs the key check in both the case of user provided or autoimatically gathered reset keys, making the function more resilient.

[BugFix] `RewardSum` key check

---

docs/source/reference/data.rst
test/test_rb.py
torchrl/data/replay_buffers/storages.py
torchrl/data/replay_buffers/writers.py

Allows a replay buffer with memmap storage to be shared across processes.
Example:
```python
import pickle
from torchrl.data import TensorDictReplayBuffer, LazyMemmapStorage
import torch
from torch import multiprocessing as mp
def worker(rb):
td = TensorDict({"a": torch.ones(10)}, [10])
rb.extend(td)
if __name__ == "__main__":
rb = TensorDictReplayBuffer(storage=LazyMemmapStorage(21))
td = TensorDict({"a": torch.zeros(10)}, [10])
rb.extend(td)
proc = mp.Process(target=worker, args=(rb,))
proc.start()
proc.join()
assert len(rb) == 20
```
TODO:

[Feature] Shared replay buffers

---

torchrl/objectives/value/advantages.py

_call_actor_net method from advantages.py raises the following error when the actor network expects multiple inputs
> *** TypeError: select() received an invalid combination of arguments - got (list, inplace=bool, strict=bool), but expected one of:
>  * (name dim, int index)
>  * (int dim, int index)
This PR fixes that

[BugFix] _call_actor_net does not handle multiple inputs

---

test/test_tensordictmodules.py
torchrl/objectives/value/utils.py

Fixes #1735 
The issue was that a newly created tensor was being populated with a non-leaf tensor during a call to torch.vmap, making vmap complain about it.
The solution is to rely on `torch.masked_scatter` instead of `__setitem__` (it, `tensor[mask] = smth`).

[BugFix] Fix RNNs trajectory split in VMAP calls

---

torchrl/data/rlhf/utils.py

Removing what looks like some leftover debug code, happens after a non-conditional return statement so cannot be executed.
Purely a cleanup, observed when reading through the code. 
- [ x] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)

[Minor] Remove dead code in RolloutFromModel

---

examples/rlhf/train.py
examples/rlhf/train_reward.py
examples/rlhf/utils.py

Small amount of bit rot on the RLHF example.
- Correct passing of configuration in train transformer and reward steps
- Fix typo on prompt logger
- Update log_scalar to match class spec.
There was one larger issue which I didn't address, which was that tensordictmodule wasn't playing well with dynamo, due to the optimizedmodule not forwarding getattr calls to the underlying module: I didn't get round to verifying that was fixed in nightlies (though I think it might be), but I did think about about updating the train/train_reward configs to default compile to be off as it will fail in the stable release version with `TypeError: _forward_unimplemented() got an unexpected keyword argument 'input_ids'` or similar. Its easy enough to disable compile in config or on command line, but it might …

[Minor] Fix runnability of RLHF example in examples/rlhf

---

docs/source/reference/data.rst
test/test_rb.py
test/test_tensordictmodules.py
torchrl/data/__init__.py
torchrl/data/replay_buffers/__init__.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/samplers.py
torchrl/objectives/td3.py

In this PR I propose a new sampler that samples slices of data in a storage.
Let RB be a replay buffer of capacity `M` (for simplicity the replay buffer is full). 
We have `N` trajectories stored in this buffer, with length `T_{min} < T_i < T_{max}` for all `T_i for i in 1:N`.
We want to sample batches of data of some arbitrary length such that the batch size `B = S * U` (potentially with a tensordict of shape `[S, U]` or `[S * U]`, TBD) where `S` is the number of slices and `U` a fixed sub-trajectory length.
Assume `U > T_{min}`.
The slices sampled from the RB can start anywhere from `t_start=0` to `t_start = T_i - U` and end at `t_start + U`.
## Usage
In many cases, users want to sample sub-trajectories out of complete trajectories. Those sub-trajectories should generally not start at …

[Feature] SliceSampler

---

benchmarks/test_replaybuffer_benchmark.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/samplers.py

cc @harnvo
I changed the names so that we can have a fresh look at the benchmarks on the benchmark tool. 
I will try to remove the old traces that are wrong (need to look at how I can modify the xml files on gh-pages)

[Benchmark] Fix RB benchmarks

---

torchrl/data/replay_buffers/samplers.py

[BugFix] Fix slice sampler

---

docs/source/reference/envs.rst
test/test_transforms.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

Transform to partially burn-in data sequences. 
This transform is useful to obtain up-to-date recurrent states when they are not available. It burns-in a number of steps along the time dimension from sampled sequential data slices and returns the remaining data sequence with the burnt in data in its initial time step.
As an example, this transform can be used with off-policy RL algorithms when the models are RNN's.

[Feature] BurnInTransform

---

test/test_rb.py
torchrl/data/replay_buffers/samplers.py

Fixed a bug reported [here](https://github.com/pytorch/rl/pull/1762#issuecomment-1880177757) where it was pointed that the last item of a trajectory was always missed by SliceSampler.
This was due to sampling the start item of the trajectory according to `floor((traj_len - sample_len) * rand()) + start_idx` instead of `floor((traj_len - sample_len + 1) * rand()) + start_idx`. To see why the second is right and first wrong, one can thing of a trajectory of `traj_len=2`, `sample_len=1` and `start_idx=0`. It is clear that the first will only sample a start index of `0` and never `1`.
cc @nicklashansen @dasGringuen

[BugFix] Fix sampling of last item in SliceSampler

---

torchrl/envs/batched_envs.py

[BugFix] Fix documentation of threads for batched envs.

---

torchrl/data/datasets/openx.py
torchrl/data/replay_buffers/samplers.py

Solves a bug where `from_dict` was allocating the max batch-size to the info tensordict in the SamplerEnsemble.
cc @nicklashansen

[BugFix] Ensure that infos and samples have the same batch-size in SamplerEnsemble

---

torchrl/data/replay_buffers/samplers.py
torchrl/data/replay_buffers/writers.py

This PR replaces the numpy indices returned by data writers with tensor indices in the correspondent device.
It also makes sure that PrioritizedSampler moves received indices to cpu to avoid segmentation fault.

[BugFix] Writers extend() method should always return indices in data.device 

---

docs/source/reference/envs.rst
test/test_transforms.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

This PR adds a new Transform called SignTransform. As explained in the docs,
```
This transform reads the tensors in ``in_keys`` and ``in_keys_inv``, computes the
signs of their elements and writes the resulting sign tensors to ``out_keys`` and
``out_keys_inv`` respectively.
```

[Feature] SignTransform

---

test/test_rb.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/utils.py
torchrl/data/replay_buffers/writers.py

The current version of the MaxValueWriter only allows to reduce the `rank_key` by summing along the last dimension.
In a similar fashion to the PrioritizedSampler, this PR introduces a `reduce` parameter so that users have more control about how the `rank_key` will be handled when it has more that 1 dimension. Options are: max, min, mean, median and sum.

[Feature] Extend MaxValueWriter with reduce parameter for the rank_key

---

torchrl/envs/gym_like.py

In this PR, I propose a change in the `_step` from `GymLikeEnv` where we validate the value provided to the tensordict once and for all if possible. The behaviour is as follows:
At first, `validated` is `None` by default. `None` means that we need to validate whether or not the data must be validated by the tensordict.
Then, we check if building the tensordict a second time changes the identity of its leaves. If so, it means that some casting has occurred. If not, we are confident that the value passed to the TD are the same as originally and no check should be executed.
We then save this `validated` attribute and never check it again.
On my old macbook, `TensorDict.__init__` was raking 5th in the list of the most expensive functions with 15% of runtime associated, i now ranks way below …

[Performance] faster gym-like class

---

test/mocking_classes.py
test/test_shared.py
test/test_transforms.py
torchrl/data/datasets/d4rl.py
torchrl/data/tensor_specs.py
torchrl/envs/batched_envs.py
torchrl/envs/common.py
torchrl/envs/transforms/transforms.py

Select now returns a locked TD if the original TD was memmaped or shared. We now use empty which does not have that feature.

[BugFix] Remove select() in favor of empty()

---

test/mocking_classes.py
test/test_transforms.py
torchrl/envs/common.py
torchrl/envs/transforms/transforms.py

Fixes #1806
The context is:
Some enviornments can be done immediately after a reset (e.g., some agents can be still dead after a reset in multiagent settings).
TorchRL by default does not allow this and will throw an error.
If you, however, would like to allow your environment to be done after reset, you can set `allow_done_after_reset` during construction of your environment.
`PettingZoo` and `VMAS` need this.
However, in #1806, it is shown that when a transform is added to the environment, this attribute changes.
In this PR, we fix this, by making the attribute of transformend enviornments mirror the one of the base environment.

[BugFix] Make `TransformedEnv` mirror `allow_done_after_reset` property of base env

---

test/test_env.py
torchrl/envs/batched_envs.py
torchrl/envs/gym_like.py
torchrl/envs/libs/gym.py

Improves the info_dict reader API for gym-like envs:
- `set_info_dict_reader()` now works with no args, in which case the default info-dict reader is used. We also populate it using a dummy rollout. 
- The above method could break when the env is passed to a parallel env since some gym envs do not return infos at reset. To palliate this, one can now use `GymLikeEnv.auto_register_info_dict`. The docstring should be enough to understand when this is used. We also link it in the ParallelEnv doc.
Feel free to read the ParallelEnv doc from this PR which I think is the easiest way of getting started with the feature.
Tagging a few folks who may be interested for context and feedback:
@skandermoalla @duburcqa @felix-basiliskroko @vikashplus @ShaneFlandermeyer @albertbou92 @BY571

[Feature] Improve info_dict reader

---

torchrl/envs/libs/pettingzoo.py

This change is a PettingZoo change which is BC-compatible to all the pettingzoo versions we already supported.
In addition, in case pettingzoo cannot load all modules, it leverages the new PettingZoo 1.24.3 functionalities to load only group of environments
This ameliorates the issue https://github.com/Farama-Foundation/PettingZoo/issues/1072
And fixes https://github.com/facebookresearch/BenchMARL/issues/41
cc @elliottower

[Feature] More flexibility in loading PettingZoo

---

torchrl/envs/transforms/transforms.py

Fixes a bug reported in https://github.com/pytorch/rl/issues/1198#issuecomment-1896617332

[BugFix] Fix device of container generated values in transforms

---

pyproject.toml

Removes irrelevant (and invalid) fields in the `pyproject.toml` file (`excludes`, `target-version` and `first_party_detection`).
When installing this package from the source, I get the following error:
```
ERROR Failed to validate `build-system` in pyproject.toml: Unknown properties: excludes, target-version, first_party_detection
```
From my understanding, the following three tags are not meant to be under the `build-system` category.

pyproject.toml: remove unknown properties

---

.github/unittest/linux_olddeps/scripts_gym_0_13/environment.yml
test/test_loggers.py
torchrl/objectives/a2c.py
torchrl/objectives/ppo.py
torchrl/objectives/redq.py
torchrl/record/loggers/csv.py
torchrl/record/loggers/tensorboard.py
torchrl/record/loggers/wandb.py
torchrl/record/recorder.py

closes #1400
cc @lucasbasquerotto @ADebor
In a previous PR I also [refined a lot the docstrings](https://github.com/pytorch/rl/pull/1787) of all the envs we have so all in all the situation should be much better now!
I added a bunch of options in CSVLogger to save videos in a more flexible way. 
The doc will be available here https://docs-preview.pytorch.org/pytorch/rl/1829/reference/generated/torchrl.record.VideoRecorder.html#torchrl.record.VideoRecorder

[Doc, Feature] Doc improvements for video recording and CSV video formats

---

torchrl/__init__.py

Suppresses warnings about lazy_legacy not being defined.
We'll revert it later to ``False`` in #1832

[BugFix] Temporarily set lazy legacy to True

---

test/test_collector.py
test/test_env.py
torchrl/__init__.py
torchrl/_utils.py
torchrl/collectors/collectors.py
torchrl/envs/batched_envs.py
torchrl/envs/libs/gym.py

Closes #1847 
To test:
```python
import torch
from torchrl.envs import ParallelEnv, GymEnv
if __name__ == "__main__":
print(torch.get_num_threads()) # 8
env3 = ParallelEnv(3, lambda: GymEnv("Pendulum-v1"))
env3.rollout(2) 
print(torch.get_num_threads()) # 5
env2 = ParallelEnv(2, lambda: GymEnv("Pendulum-v1"))
env2.rollout(2)
print(torch.get_num_threads()) # 3
env2.close()
print(torch.get_num_threads()) # 5
env3.close()
print(torch.get_num_threads()) # 8
```
cc @skandermoalla

[Feature, BugFix] Better thread control in penv and collectors

---

test/test_transforms.py
torchrl/data/replay_buffers/storages.py

Bug fixes in tensordict (namely is_empty and state_dict issues) caused tests to fail in torchrl.
Since these tests were relying on brittle APIs we simply upgrade to the consolidated tensordict features.

[BugFix] Fix load_state_dict and is_empty td bugfix impact

---

torchrl/modules/tensordict_module/exploration.py

Improves egreedy device when specs have no device

[BugFix] better device consistency in EGreedy

---

test/test_utils.py
torchrl/_utils.py
torchrl/envs/utils.py

Sets the default seed of check_env_specs to None (no seed) and set it only temporarily for Torch. For the env, we can't reset the RNG state unfortunately.

[BugFix] check_env_specs seeding logic

---

torchrl/data/replay_buffers/samplers.py

In certain cases, because of the wrong parentheses placement, the SliceSampler would produce indices that are outside the acceptable range of the storage.
`close #1873 `

[BugFix] Fix a bug in SliceSampler, indexes outside sampler lengths were produced

---

test/test_env.py
torchrl/envs/batched_envs.py

[BugFix] Fix _reset data passing in parallel env

---

torchrl/data/replay_buffers/samplers.py

"terminated" tensor was not properly populated in SliceSampler.
Addresses this bug report: https://github.com/pytorch/rl/issues/1877

[BugFix] Use traj_terminated in SliceSampler

---

docs/source/reference/data.rst
test/test_rb.py
torchrl/data/replay_buffers/__init__.py
torchrl/data/replay_buffers/samplers.py
torchrl/modules/tensordict_module/exploration.py

Add PrioritizedSliceSampler which inherits from PrioritizedSampler and SliceSampler.
Contrary to PrioritizedSampler which samples steps with a priority weight for each, PrioritizedSliceSampler samples slices with a priority weight for each. Implementation-wise, it only samples the start index of each slice, while discarding the indices at the end of each episode since they can't form long enough slices.
Contrary to SliceSampler which first samples trajectories, then randomly samples slices inside each trajectory, PrioritizedSliceSampler directly samples slices. It is easier to implement that way, but as a consequence PrioritizedSliceSampler more often samples slices from longer trajectories than shorter trajectories when priority weights are uniform. Nevertheless, since the priority …

[Feature] Add PrioritizedSliceSampler

---

torchrl/collectors/collectors.py
torchrl/envs/batched_envs.py

[BugFix] Adaptable non-blocking for mps and non cuda device in batched-envs

---

examples/a2c/utils_atari.py
examples/dqn/utils_atari.py
examples/impala/utils.py
examples/ppo/utils_atari.py

In practice does not change the value for Atari envs because there are no rewards smaller than abs(1.0), but the original implementations of the examples compute the sign of the rewards instead of clipping it.  Would close this issue: https://github.com/pytorch/rl/issues/1777

[Feature] Replace RewardClipping with SignTransform in Atari examples

---

torchrl/objectives/utils.py

[BugFix] Use setdefault in _cache_values

---

torchrl/envs/transforms/transforms.py

[BugFix] Non exclusive terminated and truncated

---

test/test_env.py
torchrl/envs/batched_envs.py

Also adds a test to make sure SerialEnv gradients work ok
cc @AndreaTirinzoni

[BugFix] Make sure ParallelEnv does not overflow mem when policy requires grad

---

torchrl/envs/transforms/transforms.py

[Feature] Allow non-sorted keys in CatFrames

---

test/test_cost.py
torchrl/objectives/ppo.py

[BugFix] Fix KLPENPPOLoss KL computation

---

torchrl/data/__init__.py
torchrl/envs/libs/openml.py
torchrl/envs/transforms/r3m.py
torchrl/envs/transforms/transforms.py
torchrl/envs/transforms/vip.py
torchrl/record/recorder.py

[BugFix, Performance] Fewer imports at root

---

test/test_rb.py
torchrl/data/replay_buffers/storages.py
torchrl/data/replay_buffers/writers.py

[BugFix] Fix replay buffer extension with lists

---

torchrl/envs/common.py

Closes https://github.com/pytorch/rl/issues/1925

[Minor] Add env.shape attribute

---

torchrl/objectives/value/advantages.py

[BugFix] Vmap randomness for value estimator 

---

benchmarks/ecosystem/gym_env_throughput.py
benchmarks/test_collectors_benchmark.py
examples/distributed/collectors/multi_nodes/delayed_dist.py
examples/distributed/collectors/multi_nodes/delayed_rpc.py
examples/distributed/collectors/multi_nodes/generic.py
examples/distributed/collectors/multi_nodes/rpc.py
examples/distributed/collectors/multi_nodes/sync.py
examples/distributed/collectors/single_machine/generic.py
examples/distributed/collectors/single_machine/rpc.py
examples/distributed/collectors/single_machine/sync.py
test/test_collector.py
test/test_distributed.py
test/test_env.py
test/test_libs.py
torchrl/collectors/__init__.py
torchrl/collectors/collectors.py
torchrl/collectors/distributed/utils.py
torchrl/envs/common.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py
tutorials/sphinx-tutorials/getting-started-3.py
tutorials/sphinx-tutorials/rb_tutorial.py

From the docstrings:
```python
>>> from torch import nn
>>> env = GymEnv("CartPole-v1", categorical_action_encoding=True)
>>> class ArgMaxModule(nn.Module):
...     def forward(self, values):
...         return values.argmax(-1)
>>> n_obs = env.observation_spec["observation"].shape[-1]
>>> n_act = env.action_spec.n
>>> # A deterministic policy
>>> policy = nn.Sequential(
...     nn.Linear(n_obs, n_act),
...     ArgMaxModule())
>>> env.rollout(max_steps=10, policy=policy)
TensorDict(
fields={
action: Tensor(shape=torch.Size([10]), device=cpu, dtype=torch.int64, is_shared=False),
done: Tensor(shape=torch.Size([10, 1]), device=cpu, dtype=torch.bool, is_shared=False),
next: TensorDict(
fields={
done: Tensor(shape=torch.Size([10, 1]), device=cpu, dtype=torch.bool, is_shared=False), …
```

[Feature] Execute rollouts with regular nn.Module instances

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

Currently offline catframes is broken
- it does not return cat but stacks
- it ignores reset signals
I'm trying to fix this
Example code:
```python
from torchrl.envs import GymEnv, TransformedEnv, CatFrames, SerialEnv
env = SerialEnv(3, lambda: TransformedEnv(GymEnv("CartPole-v1"), CatFrames(dim=-1, N=4, in_keys=["observation"], out_keys=["observation_cat"], padding="constant")))
r = env.rollout(100, break_when_any_done=False)
c = CatFrames(dim=-1, N=4, in_keys=["observation", ("next", "observation")], out_keys=["observation_cat2", ("next", "observation_cat2")], padding="constant")
r2 = c(r)
assert (r2["observation_cat2"] == r2["observation_cat"]).all()
assert (r2["next", "observation_cat2"] == r2["next", "observation_cat"]).all()
```
cc @btx0424 @BY571

[BugFix] Fix offline CatFrames

---

.github/workflows/build-wheels-m1.yml
test/smoke_test.py
torchrl/_extension.py

There is an issue with import importlib. [This cause the warning](https://github.com/pytorch/rl/blob/main/torchrl/_extension.py#L24) "Failed to import torchrl C++ binaries"  #1888 
Tested locally - see screenshots

[BugFix] Fixed import for importlib

---

.github/workflows/build-wheels-m1.yml

Use the main branch for the M1 build wheels workflow.
All workflows should use the main branch, except for debugging purposes.

[Minor] Use the main branch for the M1 build wheels

---

torchrl/record/recorder.py

Fixes the formatting for the VideoRecorder docstring example, which is [currently broken](https://pytorch.org/rl/reference/generated/torchrl.record.VideoRecorder.html).

[BugFix] fix formatting for VideoRecorder docstring

---

.github/unittest/linux/scripts/run_all.sh
.github/unittest/linux_distributed/scripts/install.sh
.github/unittest/linux_examples/scripts/run_all.sh
.github/unittest/linux_libs/scripts_ataridqn/install.sh
.github/unittest/linux_libs/scripts_brax/install.sh
.github/unittest/linux_libs/scripts_d4rl/install.sh
.github/unittest/linux_libs/scripts_envpool/install.sh
.github/unittest/linux_libs/scripts_gen-dgrl/install.sh
.github/unittest/linux_libs/scripts_habitat/install.sh
.github/unittest/linux_libs/scripts_jumanji/install.sh
.github/unittest/linux_libs/scripts_minari/install.sh
.github/unittest/linux_libs/scripts_openx/install.sh
.github/unittest/linux_libs/scripts_pettingzoo/install.sh
.github/unittest/linux_libs/scripts_rlhf/install.sh
.github/unittest/linux_libs/scripts_robohive/install_and_run_test.sh
.github/unittest/linux_libs/scripts_roboset/install.sh
.github/unittest/linux_libs/scripts_sklearn/install.sh
.github/unittest/linux_libs/scripts_smacv2/install.sh
.github/unittest/linux_libs/scripts_vd4rl/install.sh
.github/unittest/linux_libs/scripts_vmas/install.sh
.github/unittest/linux_optdeps/scripts/install.sh
.github/unittest/windows_optdepts/scripts/install.sh
.github/workflows/benchmarks.yml
.github/workflows/benchmarks_pr.yml
.github/workflows/docs.yml
.github/workflows/nightly_build.yml

Related issues: 
- https://github.com/aws-neuron/aws-neuron-sdk/issues/841
- https://github.com/sympy/sympy/issues/26273
- https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15103

[CI] Fixes sympy error by fixing mpmath version

---

test/test_rb.py
torchrl/data/replay_buffers/samplers.py

Solves #1969  as discussed in the issue
To test the feature:
```python
from torchrl.data import ReplayBuffer, SliceSampler, LazyTensorStorage
import torch
trajectory0 = torch.tensor([3, 3, 0, 1, 1, 1, 2, 2, 2, 3])
trajectory1 = torch.arange(10)
trajectory = torch.stack([trajectory0, trajectory1], -1)
td = TensorDict({"trajectory": trajectory, "steps": torch.arange(10).view(10, 1).expand(10, 2)}, [10, 2]).transpose(-2, -1).clone()
print(td)
rb = ReplayBuffer(
sampler=SliceSampler(traj_key="trajectory", num_slices=2),
storage=LazyTensorStorage(20, ndim=2),
batch_size=6
)
rb.extend(td)
s = rb.sample()
print(s["steps"])
print(s["trajectory"])
```
Which can give
```
tensor([9, 0, 1, 6, 7, 8])
tensor([3, 3, 3, 2, 2, 2])
```
cc @nicklashansen @dasGringuen …

[BugFix] Fix strict-length for spanning trajectories

---

test/test_cost.py
test/test_env.py
torchrl/data/tensor_specs.py
torchrl/envs/common.py
torchrl/envs/gym_like.py
torchrl/envs/libs/gym.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py

Other improvements to explore:
- usage of `to` in env._step may be unnecessary if no mapping is needed
- step_mdp takes 11% of runtime and _set called within another 8% (2.2% own time). Improving on `_set` could speed things up drastically
- tensordict.get takes another 5.1%
cc @teopir

[Performance] Faster DMC

---

test/test_cost.py
torchrl/objectives/a2c.py
torchrl/objectives/cql.py
torchrl/objectives/ddpg.py
torchrl/objectives/deprecated.py
torchrl/objectives/dreamer.py
torchrl/objectives/iql.py
torchrl/objectives/redq.py
torchrl/objectives/reinforce.py
torchrl/objectives/sac.py
torchrl/objectives/td3.py
torchrl/objectives/value/advantages.py

This PR proposes to set `strict=False` for the `tensordict.select()` calls in the objective classes.
The logic behind this is that in some situations the Actors and Value networks should still be able to run through the losses without some of the in_keys. 
Examples are: 
1. RNN without the `recurrent_state` key can still be called when the `is_init` is True.
2. Transformer networks may need a mask during inference but not during training.
3. More generally, users could make custom TensorDict modules that have optional parameters.  …

[BugFix] Set strict=False in tensordict.select() calls for objective classes

---

docs/source/reference/data.rst
test/test_cost.py
test/test_postprocs.py
test/test_transforms.py
torchrl/data/postprocs/postprocs.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/rb_transforms.py
torchrl/envs/transforms/transforms.py

Test script
```python
import torch
from torchrl.envs import GymEnv, TransformedEnv, StepCounter, SerialEnv
from torchrl.envs.transforms.rb_transforms import MultiStepTransform
from tensordict.utils import assert_allclose_td
env = TransformedEnv(GymEnv("CartPole-v1"), StepCounter())
env.set_seed(0)
torch.manual_seed(0)
t = MultiStepTransform(3, 0.98)
outs_2 = []
td = env.reset()
for _ in range(1):
rollout = env.rollout(250, auto_reset=False, tensordict=td, break_when_any_done=False)
out = t._inv_call(rollout)
td = rollout[..., -1]
outs_2.append(out)
outs_2 = torch.cat(outs_2, -1).split([47, 50, 50, 50, 50], -1)
t = MultiStepTransform(3, 0.98)
env.set_seed(0)
torch.manual_seed(0)
outs = []
td = env.reset()
for i in range(5):
rollout = env.rollout(50, auto_reset=False, tensordict=td, …
```

[Feature] RB MultiStep transform

---

torchrl/objectives/ppo.py
torchrl/objectives/utils.py

[BugFix] Fix clip_fraction in PO losses

---

test/test_rb.py
torchrl/data/replay_buffers/samplers.py
torchrl/data/replay_buffers/storages.py

TODO:
- Make sure that this is working OK with shared buffers (extend on one worker won't erase the buffer on the other!)
cc @ahmed-touati @Cadene

[Performance] Faster slice sampler

---

test/test_rb.py
torchrl/data/replay_buffers/samplers.py

[BugFix] Fix strict_length=True in SliceSampler

---

torchrl/collectors/collectors.py
torchrl/data/replay_buffers/storages.py
torchrl/envs/batched_envs.py
torchrl/envs/common.py
torchrl/envs/gym_like.py
torchrl/envs/libs/gym.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py

@skandermoalla @dennismalmgren @albanD  @alexander-soare
To test this (replace mps with cuda if available):
```python
import torch
from tensordict.nn import TensorDictModule
from torchrl.envs import GymEnv
from torchrl.modules import MLP
import torch.utils.benchmark
if __name__ == "__main__":
env = GymEnv("Pendulum-v1", device="cpu")
policy = TensorDictModule(
MLP(
env.observation_spec["observation"].shape[-1],
env.action_spec.shape[-1],
num_cells=(64, 64),
device="mps",
),
in_keys=["observation"], out_keys=["action"])
print(torch.utils.benchmark.Timer("env.rollout(1000, policy=policy, auto_cast_to_device=True, break_when_any_done=False)", globals=globals()).adaptive_autorange())
torch.manual_seed(0)
env.set_seed(0)
rollout = env.rollout(1000, policy=policy, auto_cast_to_device=True, …
```

[BugFix] Robust sync for non_blocking=True

---

docs/source/reference/envs.rst
test/test_transforms.py
torchrl/data/tensor_specs.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

Solves https://stackoverflow.com/questions/78198313/handling-batch-size-in-a-torchrl-environment/78199390#78199390
TODO:

[Feature] BatchSizeTransform

---

test/test_rb.py
torchrl/data/replay_buffers/samplers.py

[BugFix] Fix slicesampler terminated/truncated signaling

---

test/test_transforms.py
torchrl/data/tensor_specs.py
torchrl/envs/transforms/transforms.py

Blocking merge until #2034 is incorporated

[Feature] Fine grained DeviceCastTransform

---

torchrl/envs/transforms/transforms.py

Changes the arguments for the `_reset` function in the `MaskedEnv` example in the documentation for the `ActionMask` transform, which solves the example throwing an error.
This change is required because the current example in the documentation throws `TypeError: MaskedEnv._reset() got an unexpected keyword argument 'tensordict'` when run. The new code fixes this issue. 
Bug Report: https://github.com/pytorch/rl/issues/2059
`close #2059`

[Documentation] Correct MaskedEnv Example in ActionMask Transform Documentation

---

.github/unittest/linux_libs/scripts_pettingzoo/environment.yml
.github/unittest/linux_libs/scripts_smacv2/environment.yml
.github/unittest/linux_libs/scripts_vmas/environment.yml
test/test_libs.py
torchrl/envs/libs/pettingzoo.py

Here I have a small set of modifications to PettingZoo wrapper that have been requested by users.
The modifications are:
- possibility to override if an environment is done whaen any or all agents are done
- setting the done flags for dead agents properly
cc @renos

[Features] PettingZoo possibility to choose reset strategy

---

torchrl/envs/batched_envs.py

[Feature] Passing lists of keyword arguments in ``reset`` for batched envs

---

.github/unittest/linux_libs/scripts_robohive/environment.yml
.github/unittest/linux_libs/scripts_robohive/setup_env.sh
test/test_libs.py
torchrl/envs/common.py
torchrl/envs/libs/robohive.py
torchrl/envs/transforms/transforms.py

- Make `RoboHiveEnv` tests actually run correctly when executed
- Fixed a bug in testing of envs without cameras  
- Refactor and simplify test case 
Currently, the tests for `RoboHiveEnv` aren't actually executing correctly.  When the env is [instantiated](https://github.com/pytorch/rl/blob/main/test/test_libs.py#L3356), the `from_pixels` key isn't actually used, and none of the envs are tested with `from_pixels=True`.
After the test code is fixed, I get 9 failures for the RoboHive tests, all of which seem to be caused by an issue with `DKitty` environments. 
Short Test log:
```
================================================= short test summary info =================================================
FAILED test/test_libs.py::TestRoboHive::test_robohive[DKittyOrientFixed-v0-True] - …
```

[BugFix] Fix RoboHiveEnv tests

---

test/test_libs.py
torchrl/envs/libs/robohive.py

This PR adds a flag to enable returning of depth images from `RoboHiveEnv`.
Described in #2051 
`close #2051`
(I don't see any tests specific to `RoboHiveEnv` so I have not added any tests.)

[Feature] Return depth from RoboHiveEnv

---

torchrl/collectors/utils.py

Changes the way `.device` is obtained inside `split_trajectories`.
When `trajectory_key` is used there is not need for having `("next", "done")`, however, it was still used to get the `.device`.

[BugFix] Remove `split_trajectories`'s reference to `("next", "done")`.

---

docs/source/reference/data.rst
docs/source/reference/envs.rst
docs/source/reference/trainers.rst
test/test_loggers.py
test/test_specs.py
torchrl/data/__init__.py
torchrl/data/tensor_specs.py
torchrl/envs/batched_envs.py
torchrl/envs/common.py
torchrl/envs/utils.py
torchrl/record/__init__.py
torchrl/record/recorder.py

Adds a transform to record rgb_arrays coming from env.render()
cc @matteobettini @vikashplus
@Miffyli: I also added a bit of doc RE recording videos in torchrl, LMK if you see anything missing.

[Feature] A PixelRenderTransform

---

docs/requirements.txt

The CI for the docs was crashing due to the added pettingzoo dependency in the requirements.
Since the merged version of the MADDPG tutorial does not depend on pettingzoo because it uses vmas, we can solve this by removing the dependency
Otherwise, we should change the tutorial by setting use_vmas=False and figure out the dependency conflict

[CI] Fix Doc CI

---

test/test_rb.py
torchrl/data/replay_buffers/samplers.py

Allows to sample from a replay buffer storing trajectories by indicating the left and right span. 
For instance, `span=(True, True)` with trajectories of length 10 and slices of length (at most) 5 will lead to possible indices:
```python
[0]
[0, 1]
[0, 1, 2]
...
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
...
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]
```
and `(False, True)`
```python
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
...
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]
```
Hope that's useful!
Here's a piece of code to test the feature
```python
from torchrl.collectors.utils import split_trajectories
from torchrl.data import SliceSampler, TensorDictReplayBuffer, LazyMemmapStorage
import torch
torch.manual_seed(0)
data = TensorDict(
{"obs": torch.arange(1, 11).repeat(10),
"eps": …
```

[Feature] Span slice indices on the left and on the right

---

torchrl/data/tensor_specs.py

The following code, passing the deprecated `minimum` and `maximum`:
```python
from torchrl.data import BoundedTensorSpec
spec = BoundedTensorSpec(minimum=0, maximum=1, shape=(2,))
```
Raises the following error: `AttributeError: 'BoundedTensorSpec' object has no attribute 'DEPRECATED_KWARGS'`. This attribute was removed in a previous commit. 
I simply modified the warning message to keep the current functionality!
(did not raise an issue since it is super simple and will only affect depracted usage of one tensor spec)

[BugFix] missing deprecated kwargs

---

torchrl/collectors/collectors.py
torchrl/data/tensor_specs.py

This PR updates the docstrings for the `MultiSyncCollector` and `MultiaSyncCollector. It does several things:
- Add a note that code should be run inside a `if __name__ == "__main__":` block.
- Updated the examples and fixes some errors, including:
- The gymenv already has a stepcounter, so removed it.
- `devices` and `storing_devices` kwargs don't exist - it needs to be `device` and `storing_device`.
- Added `cat_results="stack"` to follow future behaviour.
- The collector wasn't actually imported in the example, so I added that too - it's now self-contained.
- The current `main` branch also does not pass pre-commit, which is why `tensor_specs.py` is changed too.
I'm currently building the docs to see if everything looks good, but it's taking *very* long. Any advice there?

[Doc] Indicate necessary context to run multiprocessed collectors in doc

---

torchrl/objectives/sac.py

This fixes a mismatch in the documentation of the default value of the `num_qvalue_nets` argument in `DiscreteSACLoss`. The documentation said that default is 10, but in reality it is 2.
This is misleading.

[Doc] Fix documentation mismatch for default argument

---

torchrl/record/loggers/mlflow.py

Currently, the MLFlow logger always tries to create a new experiment by calling `create_experiment`. If the experiment name already exists, this throws an error - so in practice running your script for the second time will crash the run. Additionally, MLFlow considers an `experiment` as a collection of `run`s, so we don't want to create a new experiment for each run. 
This PR modifies this logic by first checking if an experiment exists, creating one if necessary, and otherwise just retrieves the experiment ID.
Additionally, the MLFlow runs should be closed using `mlflow.end_run()` when it's not called as a context manager (as is the case for us). Do we want to add a `shutdown` method to the `Logger` base class to handle that? I can do that in this PR or in another.

Fix MLFlow logger

---

docs/source/reference/modules.rst
test/test_tensordictmodules.py
torchrl/data/tensor_specs.py
torchrl/envs/transforms/transforms.py
torchrl/modules/tensordict_module/rnn.py
torchrl/modules/utils/__init__.py
torchrl/modules/utils/utils.py

This PR adds a utils method to address https://github.com/pytorch/rl/issues/1771

[Feature] Extract primers from modules that contain RNNs

---

torchrl/modules/tensordict_module/actors.py

[Doc] default_interaction_type doc

---

torchrl/data/replay_buffers/replay_buffers.py

Adds loop termination condition in replay buffer `__iter__` method for yielding samples in prefetch queue and another condition in its `sample` method for only adding new jobs to the prefetch queue if the sampler has not yet run out.
For replay buffers with prefetch enabled while having a sampler without replacement (that can "run out"), the buffer's `__iter__` method will not yield all samples. This is because its while loop terminates on sampler `ran_out` which is set as soon as a prefetch job is executed that triggers running out. However, there might still be prefetch jobs in the queue left that could yield samples, therefore their samples are simply skipped.
Go over all the following points, and put an `x` …

[BugFix] buffer `__iter__` for samplers without replacement + prefetch

---

test/test_rb.py
torchrl/data/replay_buffers/samplers.py

The PrioritizedSampler docstring says that the input parameter alpha can be set to 0.0 to obtain uniform sampling. In practice though, a ValueError is raised when alpha = 0.0. This PR changes this to allow for alpha to be 0.0.

[BugFix] Allow zero alpha value for PrioritizedSampler

---

torchrl/data/replay_buffers/replay_buffers.py

Reverts pytorch/rl#2178
@JulianKu I'm reverting this because it breaks the offline IQL example 
To test this:
```
python sota-implementations/iql/iql_offline.py \
optim.gradient_steps=55 \
logger.backend=
```

Revert "[BugFix] buffer `__iter__` for samplers without replacement + prefetch"

---

torchrl/data/replay_buffers/storages.py

[BugFix] `LazyTensorStorage` only allocates data on the given device

---

test/mocking_classes.py
test/test_env.py
test/test_libs.py
torchrl/envs/utils.py

Fixes #2179
Replaces #2181
By enforcing resets to have the same shape as dones

[BugFix] Make `_reset` follow `done` shape

---

test/test_libs.py
torchrl/envs/libs/dm_control.py

[BugFix] Make DMControlEnv aware of truncated signals

---

test/test_transforms.py
torchrl/envs/batched_envs.py
torchrl/envs/common.py

[Quality] Remove global seeding in set_seed

---

torchrl/envs/libs/dm_control.py

Can we also have a test pipeline of torchrl that does not install any optional dependency?

[BugFix] Global import of optional library

---

test/test_rb.py
torchrl/data/replay_buffers/storages.py
torchrl/data/replay_buffers/utils.py

cc @teopir 
cc @shagunsodhani this is a good example of prealloc with tensordict. We were using a lot of lazy stacks and stacking at the last minute. Using a preallocated TD instead (create an empty td -> get a bunch of views of that td -> write on the first view, and all views get instantiated instantaneously) made the whole thing 20 - 1000x faster!

[Performance, Refactor] Faster loading of uninitialized storages

---

test/test_rb.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/samplers.py

Reopen #2178 (see #2182)
Adds loop termination condition in replay buffer `__iter__` method for yielding samples in prefetch queue and another condition in its `sample` method for only adding new jobs to the prefetch queue if the sampler has not yet run out.
For replay buffers with prefetch enabled while having a sampler without replacement (that can "run out"), the buffer's `__iter__` method will not yield all samples. This is because its while loop terminates on sampler `ran_out` which is set as soon as a prefetch job is executed that triggers running out. However, there might still be prefetch jobs in the queue left that could yield samples, therefore their samples are simply skipped.
Go over all the …

[BugFix] buffer __iter__ for samplers without replacement + prefetch

---

docs/source/reference/data.rst
test/test_rb.py
test/test_transforms.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/storages.py
torchrl/data/replay_buffers/writers.py
torchrl/envs/batched_envs.py
torchrl/envs/transforms/transforms.py

This PR enables assigning values to a RB.
This is slightly bc-breaking: 
Previously doing `storage[index] = foo` was exactly equivalent to `storage.set(index, foo)`. Now only the second will update the cursor position. This lets us assigning values without telling the buffer that we have moved the cursor.
TODO:
cc @wertyuilife2

[Feature] assinging values to RB storage 

---

test/test_rb.py
torchrl/data/replay_buffers/samplers.py

As noted in #2208, we register the cursor when computing the start/stop signals based on the "done" signals, but we don't do so when trajectories are provided. This PR solves this/

[BugFix] Fix sliced PRB when only traj is provided

---

sota-implementations/cql/cql_offline.py
sota-implementations/cql/cql_online.py
test/test_collector.py
torchrl/collectors/collectors.py
torchrl/envs/batched_envs.py
torchrl/envs/common.py
torchrl/modules/models/model_based.py
torchrl/objectives/a2c.py

Based on https://github.com/pytorch/tensordict/pull/817
Code to test:
```python
from torchrl.envs import GymEnv, Transform, check_env_specs
from torchrl.data import NonTensorSpec, TensorSpec
from torchrl.collectors import SyncDataCollector
from tensordict import TensorDictBase, TensorDict, NonTensorData
class AddNontTensorData(Transform):
def _call(self, tensordict: TensorDictBase) -> TensorDictBase:
tensordict["nt"] = "a string!"
return tensordict
def _reset(
self, tensordict: TensorDictBase, tensordict_reset: TensorDictBase
) -> TensorDictBase:
return tensordict_reset.set("nt", NonTensorData("reset!"))
def transform_observation_spec(self, observation_spec: TensorSpec) -> TensorSpec:
observation_spec["nt"] = NonTensorSpec(shape=())
return observation_spec
env = …
```

[BugFix] Fix collectors with non tensors

---

sota-implementations/cql/cql_offline.py
sota-implementations/cql/cql_online.py
torchrl/data/replay_buffers/samplers.py

Closes #2230
Unfortunately, I'm not sure how to test this. I guess we should save somewhere a tree structure and mass to replicate the issue (and possibly fix it directly in the c++ code @xiaomengy if you can help with this)

[BugFix] Fix OOB sampling in PrioritizedSliceSampler

---

test/test_rb.py
torchrl/data/replay_buffers/samplers.py

[BugFix] Fix max value within buffer during update priority

---

docs/source/reference/envs.rst
test/test_transforms.py
torchrl/data/tensor_specs.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

A transform to discretize continuous actions

[Feature] ActionDiscretizer

---

torchrl/envs/batched_envs.py

Improves perf of ParallelEnv without buffer
FPS for CartPole-v1 with gym on 4 procs (local) goes from 660fps to 1000fps on my machine.
Based on 
https://github.com/pytorch/tensordict/pull/814
```python
import time
import tqdm
from torchrl.envs import ParallelEnv, GymEnv
if __name__ == "__main__":
env = ParallelEnv(4, lambda: GymEnv("CartPole-v1"), use_buffers=False)
env.rollout(1000, break_when_any_done=False)
pbar = tqdm.tqdm(range(100))
t0 = time.time()
for i in pbar:
env.rollout(1000, break_when_any_done=False)
pbar.set_description(f"fps: {(1000 * (i+1)) / (time.time() - t0): 4.4f}")
```

[Performance] consolidate TDs in ParallelEnv without buffers

---

test/test_env.py
torchrl/envs/batched_envs.py
torchrl/envs/utils.py

Revert "[BugFix] Fix non-tensor passage in _StepMDP"

---

test/test_env.py
torchrl/envs/batched_envs.py
torchrl/envs/utils.py

[BugFix] Fix non-tensor passage in _StepMDP

---

docs/source/_static/js/theme.js
docs/source/_static/js/torchrl_theme.js
docs/source/_templates/layout.html

Fixes the links to run tutorials in Colab and to download notebooks.
close #2134

Fix "Run in Colab" and "Download Notebook" links in tutorials

---

.github/unittest/linux_libs/scripts_rlhf/environment.yml

With `transformers>=4.42.0` we get this error from calling vmap around the model:
```
File "/home/vmoens/tensordict/tensordict/nn/common.py", line 1185, in forward
tensors = self._call_module(tensors, **kwargs)
File "/home/vmoens/tensordict/tensordict/nn/common.py", line 1141, in _call_module
out = self.module(*tensors, **kwargs)
File "/home/vmoens/.conda/envs/torchrl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1566, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/home/vmoens/.conda/envs/torchrl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1575, in _call_impl
return forward_call(*args, **kwargs)
File "/home/vmoens/.conda/envs/torchrl/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1144, in forward …
```

[CI] Pin transformers version to < 4.42.0 to make vmap happy

---

docs/source/reference/trainers.rst

Fix documentation for Trainer checkpointing, which mistakenly said that `torchsnapshot` is the default backend, when `torch` is actually the default, as seen [here](https://github.com/pytorch/rl/blob/35663887d92419ec7eb326ec5ee4a1894b37d1d8/torchrl/_utils.py#L208).
Also fix incorrect syntax for the hyperlink to the torchsnapshot repo.
close #2075

[Doc] Fix mistakes in docs for Trainer checkpointing backends

---

torchrl/data/tensor_specs.py

Add documentation for masks in the four `*DiscreteTensorSpec`s.
close #2280

[Doc] Add documentation for masks in tensor specs

---

docs/source/reference/modules.rst
test/test_exploration.py
torchrl/modules/__init__.py
torchrl/modules/tensordict_module/__init__.py
torchrl/modules/tensordict_module/exploration.py

Add `OrnsteinUhlenbeckProcessModule`, which serves the same purpose as `OrnsteinUhlenbeckProcessWrapper`, but derives from `TensorDictModuleBase` rather than `TensorDictModuleWrapper`
part of #2295

[Feature] Add `modules.OrnsteinUhlenbeckProcessModule`

---

docs/source/reference/modules.rst
test/test_exploration.py
torchrl/modules/__init__.py
torchrl/modules/tensordict_module/__init__.py
torchrl/modules/tensordict_module/exploration.py

Add `AdditiveGaussianModule`, which serves the same purpose as `AdditiveGaussianWrapper`, but derives from `TensorDictModuleBase` rather than `TensorDictModuleWrapper`
part of #2295

[Feature] Add `modules.AdditiveGaussianModule`

---

sota-implementations/ddpg/ddpg.py
sota-implementations/ddpg/utils.py
sota-implementations/dreamer/dreamer.py
sota-implementations/dreamer/dreamer_utils.py
sota-implementations/multiagent/maddpg_iddpg.py
sota-implementations/redq/redq.py
sota-implementations/td3/td3.py
sota-implementations/td3/utils.py
sota-implementations/td3_bc/utils.py
test/test_collector.py
test/test_tensordictmodules.py
tutorials/sphinx-tutorials/coding_ddpg.py
tutorials/sphinx-tutorials/getting-started-1.py
tutorials/sphinx-tutorials/multiagent_competitive_ddpg.py

Update instances of
* `AdditiveGaussianWrapper` --> `AdditiveGaussianModule`
* `OrnsteinUhlenbeckProcessWrapper` --> `OrnsteinUhlenbeckProcessModule`
everywhere in the code base, except in `test/test_exploration.py`, which should still test both the wrappers and modules until we finally remove the wrappers in the future.
close #2295

[Refactor] Update all instances of exploration `*Wrapper` to `*Module`

---

torchrl/envs/libs/brax.py

This fixes the brax examples. It explicitly specifies the device to run env on as recommended in the error messages.
This fixes the issues which I was getting with the original errors:
```
/home/jorbik/Projects/rl/torchrl/envs/libs/brax.py:207: UserWarning: No device is set for env BraxEnv(env=ant, batch_size=torch.Size([4]), device=None). Setting a device in Brax wrapped environments is strongly recommended.
warnings.warn(
Traceback (most recent call last):
File "/home/jorbik/Projects/rl/test.py", line 19, in <module>
print(batch_size, timer.timeit(10))
^^^^^^^^^^^^^^^^
File "/home/jorbik/miniconda3/envs/torchrl/lib/python3.11/site-packages/torch/utils/benchmark/utils/timer.py", line 274, in timeit
self._timeit(number=max(int(number // 100), 2))
File …
```

Fix brax examples

---

docs/source/reference/envs.rst
test/test_transforms.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

Currently TorchRL has a CenterCrop transform. I have recently encountered a situation were I did not want to crop the center, but another part of the obs image.
For cases like this one, it would be interesting to have a Crop transform too, that allows to define the specific location of the cropping.
This super simple PR adds it. For the tests I have pretty much used the same as CenterCrop, as it is simply a more general Transform where the cropping location can be modified.
I thought about simply having single Transform for both cases (e.g. default behaviour is center crop but the starting location can be optionally provided). However, imo it is cleaner and more intuitive to have both.
If it fixes an open issue, please link to the …

[Feature] Crop Transform

---

torchrl/objectives/ppo.py

The PPO algorithm implies the _critic_ operator to compute the value of each state (`V(s)`) rather than the Q value (`Q(s, a)`) of a state-action pair.
Thus, an `ActorValueOperator` is the correct module to use here.

[Docs] Use more appropriate ActorValueOperator in PPOLoss documentation

---

README.md

This fixes two typos where a space was missing in the `pip3 install` command in the readme.
It's confusing if you just copy&paste the command for building the library by yourself or want to install the nightly version

Fix pip3install typos in Readme

---

test/test_modules.py
torchrl/modules/models/multiagent.py

We currently store the parameters in MARL modules in `self.params` in a TensorDictParams.
During a call to forward, we call `vmap` and `to_module` to put the batched parameters in place within the module.
This PR proposes to optionally make `self.params` a regular TensorDict (ie, `self.parameters()` will not see them because `self.params` is not within the `self.modules()` anymore), and place them in the `self._empty_net` instead. With that in place, the module has two copies of the parameters, but one is not accessible via `self.parameters()` (so things don't change from the user perspective).
We test that these two scenarios are identical and that sending the module to device does not create multiple distinct copies of the params.

[Feature] Store MARL parameters in module

---

.github/workflows/benchmarks.yml
.github/workflows/benchmarks_pr.yml
.github/workflows/test-linux-examples.yml
.github/workflows/test-linux-habitat.yml
.github/workflows/test-linux-libs.yml
.github/workflows/test-linux-rlhf.yml
.github/workflows/test-linux.yml
.github/workflows/test-windows-optdepts.yml
torchrl/data/tensor_specs.py

This PR
- Adds TD_GET_DEFAULTS_TO_NONE=1 in all CIs to execute tests based on the new TensorDict.get behaviour
- Adds a `tests-cpu-oldget` CI to check that tests pass (on CPU) when `TD_GET_DEFAULTS_TO_NONE=0`
- Fixes behaviours for the new behaviour

[BugFix, CI] Set `TD_GET_DEFAULTS_TO_NONE=1` in all CIs

---

test/test_rb.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/samplers.py
torchrl/data/replay_buffers/storages.py
torchrl/data/replay_buffers/writers.py

Implements a `generator` argument in replay buffers that allows to control the local (RB-specific) seed.

[Feature] RNG for RBs

---

knowledge_base/VIDEO_CUSTOMISATION.md

Documentation error in `knowledge_base` entry regarding how to pass custom settings into `VideoRecorder`.

Correct minor erratum in `knowledge_base` entry

---

torchrl/envs/common.py
torchrl/envs/gym_like.py
torchrl/envs/libs/gym.py

Adds a configuration parameter to `GymLikeEnv` to specify whether or not actions should be converted to numpy arrays before being passed to the step function of the underlying environment to retrieve the next state. Users can now pass `convert_actions_to_numpy=False` when wrapping environments that work with torch tensors. 
Let me know if a new test is required for this. 
Previously, it was assumed that the step function argument expected numpy array types on CPU, which makes torchrl incompatible with environments like IsaacLab that operate on torch tensors and on the GPU. 
Closes #2369 
- [] Bug fix (non-breaking change which fixes an issue)
- [] Breaking change …

[Feature] Support wrapping IsaacLab environments with GymEnv

---

test/mocking_classes.py
test/test_env.py
torchrl/envs/batched_envs.py

* #2382
* #2381
* __->__ #2377

[Feature] Partial steps in batched envs

---

torchrl/envs/batched_envs.py
torchrl/envs/common.py

[Feature] break_when_all_done in rollout

---

.github/unittest/linux/scripts/environment.yml
.github/unittest/linux/scripts/run_all.sh
.github/unittest/linux_distributed/scripts/environment.yml
.github/unittest/linux_examples/scripts/environment.yml
.github/unittest/linux_libs/scripts_envpool/environment.yml
.github/unittest/linux_olddeps/scripts_gym_0_13/environment.yml
.github/workflows/benchmarks.yml
.github/workflows/benchmarks_pr.yml
docs/requirements.txt
sota-implementations/cql/cql_offline.py
test/test_transforms.py

[CI] Resolve DMC and mujoco pinned versions

---

test/test_collector.py
test/test_rb.py
torchrl/collectors/collectors.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/storages.py
torchrl/envs/custom/pendulum.py

* #2389
* #2388
* #2387
* __->__ #2384

[Feature] Pass replay buffers to SyncDataCollector

---

test/test_collector.py
torchrl/collectors/collectors.py

* #2389
* #2388
* __->__ #2387
* #2384

[Feature] Pass replay buffers to MultiaSyncDataCollector

---

torchrl/data/replay_buffers/replay_buffers.py

[BugFix] pin-mem all rb outputs

---

torchrl/envs/transforms/transforms.py

Improves the performance of `CatFrames.unfolding` with `padding="same"`. Running the performance measurement script in the issue description of #2406 shows a speedup of ~70x compared to the previous implementation:
```
WITHOUT CATFRAMES
Sampling took 0.0016054896002363724 seconds.
WITH CATFRAMES
Sampling took 0.003015774066928619 seconds.
```
close #2406

[Performance] Faster `CatFrames.unfolding` with `padding="same"`

---

.github/unittest/linux_libs/scripts_open_spiel/environment.yml
.github/unittest/linux_libs/scripts_open_spiel/install.sh
.github/unittest/linux_libs/scripts_open_spiel/post_process.sh
.github/unittest/linux_libs/scripts_open_spiel/run-clang-format.py
.github/unittest/linux_libs/scripts_open_spiel/run_test.sh
.github/unittest/linux_libs/scripts_open_spiel/setup_env.sh
.github/workflows/test-linux-libs.yml
README.md
docs/source/reference/envs.rst
setup.py
test/test_libs.py
torchrl/envs/__init__.py
torchrl/envs/libs/__init__.py
torchrl/envs/libs/openspiel.py

Adds environment wrapper classes for OpenSpiel.
`OpenSpielWrapper.reset` supports resetting to a specified state.
Part of #2133

[Feature] Add `OpenSpielWrapper` and `OpenSpielEnv`

---

torchrl/data/tensor_specs.py

This pull request resolves an invalid CUDA ID error that occurs when transferring a Bounded variable between servers with different numbers of GPUs.
In the current implementation, when changing the device of a `Bounded` variable, there is:
https://github.com/pytorch/rl/blob/df4fa7808e81f4b95ee2c22a4bb768370a669048/torchrl/data/tensor_specs.py#L2273-L2274
This operation first attempts to move `self.space._low` to its `self.space.device` before transferring to the target device (`dest`):
https://github.com/pytorch/rl/blob/df4fa7808e81f4b95ee2c22a4bb768370a669048/torchrl/data/tensor_specs.py#L376-L382
This process leads to errors when a variable previously on `cuda:7` (in an 8 GPU server) is loaded on a server with only one GPU, as it incorrectly attempts to access `cuda:7`.
The issue was …

[BugFix] Fix invalid CUDA ID error when loading Bounded variables across devices

---

torchrl/data/replay_buffers/samplers.py

Speeds up the `SliceSampler._tensor_slices_from_startend` method by about 8x in the case where `seq_length` is an int.
Running the performance measurement script from https://github.com/pytorch/rl/issues/2422#issue-2508402938 in my machine gives:
```
Without SliceSampler: 0.00019115543303390345 s
With SliceSampler: 0.002860310899753434 s
Slowdown factor: 14.963272842190824x
```
whereas the output before the change was:
```
Without SliceSampler: 0.0001870056662786131 s
With SliceSampler: 0.0046725646670286855 s
Slowdown factor: 24.98621972270721x
```
So this change provides a speedup of about `(0.00467 / 0.00286) = 1.632` to the `ReplayBuffer.sample` method for the particular case in that script.
I also took a performance profile of the script with `cProfile`, like so:
```bash
pthon -m …
```

[Performance] Faster `SliceSampler._tensor_slices_from_startend`

---

torchrl/objectives/dqn.py
tutorials/sphinx-tutorials/getting-started-5.py

Fixes errors pointed in https://discuss.pytorch.org/t/suspected-error-in-dqn-tutorial/

[Doc] Fix policy in getting started

---

torchrl/data/replay_buffers/samplers.py

Speeds up `PrioritizedSliceSampler._padded_indices` by about 2x.
Running the performance script given in https://github.com/pytorch/rl/issues/2431#issue-2517641562, my machine gives the following:
```
time: 7.804846733536882 ms
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
900    2.739    0.003    3.114    0.003 samplers.py:1845(_padded_indices)
900    0.197    0.000    6.895    0.008 samplers.py:1907(sample)
900    0.067    0.000    0.342    0.000 samplers.py:473(sample)
```
This is a speedup of (22.235 / 7.804) = 2.8x
Although sometimes, the runtime per `sample` call reaches up to 11.8 ms, a speedup of ~1.8x.
close #2431
Go over all the following points, and put an `x` in all the boxes …

[Performance] Faster `PrioritizedSliceSampler._padded_indices`

---

test/test_cost.py
torchrl/objectives/a2c.py
torchrl/objectives/ppo.py

* __->__ #2435
cc @albertbou92

[BugFix] compatibility to new Composite dist log_prob/entropy APIs

---

test/test_rb.py
torchrl/data/replay_buffers/storages.py

[Feature] Prevent loading existing mmap files in storages if they already exist

---

.github/unittest/linux/scripts/run_all.sh
.github/unittest/linux_examples/scripts/run_all.sh
.github/unittest/linux_libs/scripts_brax/install.sh
.github/unittest/linux_libs/scripts_openx/install.sh
.github/unittest/linux_libs/scripts_rlhf/install.sh
.github/unittest/linux_libs/scripts_vd4rl/install.sh
.github/unittest/linux_olddeps/scripts_gym_0_13/install.sh
.github/unittest/linux_optdeps/scripts/install.sh
.github/workflows/benchmarks.yml
.github/workflows/benchmarks_pr.yml
benchmarks/test_objectives_benchmarks.py
test/test_cost.py
torchrl/__init__.py
torchrl/data/tensor_specs.py
torchrl/envs/transforms/transforms.py
torchrl/modules/distributions/continuous.py
torchrl/modules/distributions/utils.py
torchrl/objectives/a2c.py
torchrl/objectives/common.py
torchrl/objectives/cql.py
torchrl/objectives/iql.py
torchrl/objectives/ppo.py
torchrl/objectives/redq.py
torchrl/objectives/td3.py
torchrl/objectives/td3_bc.py
torchrl/objectives/utils.py

* #2426
* #2410
* #2408
* __->__ #2405

[Feature] Make benchmarked losses compatible with torch.compile

---

.github/unittest/linux_libs/scripts_minari/environment.yml
test/test_libs.py

With Minari 0.5.0 release, we regrouped dependencies to install only the required ones depending on user usage. 
Moreover, we restructured the datasets to be hierarchical. This caused the `torch/rl` tests to fail; this PR should fix them.
I changed the tests to rely on Minari for getting the last version of the datasets.
Also, Minari 0.5.0 adds support for Arrow datasets, I am happy to integrate it in `torch/rl`.
Fixes failing CI due to new version of Minari.

[CI] Fix Minari tests

---

README.md

* #2426
* #2410
* __->__ #2408

[Doc] Document losses in README.md

---

torchrl/modules/distributions/discrete.py

[Feature] Deterministic sample for Masked one-hot

---

.github/workflows/build-wheels-windows.yml
.github/workflows/wheels-legacy.yml

[CI] Fix windows build legacy

---

.github/workflows/build-wheels-windows.yml
.github/workflows/wheels-legacy.yml
test/test_rb.py
torchrl/data/replay_buffers/storages.py

[BugFix] Extend RB with lazy stack

---

torchrl/data/replay_buffers/storages.py

[BugFix] Extend RB with lazy stack (revamp)

---

torchrl/data/replay_buffers/storages.py

[BugFix] Fix displaying of tensor sizes in buffers

---

torchrl/data/replay_buffers/samplers.py
torchrl/data/replay_buffers/storages.py

[Refactor] Use empty_like in storage construction

---

sota-implementations/impala/utils.py
torchrl/envs/common.py
torchrl/envs/libs/gym.py
torchrl/envs/utils.py
torchrl/modules/distributions/continuous.py
torchrl/objectives/value/functional.py
tutorials/sphinx-tutorials/pendulum.py
tutorials/sphinx-tutorials/torchrl_envs.py

These are minor fixes to comments and docstrings that I've been gathering for the past weeks.

[Doc] Minor fixes to comments and docstrings

---

test/test_collector.py
torchrl/collectors/collectors.py

The listing of updated keys in the collector after running the policy checks that an entry is either new or updated or updated and not identical, when it should be new OR (updated AND not identical).

[BugFix] Fix listing of updated keys in collectors

---

test/test_transforms.py
torchrl/collectors/collectors.py
torchrl/envs/transforms/transforms.py

This PR fixes what I think is a bug in the `transform_input_spec` method of the `Compose` transform. 
The original code goes backward through the list of transforms:
```python
def transform_input_spec(self, input_spec: TensorSpec) -> TensorSpec:
for t in self.transforms[::-1]:
input_spec = t.transform_input_spec(input_spec)
return input_spec
```
while I believe this should go forward to propagate the input spec of the underlying env.
```python
def transform_input_spec(self, input_spec: TensorSpec) -> TensorSpec:
for t in self.transforms:
input_spec = t.transform_input_spec(input_spec)
return input_spec
```
I noticed this issue after trying to compose two inverse transformations: `DiscretiseAction` and `RenameTransform` -- which broke with a "key" error. I also tried to chain some …

[BugFix] Fix Compose input spec transform

---

torchrl/envs/transforms/transforms.py

From the documentation and tests it is implicit that the number of in and out keys should match in the transformations. I'm proposing to enforce that through a runtime check by adding the `strict=True` when using zip. If the sequences don't have the same number of elements a `ValueError` is raised.
Let me know if you think enforcing this assumption requires some tests. Happy to take your suggestions if you have an idea on how to easily test all the calls to `zip`.
This will ensure the keys are provided by pairs. Currently last elements of the longest list are ignored.
Not sure if preventing silent errors should be considered a bug fix or a new feature to guide the users.
If you are unsure about any of these, …

[Feature] Ensure transformation keys have the same number of elements

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

[BugFix] Fix DeviceCastTransform

---

torchrl/__init__.py
torchrl/modules/distributions/continuous.py
torchrl/objectives/utils.py

[BugFix] torch 2.0 compatibility fix

---

setup.py
test/_utils_internal.py
test/test_libs.py
test/test_utils.py
torchrl/_utils.py
torchrl/envs/libs/_gym_utils.py
torchrl/envs/libs/gym.py

[Versioning] Gymnasium 1.0 incompatibility errors

---

test/test_env.py
torchrl/envs/batched_envs.py

Add runtime checks to ensure the `create_env_kwargs` and `kwargs` passed to the `__init__()` and `update_kwargs()` respectively have the right number of elements, i.e. the number of workers.
An off by one error got me pretty hard.
Not sure if that is a bug fix or a new feature to add these checks.

[Feature] Check number of kwargs matches num_workers

---

.github/unittest/linux_libs/scripts_unity_mlagents/environment.yml
.github/unittest/linux_libs/scripts_unity_mlagents/install.sh
.github/unittest/linux_libs/scripts_unity_mlagents/post_process.sh
.github/unittest/linux_libs/scripts_unity_mlagents/run-clang-format.py
.github/unittest/linux_libs/scripts_unity_mlagents/run_test.sh
.github/unittest/linux_libs/scripts_unity_mlagents/setup_env.sh
.github/workflows/test-linux-libs.yml
docs/source/reference/envs.rst
pytest.ini
test/conftest.py
test/test_libs.py
torchrl/envs/__init__.py
torchrl/envs/libs/__init__.py
torchrl/envs/libs/unity_mlagents.py

Adds `UnityMLAgentsWrapper` and `UnityMLAgentsEnv` environment wrapper classes to control MLAgents environments from TorchRL.
close #1110

[Feature] Add env wrapper for Unity MLAgents

---

test/test_transforms.py

The last line of the test was always checking to true:
```python
assert "action_2"
```
and was missing a few characters to be complete:
```python
assert "action_2" in action
```

[Minor] Fix test_compose_action_spec

---

test/test_libs.py
torchrl/envs/libs/unity_mlagents.py

Adds the `group_map` argument to `UnityMLAgentsWrapper` and `UnityMLAgentsEnv`.
Close #2490

[Feature] Add `group_map` support to MLAgents wrappers

---

torchrl/objectives/utils.py

[Feature] inline `hold_out_net`

---

sota-implementations/dreamer/dreamer.py
test/test_cost.py
torchrl/objectives/dreamer.py

Avoid reshaping inputs to `DreamerActorLoss`.
Follow-up to #2494

[BugFix] Avoid `reshape(-1)` for inputs to `DreamerActorLoss`

---

.github/unittest/linux_libs/scripts_rlhf/install.sh
.github/unittest/linux_olddeps/scripts_gym_0_13/environment.yml
test/test_cost.py

[CI] Fix h5py dependency in olddeps

---

benchmarks/test_replaybuffer_benchmark.py

[Benchmark] Add benchmark for compiled `ReplayBuffer.extend/sample`

---

torchrl/data/replay_buffers/storages.py
tutorials/sphinx-tutorials/multiagent_competitive_ddpg.py

[Doc] MADDPG bug fix of buffer device and improve explaination

---

torchrl/data/replay_buffers/replay_buffers.py

[Feature] Send info dict to the storage device in RBs

---

docs/source/reference/envs.rst
test/test_transforms.py
torchrl/envs/__init__.py
torchrl/envs/batched_envs.py
torchrl/envs/env_creator.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

[Feature] TrajCounter transform

---

benchmarks/test_replaybuffer_benchmark.py
test/test_rb.py
torchrl/_utils.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/storages.py
torchrl/data/replay_buffers/writers.py

Performance improvements for compiled `ReplayBuffer.extend/sample` with `LazyTensorStorage`. For the cases tested in the benchmark, compiled gives the same or better performance than eager.
This uses the changes from #2426 to avoid using multiprocessing features, but also adds some other changes to avoid graph breaks in other places.
The benchmark and test are updated to include both cases where the storage's max size is reached and not reached.
Part of #2501

[Performance] Improve performance of compiled ReplayBuffer

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

Often, when defining `TensorDictPrimer` transforms during environment creation, the batch size is unknown. For example when we create the transform with the` torchrl.modules.utils.get_primers_from_module` method.
In `TensorDictPrimer`, we assume that if the parent environment is batch-locked, the specs will already have the appropriate leading shape. However, this can lead to issues if the batch size is unknown at instantiation.
Maybe I am missing something here, but this PR makes sure the primer matches the parent batch size during reset, expanding it if necessary.
What types of changes does your code …

[BugFix] Allow expanding TensorDictPrimer transforms shape with parent batch size

---

torchrl/_extension.py

[Quality] Better warning when c++ binaries failed to be imported

---

test/test_cost.py
torchrl/objectives/ppo.py

The function `get_entropy_bonus` was not unpacking the `entropy` from the `TensorDict`.
When using a `CompositeDistribution`, the return type of the entropy can be either a `Tensor` or a `TensorDict` depending on the `aggregate_probabilities`. This break the `get_entropy_bonus` that expects a `Tensor`. We can unpack it accessing by the entropy key.

[BugFix] Support for tensor collection in the `PPOLoss`

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

Reverts pytorch/rl#2521
cc @albertbou92 this was causing `test_tensordictprimer_batching` to break - can you have a look and resubmit a PR?

Revert "[BugFix] Allow expanding TensorDictPrimer transforms shape with parent batch size"

---

test/test_cost.py
torchrl/objectives/common.py

Adds `LossModule.reset_parameters_recursive`, which resets each parameter using the `reset_parameters_recursive` method from its corresponding submodule.
Close #2538

[Feature] Add `LossModule.reset_parameters_recursive`

---

sota-implementations/ppo/ppo_atari.py
torchrl/envs/common.py

Minor improvements to the documentation and type hints of the environment code.

[Doc] Minor fixes to the docs and type hints

---

test/test_trainer.py
torchrl/trainers/trainers.py

* __->__ #2558
cc @mikaylagawarecki @albanD

[BugFix] Fix tests failing because of https://github.com/pytorch/pytorch/pull/137602

---

docs/requirements.txt
docs/source/index.rst
torchrl/modules/models/models.py
torchrl/modules/tensordict_module/exploration.py
tutorials/sphinx-tutorials/export.py

* #2559
* __->__ #2557
cc @agunapal @matteobettini @desertfire @angelayi @gmagogsfm @ezyang (and @janeyx99 since it's kinda BE? 😉 )

[Doc] Tutorial on exporting TorchRL models

---

tutorials/sphinx-tutorials/torchrl_demo.py
tutorials/sphinx-tutorials/torchrl_envs.py

[Doc] Fix tutorials

---

tutorials/sphinx-tutorials/export.py

[BugFix,Doc] Revert dynamic shape in export tutorial

---

tutorials/sphinx-tutorials/export.py

[Doc] Add AOTInductor back

---

test/test_collector.py
torchrl/collectors/collectors.py

* #2578
* #2577
* #2576
* __->__ #2575

[BugFix] Fix collector length with non-empty batch size

---

.github/workflows/docs.yml
benchmarks/test_objectives_benchmarks.py
torchrl/envs/libs/vmas.py
torchrl/objectives/utils.py
torchrl/objectives/value/advantages.py

[CI] Fix docs upload

---

test/_utils_internal.py
torchrl/modules/tensordict_module/exploration.py

[BugFix] make buffers zero-dim in exploration modules

---

.github/unittest/linux/scripts/environment.yml
.github/unittest/linux_distributed/scripts/environment.yml
.github/unittest/linux_libs/scripts_envpool/environment.yml
.github/unittest/linux_libs/scripts_gym/environment.yml
.github/unittest/linux_libs/scripts_robohive/environment.yml
.github/unittest/linux_olddeps/scripts_gym_0_13/environment.yml
.github/unittest/linux_sota/scripts/environment.yml
README.md
setup.py
sota-check/README.md
sota-implementations/multiagent/README.md

[Versioning] Fix moviepy 2.0 incompatibility

---

torchrl/data/tensor_specs.py

* #2601
* #2600
* #2599
* #2598
* __->__ #2597
* #2596

[Feature] Composite.batch_size

---

torchrl/data/tensor_specs.py

* #2601
* #2600
* __->__ #2599
* #2598
* #2597
* #2596

[Feature] Composite.separates

---

torchrl/modules/models/models.py
tutorials/sphinx-tutorials/getting-started-3.py
tutorials/sphinx-tutorials/rb_tutorial.py

Fix several typos in the documentation

[Doc] fix several typos

---

test/test_cost.py
torchrl/objectives/sac.py

[BugFix] Account for terminating data in SAC losses

---

torchrl/data/replay_buffers/samplers.py

[Doc] Better doc for SliceSampler

---

test/test_cost.py
torchrl/objectives/sac.py

[BugFix] skip_done_states in SAC

---

test/mocking_classes.py
test/test_env.py
torchrl/envs/common.py
torchrl/envs/utils.py

[Feature, Test] Adding tests for envs that have no specs

---

torchrl/modules/tensordict_module/actors.py
torchrl/modules/tensordict_module/probabilistic.py

Changed docstrings in `ProbabilisticActor` and `SafeProbabilisticModule` to clarify that the keyword argument `default_interaction_type` should take one of the enum values of `tensordict.nn.InteractionType`. Previous documentation made me think that I had to supply the literal string, e.g "InteractionType.RANDOM".
Clearer documentation.

[Doc] actor docstrings

---

tutorials/sphinx-tutorials/multiagent_ppo.py

[BugFix] Fix MARL PPO tutorial action_spec call

---

.github/unittest/linux_libs/scripts_unity_mlagents/run_test.sh
test/mocking_classes.py
test/test_transforms.py
torchrl/envs/__init__.py
torchrl/envs/libs/unity_mlagents.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

Adds a transform that stacks tensors and specs from different keys of a tensordict into a common key.
close #2566

[Feature] Add `Stack` transform

---

test/mocking_classes.py

[BugFix] Fix typing for python 3.9

---

.github/workflows/docs.yml

[CI] Change doc image

---

torchrl/data/map/hash.py
torchrl/data/map/tdstorage.py
torchrl/data/map/tree.py
torchrl/data/map/utils.py
torchrl/data/replay_buffers/storages.py

* #2641
* #2640
* #2639
* #2638
* #2637
* #2636
* #2635
* __->__ #2634

[Refactor] Refactor trees

---

docs/source/reference/envs.rst
docs/source/reference/trainers.rst
test/test_env.py
torchrl/data/map/tree.py
torchrl/envs/__init__.py
torchrl/envs/common.py
torchrl/envs/custom/__init__.py
torchrl/envs/custom/llm.py
torchrl/envs/utils.py

* #2641
* #2640
* #2639
* #2638
* #2636
* __->__ #2635

[Feature] LLMHashingEnv

---

torchrl/envs/common.py

* #2641
* #2640
* #2639
* #2638
* __->__ #2636
* #2635

[Feature] env.step_mdp

---

test/test_specs.py
torchrl/data/tensor_specs.py
torchrl/envs/common.py

* #2641
* #2640
* #2639
* __->__ #2638

[Feature] spec.cardinality

---

torchrl/_utils.py
torchrl/envs/utils.py

* #2641
* #2640
* __->__ #2639
* #2638

[Quality,BE] Better doc for step_mdp

---

test/mocking_classes.py
test/test_env.py

* #2641
* __->__ #2640
* #2639
* #2638

[Test] More comprehensive tests for auto_spec

---

docs/source/reference/envs.rst
torchrl/envs/__init__.py
torchrl/envs/custom/__init__.py
torchrl/envs/custom/chess.py

[Feature] ChessEnv

---

examples/replay-buffers/catframes-in-buffer.py
torchrl/data/replay_buffers/samplers.py
torchrl/envs/transforms/transforms.py

[Feature] CatFrames.make_rb_transform_and_sampler

---

sota-implementations/iql/iql_online.py
sota-implementations/ppo/config_atari.yaml
sota-implementations/ppo/config_mujoco.yaml
sota-implementations/ppo/ppo_atari.py
sota-implementations/ppo/ppo_mujoco.py
sota-implementations/ppo/utils_atari.py
sota-implementations/ppo/utils_mujoco.py
torchrl/_utils.py
torchrl/collectors/collectors.py

* #2654
* #2653
* __->__ #2652
* #2649

[Feature] PPO compatibility with compile

---

sota-implementations/a2c/a2c_atari.py
sota-implementations/a2c/a2c_mujoco.py
sota-implementations/cql/cql_offline.py
sota-implementations/cql/cql_online.py
sota-implementations/cql/discrete_cql_online.py
sota-implementations/crossq/crossq.py
sota-implementations/ddpg/ddpg.py
sota-implementations/decision_transformer/dt.py
sota-implementations/decision_transformer/online_dt.py
sota-implementations/discrete_sac/discrete_sac.py
sota-implementations/dqn/dqn_atari.py
sota-implementations/dqn/dqn_cartpole.py
sota-implementations/dreamer/dreamer.py
sota-implementations/gail/gail.py
sota-implementations/iql/discrete_iql.py
sota-implementations/iql/iql_offline.py
sota-implementations/iql/iql_online.py
sota-implementations/ppo/ppo_atari.py
sota-implementations/ppo/ppo_mujoco.py
torchrl/__init__.py
torchrl/_utils.py

[Feature] timeit.printevery

---

sota-implementations/cql/cql_online.py
sota-implementations/cql/discrete_cql_online.py
sota-implementations/crossq/crossq.py
sota-implementations/ddpg/ddpg.py
sota-implementations/discrete_sac/discrete_sac.py
sota-implementations/iql/discrete_iql.py
sota-implementations/iql/iql_online.py
sota-implementations/sac/config.yaml
sota-implementations/sac/sac.py
sota-implementations/td3/config.yaml
sota-implementations/td3/td3.py
sota-implementations/td3/utils.py
test/test_specs.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/tensor_specs.py
torchrl/modules/tensordict_module/exploration.py

[Feature] TD3 compatibility with compile

---

sota-implementations/td3_bc/config.yaml
sota-implementations/td3_bc/td3_bc.py
sota-implementations/td3_bc/utils.py

[Feature] TD3-bc compatibility with compile

---

.github/unittest/linux_libs/scripts_chess/environment.yml
.github/unittest/linux_libs/scripts_chess/install.sh
.github/unittest/linux_libs/scripts_chess/post_process.sh
.github/unittest/linux_libs/scripts_chess/run-clang-format.py
.github/unittest/linux_libs/scripts_chess/run_test.sh
.github/unittest/linux_libs/scripts_chess/setup_env.sh
.github/workflows/test-linux-libs.yml
test/test_env.py
torchrl/envs/custom/chess.py

[Test] Add tests and a few fixes for ChessEnv

---

test/test_storage_map.py
torchrl/data/map/hash.py

Fix typo so that `SipHash(as_tensor=False)` returns the correct output.
close #2663

[BugFix] Fix output of `SipHash(as_tensor=False)`

---

sota-implementations/a2c/a2c_atari.py
sota-implementations/a2c/a2c_mujoco.py
sota-implementations/cql/cql_offline.py
sota-implementations/cql/cql_online.py
sota-implementations/cql/discrete_cql_online.py
sota-implementations/cql/utils.py
sota-implementations/crossq/crossq.py
sota-implementations/ddpg/ddpg.py
sota-implementations/decision_transformer/dt.py
sota-implementations/decision_transformer/online_dt.py
sota-implementations/decision_transformer/utils.py
sota-implementations/discrete_sac/discrete_sac.py
sota-implementations/dqn/config_atari.yaml
sota-implementations/dqn/config_cartpole.yaml
sota-implementations/dqn/dqn_atari.py
sota-implementations/dqn/dqn_cartpole.py
sota-implementations/gail/gail.py
sota-implementations/impala/impala_multi_node_ray.py
sota-implementations/impala/impala_multi_node_submitit.py
sota-implementations/impala/impala_single_node.py
sota-implementations/iql/discrete_iql.py
sota-implementations/iql/iql_offline.py
sota-implementations/iql/iql_online.py
sota-implementations/multiagent/utils/logging.py
sota-implementations/ppo/ppo_atari.py
sota-implementations/ppo/ppo_mujoco.py
sota-implementations/sac/sac.py
sota-implementations/td3/td3.py
sota-implementations/td3_bc/td3_bc.py

[Feature] Log pbar rate in SOTA implementations

---

.github/workflows/nightly_build.yml
sota-implementations/decision_transformer/utils.py
test/test_tensordictmodules.py
test/test_transforms.py
torchrl/envs/batched_envs.py
torchrl/envs/transforms/transforms.py
torchrl/modules/tensordict_module/rnn.py

* #2674
* #2672
* #2671
* #2670
* __->__ #2668

[BugFix] Compatibility of tensordict primers with batched envs (specifically for LSTM and GRU)

---

torchrl/data/replay_buffers/samplers.py

* #2674
* #2672
* #2671
* __->__ #2670
* #2668

[BugFix] Avoid KeyError in slice sampler (for compile)

---

torchrl/data/replay_buffers/samplers.py

* #2674
* #2672
* __->__ #2671
* #2670
* #2668

[Performance] Avoid cloning trajs in SliceSampler

---

torchrl/data/replay_buffers/samplers.py
torchrl/data/replay_buffers/utils.py

* #2674
* __->__ #2672
* #2671
* #2670
* #2668

[Performance] Accelerate slice sampler on GPU

---

torchrl/envs/batched_envs.py

* __->__ #2674
* #2672
* #2671
* #2670
* #2668

[BugFix] Fix batching envs with non tensor data

---

examples/agents/recurrent_actor.py
torchrl/modules/tensordict_module/rnn.py

[Example] RNN-based policy example

---

docs/source/reference/envs.rst
test/test_transforms.py
torchrl/data/__init__.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

Adds a transform to linearise multi-objective rewards into a single one, via a weighted sum. Essentially, this is a reproduction of mo-gym's `LinearReward ` wrapper.
This feature provides a naive way to address multi-objective environments.

[Feature] Linearise reward transform

---

torchrl/record/loggers/csv.py
torchrl/record/loggers/mlflow.py
torchrl/record/loggers/wandb.py
torchrl/record/recorder.py

[BugFix, BE] Document and fix fps passing in recorder and loggers

---

torchrl/envs/libs/pettingzoo.py

[BugFix] PettingZoo dict action spaces

---

docs/source/reference/envs.rst
test/test_transforms.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py

[Feature] Add Hash transform and UnaryTransform

---

test/test_cost.py
torchrl/_utils.py
torchrl/objectives/ppo.py

Hello!
So, in this library we frequently apply standardizations over data (also called normalization) where we subtract the mean from the data and divide it by a standard deviation.
A few places where we do this that come to mind are in the transforms (where it can be used over observations and rewards) and in the advantages in ppo. Please let me know about other places if you can think of more.
The issue is that normally the mean and std statistics are computed over all the dimensions. But in multiagent settings, where for example a reward tensor could have an "agent" dimension, this is not the proper way to do it as different agents might have different reward distributions and applying standardization naively across them will create issues.
For example consider the case where we have 2 …

[Feature] multiagent data standardization: PPO advantages

---

docs/source/reference/envs.rst

`Stack` wasn't getting included in the docs build because there was no link to it

[Doc] Add `Stack` transform link in docs

---

test/test_cost.py
torchrl/objectives/ppo.py

This PR enables PPO to log the entropy of each individual head of a composite policy separately.  
Concretely, for a composite distribution with, say, a nested discrete and continuous head, the `td_out` is augmented with some detached values.
```python
>>> loss = PPO(td)
>>> loss.keys()
[..., entropy, discrete-head-entropy, continuous-head-entropy, ...]
```
This is an extremely useful debugging tool when training composite policies.

[Feature] Log each entropy for composite distributions in PPO

---

test/test_libs.py
torchrl/envs/gym_like.py

[BugFix] Account for composite actions in gym

---

torchrl/envs/transforms/transforms.py

* #2711
* #2709
* #2708
* #2702
* #2700
* __->__ #2699

[BugFix] patch rand_action in TransformedEnv to read the base_env method

---

test/test_collector.py
torchrl/collectors/collectors.py

[Feature] no_cuda_sync arg in collectors

---

docs/source/reference/data.rst
torchrl/data/__init__.py
torchrl/data/replay_buffers/__init__.py
torchrl/data/replay_buffers/samplers.py
torchrl/data/replay_buffers/storages.py

* #2730
* #2729
* #2728
* #2726
* #2725
* #2724
* __->__ #2723

[Feature] LazyStackStorage

---

.github/workflows/docs.yml
.github/workflows/test-linux-habitat.yml
.github/workflows/test-linux-libs.yml
.github/workflows/test-linux-rlhf.yml
.github/workflows/test-linux-sota.yml
.github/workflows/test-linux.yml

[CI] Cuda 12.4

---

test/test_env.py
test/test_transforms.py
torchrl/envs/common.py
torchrl/envs/transforms/transforms.py

* #2730
* #2729
* __->__ #2728

[BugFix] Temporarily remove unsafe caching in envs

---

.github/unittest/linux/scripts/run_all.sh
.github/unittest/linux_distributed/scripts/setup_env.sh
.github/unittest/linux_libs/scripts_d4rl/setup_env.sh
.github/unittest/linux_libs/scripts_gym/setup_env.sh
.github/unittest/linux_libs/scripts_habitat/run_test.sh
.github/unittest/linux_libs/scripts_habitat/setup_env.sh
.github/unittest/linux_libs/scripts_robohive/setup_env.sh
.github/unittest/linux_olddeps/scripts_gym_0_13/setup_env.sh
.github/unittest/linux_sota/scripts/run_all.sh
docs/source/reference/envs.rst
test/test_env.py
test/test_libs.py
test/test_specs.py
test/test_transforms.py
torchrl/data/tensor_specs.py
torchrl/envs/batched_envs.py
torchrl/envs/common.py
torchrl/envs/gym_like.py
torchrl/envs/libs/_gym_utils.py
torchrl/envs/libs/robohive.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py

* __->__ #2730
* #2729
* #2728

[Feature] Re-enable cache for specs

---

test/test_storage_map.py

[Test] Add tests for Tree

---

torchrl/modules/models/models.py

* #2751
* #2750
* #2749
* #2748
* #2747
* __->__ #2746
* #2745

[Deprecation] Change the default MLP depth

---

docs/source/reference/modules.rst
test/test_exploration.py
torchrl/modules/tensordict_module/exploration.py

* #2751
* #2750
* #2749
* __->__ #2748
* #2747
* #2746
* #2745

[Deprecation] Remove AdditiveGaussianWrapper

---

torchrl/data/replay_buffers/replay_buffers.py

* #2751
* __->__ #2750
* #2749
* #2748
* #2747
* #2746
* #2745

[Deprecation] Remove InPlaceSampler

---

test/test_specs.py
torchrl/data/tensor_specs.py

* __->__ #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745

[Deprecation] Gracing old *Spec with v0.8 versioning

---

docs/source/reference/envs.rst
torchrl/envs/common.py

[Doc] Add Tokenizer and auto-reset doc link

---

torchrl/data/tensor_specs.py
torchrl/envs/transforms/transforms.py
torchrl/modules/tensordict_module/common.py
torchrl/modules/tensordict_module/probabilistic.py

[BugFix] Fix safe probabilistic backward by removing in-place modif

---

docs/source/reference/data.rst
docs/source/reference/objectives.rst
examples/agents/composite_ppo.py
test/test_cost.py
torchrl/objectives/ppo.py
torchrl/objectives/utils.py
tutorials/sphinx-tutorials/multiagent_ppo.py

[BugFix] adapt log-prob TD batch-size to advantage shape in PPO

---

docs/source/reference/objectives.rst
test/test_cost.py
torchrl/envs/common.py

[Minor] Fix doc and MARL tests

---

.github/workflows/docs.yml

[CI] Install stable torch/tv in docs when on release branch

---

test/test_env.py
torchrl/envs/custom/chess.py

[Feature] Add `include_hash_inv` arg to `ChessEnv`

---

torchrl/_utils.py

Because `RL_WARNINGS` defaults to 1 `torchrl` adjusts the warning filter on all packages. This surfaces numerous warnings like `jsonschema.RefResolver is deprecated` etc. When using `warnings.filterwarnings` with the `module` argument the filtering can be limited to the `torchrl` module, and nothing more.

Limit warning filter to torchrl

---

torchrl/envs/gym_like.py

* #2775
* #2774
* #2771
* #2770
* __->__ #2769

[BugFix] Use brackets to get non-tensor data in gym envs

---

test/test_env.py
torchrl/envs/batched_envs.py
torchrl/envs/libs/gym.py
torchrl/envs/libs/robohive.py

* #2775
* #2774
* #2771
* __->__ #2770
* #2769

[BugFix] Avoid calling reset during env init

---

torchrl/data/tensor_specs.py
torchrl/envs/gym_like.py

* #2775
* #2774
* __->__ #2771
* #2770
* #2769

[BugFix] NonTensor should not convert anything to numpy

---

test/mocking_classes.py
test/test_collector.py
torchrl/collectors/collectors.py

* #2775
* __->__ #2774
* #2771
* #2770
* #2769

[BugFix] Fix collector timeouts

---

test/test_cost.py

* __->__ #2775
* #2774
* #2771
* #2770
* #2769

[BE] Make better logits in cost tests

---

torchrl/objectives/ppo.py

I believe there is a bug in PPOs' implementation when both `prev_log_prob` and `log_prob` are TensorDicts.
In the setting were both `prev_log_prob` and `log_prob` are TensorDicts, we were clamping `prev_log_prob - log_prob` directly, instead of their sum over features. 

[BugFix] PPOs with composite distribution

---

test/test_transforms.py
torchrl/envs/batched_envs.py
torchrl/envs/common.py
torchrl/envs/libs/pettingzoo.py
torchrl/envs/libs/smacv2.py
torchrl/envs/libs/unity_mlagents.py
torchrl/envs/transforms/transforms.py

* #2799
* #2798
* #2797
* #2793
* __->__ #2792

[Feature] ParallelEnv.consolidate

---

docs/source/reference/utils.rst
test/test_transforms.py
torchrl/__init__.py
torchrl/_utils.py
torchrl/envs/transforms/transforms.py

* #2799
* #2798
* #2797
* __->__ #2793
* #2792

[Deprecation] Softly change default behavior of auto_unwrap

---

torchrl/envs/transforms/transforms.py

* #2799
* __->__ #2798
* #2797
* #2793
* #2792

[BugFix] Fix calls to _reset_env_preprocess

---

test/test_storage_map.py
torchrl/data/map/tree.py

* #2796
* #2795
* __->__ #2794

[Feature] Add `MCTSForest/Tree.to_string`

---

torchrl/data/map/tree.py

* #2796
* __->__ #2795
* #2794

[Doc] Add docstring for `MCTSForest.extend`

---

test/mocking_classes.py
test/test_env.py
test/test_specs.py
test/test_transforms.py
torchrl/_utils.py
torchrl/collectors/collectors.py
torchrl/data/tensor_specs.py
torchrl/envs/batched_envs.py
torchrl/envs/common.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py

[BugFix] Test and fix life cycle of env with dynamic non-tensor spec

---

torchrl/envs/common.py

* #2823
* #2822
* #2821
* #2819
* #2818
* #2817
* #2816
* __->__ #2815
* #2732

[BugFix] Fix env.full_done_spec~s~

---

torchrl/data/tensor_specs.py

* #2823
* #2822
* #2821
* #2819
* #2818
* #2817
* __->__ #2816
* #2815
* #2732

[Feature] NonTensor batched arg

---

test/test_env.py
torchrl/envs/custom/llm.py
torchrl/envs/transforms/rlhf.py

* #2823
* #2822
* __->__ #2821
* #2819
* #2818
* #2817
* #2816
* #2815
* #2732

[Feature] DataLoadingPrimer handling of dataloader with batch-size > 0

---

torchrl/objectives/value/advantages.py

When passing a tensor value for the discounted/exponential average weight to GAE, we'd get the warning:
> UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor)
- [] My change requires a change to the documentation.

[BugFix] GAE warning when gamma/lmbda are tensors

---

torchrl/_utils.py

`setuptools` is no longer available by default starting in Python 3.12. As such, `distutils` is no longer available. `setuptools` still comes as part of `torch`, making it a transitive dependency for `torchrl`. While `setuptools` and `distutils` can still be used as part of the build process, this PR removes all `distutils` imports inside the code. Effectively, it is only about re-implementing the helper function `strtobool`.

[Setup] Remove `distutils` imports

---

test/test_storage_map.py
torchrl/data/llm/__init__.py
torchrl/data/llm/utils.py
torchrl/data/map/tree.py

Calling Tree.make_node was resulting in `TypeError: Tree.__init__() got an unexpected keyword argument 'node'.`
It looks as though it's because of a kwarg being passed as "node" instead of "node_data" at the end of the function so I renamed it. I added some tests to show this but it seemed a bit over the top to keep 3 separate tests for such a small thing so I combined them afterwards.
Thanks :)

[BugFix] Tree make node fix

---

test/test_env.py
torchrl/data/llm/__init__.py
torchrl/data/llm/utils.py
torchrl/envs/batched_envs.py

[BugFix] Fix PEnv device copies

---

test/test_transforms.py
torchrl/record/recorder.py

Small fix to prevent a crash in VideoRecorder
Fixes https://github.com/pytorch/rl/issues/2826
When creating a VideoRecorder with the latest torchrl version, we get a crash if we pass `fps` argument since `self.video_kwargs` is not set yet we try to set `self.video_kwargs['fps'] = fps`
- [] My change requires a change to the documentation.
- [ x ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [] I have updated the documentation accordingly.

Fixed VideoRecorder crash when passing fps

---

docs/source/reference/collectors.rst
test/test_distributed.py
torchrl/collectors/__init__.py
torchrl/collectors/collectors.py
torchrl/collectors/distributed/__init__.py
torchrl/collectors/distributed/generic.py
torchrl/collectors/distributed/ray.py
torchrl/collectors/distributed/rpc.py
torchrl/collectors/distributed/sync.py
torchrl/collectors/utils.py
torchrl/collectors/weight_update.py

[Feature] Local and Remote WeightUpdaters

---

torchrl/modules/distributions/discrete.py

Missing `Examples:` lead to docs being displayed wrong
Typo in docs.
Readability.
- [] My change requires a change to the documentation.
- [] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [] I have updated the documentation accordingly.

[Doc] Update discrete.py

---

test/test_env.py
torchrl/envs/custom/llm.py
torchrl/envs/transforms/llm.py
torchrl/envs/transforms/transforms.py
torchrl/modules/llm/vllm_policy.py

* #2861
* #2859
* #2857
* #2856
* #2854
* __->__ #2852

[Feature] Tokenizer for LLMEnv

---

torchrl/data/tensor_specs.py
torchrl/envs/transforms/llm.py
torchrl/modules/llm/transformers_policy.py
torchrl/objectives/ppo.py

* #2861
* #2859
* #2857
* #2856
* __->__ #2854
* #2852

[BugFix] Right log-prob size in transformer wrapper

---

torchrl/modules/llm/vllm_policy.py

* #2861
* #2859
* #2857
* __->__ #2856
* #2854
* #2852

[Feature] Set padded token log-prob to 0.0

---

test/test_actors.py
torchrl/envs/custom/llm.py
torchrl/envs/transforms/llm.py
torchrl/envs/utils.py
torchrl/modules/llm/vllm_policy.py

* __->__ #2861
* #2859
* #2857
* #2856
* #2854
* #2852

[Feature] Allow using lists of tensors in vllm instead of padded tensors

---

test/test_distributions.py
torchrl/modules/__init__.py
torchrl/modules/distributions/discrete.py
torchrl/modules/llm/common.py

* #2884
* #2883
* __->__ #2882
* #2881

[Refactor] MaskedCategorical cross_entropy usage for faster loss

---

test/test_rb.py
test/test_transforms.py
torchrl/envs/transforms/vecnorm.py

[Refactor] VecNormV2: update before norm, bias_correction at the right time

---

torchrl/objectives/value/advantages.py

Previously, when calculating the GAE, torchrl assumes that there is a valid `s_(t+1)` return from the environment. However, for auto-resetting environments, that is not true at the end of the episode, as it just jumps to the first state of the next episode. This PR adds a feature to the GAE class, allowing users to specify if it's an auto-resetting env, in which case it will use the `s_t`  as an approximation for bootstrapping. 
Without this change, we were getting much slower convergence rates during training for IsaacLab (an autoresetting env).

[Feature] Add option for auto-resetting envs in GAE

---

docs/source/reference/envs.rst
test/mocking_classes.py
test/test_collector.py
test/test_cost.py
test/test_env.py
test/test_libs.py
test/test_transforms.py
torchrl/envs/async_envs.py
torchrl/envs/batched_envs.py
torchrl/envs/common.py
torchrl/envs/custom/chess.py
torchrl/envs/custom/llm.py
torchrl/envs/custom/pendulum.py
torchrl/envs/custom/tictactoeenv.py
torchrl/envs/libs/brax.py
torchrl/envs/libs/dm_control.py
torchrl/envs/libs/envpool.py
torchrl/envs/libs/gym.py
torchrl/envs/libs/isaacgym.py
torchrl/envs/libs/jumanji.py
torchrl/envs/libs/meltingpot.py
torchrl/envs/libs/openml.py
torchrl/envs/libs/openspiel.py
torchrl/envs/libs/pettingzoo.py
torchrl/envs/libs/smacv2.py
torchrl/envs/libs/unity_mlagents.py
torchrl/envs/libs/vmas.py
torchrl/envs/model_based/common.py
torchrl/envs/transforms/transforms.py
tutorials/sphinx-tutorials/pendulum.py

`_set_seed` is not expected to return anything as the sequence of seeds is handled by the parent function `set_seed`. The type annotation should make it more explicit that no return value is expected. 
I went into a rabbit hole to figure out how to handle the seeds when dealing with a pool of environments. Certain implementation of `_set_seed` were returning `seed+1` for example which was confusing. I believe the type annotation `-> None` makes it clear.

[BE] `_set_seed` returns `None` + type annotations

---

torchrl/envs/transforms/llm.py

[BugFix] Fix KL penalty

---

torchrl/envs/gym_like.py

* #2907
* #2906
* __->__ #2905

[Performance] Use TensorDict._new_unsafe in step

---

docs/source/reference/collectors.rst
docs/source/reference/data.rst

* #2921
* #2915
* #2920
* __->__ #2919
* #2918
* #2917
* #2916

[Doc] Fix Doc

---

.github/unittest/linux_sota/scripts/environment.yml
.github/unittest/linux_sota/scripts/run_all.sh
.github/unittest/linux_sota/scripts/test_sota.py
sota-implementations/a2c/a2c_atari.py
sota-implementations/a2c/config_atari.yaml
sota-implementations/a2c/utils_atari.py
sota-implementations/dqn/config_atari.yaml
sota-implementations/dqn/dqn_atari.py
sota-implementations/dqn/utils_atari.py
sota-implementations/impala/config_multi_node_ray.yaml
sota-implementations/impala/config_multi_node_submitit.yaml
sota-implementations/impala/config_single_node.yaml
sota-implementations/impala/impala_multi_node_ray.py
sota-implementations/impala/impala_multi_node_submitit.py
sota-implementations/impala/impala_single_node.py
sota-implementations/impala/utils.py
sota-implementations/ppo/config_atari.yaml
sota-implementations/ppo/ppo_atari.py
sota-implementations/ppo/utils_atari.py

* #2923
* #2922
* __->__ #2921

[CI] Fix envnames in SOTA tests

---

torchrl/data/replay_buffers/samplers.py

- [-] Bug fix (non-breaking change which fixes an issue)
- [-] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)

[Quality] Remove redundant return

---

test/test_specs.py
torchrl/data/tensor_specs.py

[BugFix] NonTensor.encode must return a NonTensorData

---

test/mocking_classes.py
test/test_env.py
torchrl/envs/batched_envs.py
torchrl/envs/common.py

[BugFix] Fix behavior or partial, nested dones in PEnv and TEnv

---

torchrl/objectives/ppo.py

[BugFix] Remove to(device) for clip_value usage as it's a buffer already

---

test/test_libs.py
torchrl/envs/libs/pettingzoo.py

Set the "state" field in `step` and `reset`.
The `PettingZooWrapper` support of (environment) state was limited to configuring the spec. This commit completes it by setting the state in `reset` and `step`.
`PettingZooWrapper` is currently not tested.

[Environment] Complete `PettingZooWrapper` state support

---

test/test_specs.py
torchrl/data/tensor_specs.py

Before this, `Binary(shape=())` would fail with
>     n = shape[-1]
>         ~~~~~^^^^
> IndexError: tuple index out of range

[BugFix] Binary can have empty shape

---

test/test_cost.py
torchrl/objectives/ppo.py

Adds **per-head entropy coefficients** to `PPOLoss`.
* `entropy_coef` now accepts  
* **scalar** (legacy behaviour) or  
* **`Mapping[str, float]`** — one coefficient per action head.
* New helper `_weighted_entropy` applies the correct weighting:
* scalar path: `-coef * entropy`
* mapping path: `-Σ coef_head * entropy_head`
* `forward()` switches from direct multiplication to `_weighted_entropy`.
* Keeps `self.entropy_coef` buffer for backward-compat (dummy `0.0` when mapping used).
* Docstrings updated.
Composite / multi-head policies often need different exploration pressure on
each sub-action (e.g. steering vs. throttle).  
This change lets users express that directly via a dict instead of patching the
loss externally.

[Feature] Adds per-head entropy coefficients to PPOLoss

---

torchrl/data/tensor_specs.py

[!2980](https://github.com/pytorch/rl/pull/2980) can break some checks like `check_env_specs` when `is_in` receives non-long values.

[BugFix] Fixes the Categorical is_in with non-long integer

---

sota-implementations/grpo/README.md
sota-implementations/grpo/config/mode/async.yaml
sota-implementations/grpo/config/mode/sync.yaml
sota-implementations/grpo/grpo-async.py
sota-implementations/grpo/grpo-sync.py
torchrl/collectors/llm/ray_collector.py

Allows to collect data from RayLLMCollector whilst running the optim loop. This can make the collection up to 2x faster, but it sets the policy age to 1 most of the time.

[Feature] RayLLMCollector.sync_iter

---

test/test_collector.py
torchrl/collectors/collectors.py
torchrl/data/llm/chat.py

[Feature] Enabling worker level control on `frames_per_batch`

---

torchrl/objectives/ppo.py

Adds an optional `log_explained_variance` flag to PPOLoss (and subclasses) so users can log the critic’s explained‑variance metric during training.
The metric helps monitor critic fit and matches `sklearn.metrics.explained_variance_score`. Also used by other libraries such as stable baselines.
- [] I have updated the tests accordingly (*required for a bug fix or a new feature*).

[Feature] Add optional Explained Variance logging

---

sota-implementations/grpo/grpo-async.py
sota-implementations/grpo/grpo-sync.py

Super minor fix. Removing some variables declared by never used in the `make_env` method in GRPO sota-example scripts.

Minor fix: remove unused variables in GRPO scripts

---

.github/workflows/benchmarks_pr.yml

The benchmark_cpu job is currently unrunnable and has been so for  over 3 months.
Changes are:
1. Disables the job from being scheduled, since it's broken.  I'm not deleting the code in case someone is interested in fixing it later on.
2. Fixes the runner label used for benchmark cpu tests to a similar machine that actually exists and has the same amount of cpu/memory, which is the first step towards fixing the job
This buggy runner label was referenced in this PR: https://github.com/pytorch/rl/pull/2930/files#diff-1d24b39978bd364a0913d34dc491f52f4cb244e1efaf28bd0d87ebb80a73e4cdR17
Since this the job has been unable to even start, let alone run. 
Go over all the following points, and put an `x` in all the boxes …

Disable unrunnable benchmarks cpu test

---

test/test_specs.py
torchrl/data/tensor_specs.py

Fixes a bug introduced by https://github.com/pytorch/rl/pull/3077 where shapes for newly instantiated `Binary` specs are incompatible with the value of `n` passed.
In particular the following pattern is used in `unsqueeze` and other shape-modifying operations:
```python
def unsqueeze(self, dim: int):
shape = _unsqueezed_shape(self.shape, dim)
return self.__class__(
n=self.shape[-1] if len(self.shape) > 0 else None,
shape=shape,
device=self.device,
dtype=self.dtype,
)
```
However, this is wrong because we should extract `n` from the new `shape` rather than from the current `self.shape`.
We fix by switching to check on the new `shape`: 
```python
def unsqueeze(self, dim: int):
shape = _unsqueezed_shape(self.shape, dim)
return self.__class__(
n=shape[-1] if len(shape) > 0 else None, …
```

[BugFix] Fix Binary reshaping

---

torchrl/modules/tensordict_module/rnn.py

This PR fixes a minor import issue in the LSTMModule docstring example.
- Add  to the import alongside  so the snippet runs as-is without raising a .
Documentation-only change.
Closes #3119

[Doc] fix LSTM example import in rnn.LSTMModule

---

torchrl/__init__.py

Fixes the wrongly appearing version in doc
https://docs.pytorch.org/rl/0.10/

[Versioning] Fix doc versioning

---

torchrl/collectors/collectors.py

Stack from [ghstack](https://github.com/ezyang/ghstack/tree/0.12.0) (oldest at bottom):
* #3173
* #3172
* #3171
* __->__ #3170
* #3169

[Feature] track_policy_version in collectors.py

---

docs/source/reference/envs.rst
docs/source/reference/trainers.rst
sota-implementations/ppo_trainer/config/config.yaml
sota-implementations/sac_trainer/config/config.yaml
sota-implementations/sac_trainer/config/config_async.yaml
sota-implementations/sac_trainer/train.py
torchrl/collectors/collectors.py
torchrl/data/replay_buffers/storages.py
torchrl/envs/transforms/transforms.py
torchrl/trainers/__init__.py
torchrl/trainers/algorithms/configs/__init__.py
torchrl/trainers/algorithms/configs/collectors.py
torchrl/trainers/algorithms/configs/data.py
torchrl/trainers/algorithms/configs/modules.py
torchrl/trainers/algorithms/configs/trainers.py
torchrl/trainers/algorithms/configs/transforms.py
torchrl/trainers/algorithms/ppo.py
torchrl/trainers/algorithms/sac.py
torchrl/trainers/trainers.py

Stack from [ghstack](https://github.com/ezyang/ghstack/tree/0.12.0) (oldest at bottom):
* __->__ #3173
* #3172
* #3171
* #3170
* #3169

[Feature] Async collection within trainers
