README.md

- Update README.md
- Update README.md
- Update README.md

CircleCI badge

---

docs/source/reference/envs.rst
test/mocking_classes.py
test/test_env.py
test/test_exploration.py
test/test_postprocs.py
test/test_shared.py
test/test_tensordict.py
torchrl/collectors/collectors.py
torchrl/collectors/utils.py
torchrl/data/postprocs/postprocs.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/tensordict/tensordict.py
torchrl/envs/common.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py
torchrl/envs/vec_env.py
torchrl/modules/models/recipes/impala.py
torchrl/modules/td_module/common.py
torchrl/modules/td_module/exploration.py
torchrl/objectives/costs/ddpg.py
torchrl/objectives/costs/dqn.py
torchrl/objectives/costs/ppo.py
torchrl/objectives/costs/redq.py
torchrl/objectives/costs/utils.py
torchrl/objectives/returns/gae.py
torchrl/record/recorder.py

Rename tensor_dict to tensordict

---

test/test_distributions.py
torchrl/modules/distributions/continuous.py

SafeTanhTransform eps as a function of input dtype

---

docs/source/reference/objectives.rst
test/test_cost.py
torchrl/agents/helpers/losses.py
torchrl/objectives/costs/ddpg.py
torchrl/objectives/costs/dqn.py
torchrl/objectives/costs/redq.py
torchrl/objectives/costs/sac.py

Closes https://github.com/facebookresearch/rl/issues/65

Unify losses that have target parameters

---

.circleci/config.yml
.circleci/unittest/linux_optdeps/scripts/environment.yml
.circleci/unittest/linux_optdeps/scripts/install.sh
.circleci/unittest/linux_optdeps/scripts/post_process.sh
.circleci/unittest/linux_optdeps/scripts/run-clang-format.py
.circleci/unittest/linux_optdeps/scripts/run_test.sh
.circleci/unittest/linux_optdeps/scripts/setup_env.sh
test/test_env.py
test/test_helpers.py
test/test_transforms.py
torchrl/envs/common.py
torchrl/envs/libs/gym.py

Implements and corrects tests to make sure that all the listed optional deps are truly optional

Test optional dependencies

---

examples/ddpg/ddpg.py
examples/dqn/dqn.py
examples/ppo/ppo.py
examples/redq/redq.py
examples/sac/sac.py

closes the env as per #97 
Long-term fix should be to close all collectors and envs upon deletion, but we should be careful with that.

Fix PPO open env

---

test/test_tensordict.py
torchrl/data/tensordict/metatensor.py
torchrl/data/tensordict/tensordict.py

@vmoens This relates to task T116921131 (issue https://github.com/facebookresearch/rl/issues/59). Thanks!

Added permute functionality to tensordict class

---

torchrl/trainers/helpers/trainers.py

Fixing trainer helper function

---

test/test_tdmodules.py
torchrl/modules/td_module/common.py

Allows TDSequence to call the last tdmodule's `get_dist` method.

Probabilistic sequence of tdmodules

---

test/test_tensordict.py
torchrl/data/tensordict/memmap.py
torchrl/data/tensordict/metatensor.py
torchrl/data/tensordict/tensordict.py

requires_grad attribute for meta tensors #96

---

examples/ddpg/ddpg.py
examples/dqn/dqn.py
examples/ppo/ppo.py
examples/redq/redq.py
examples/sac/sac.py
torchrl/envs/env_creator.py
torchrl/trainers/helpers/envs.py

Skip ParallelEnv if only one env is created in helpers

---

tutorials/envs.ipynb

Provides a tutorial on basic usage of `torchrl.envs` module
cc @alexpalms, @eugenevinitsky

`torchrl.envs` Turorial

---

test/test_tensordict.py
torchrl/data/tensordict/tensordict.py

Makes sure all tensordicts have the same shape in the test class
cc @shagunsodhani @BoboBananas

Fix tensordict test shapes

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

Rename TransformedEnv.env to base_env

---

torchrl/trainers/trainers.py

Trainer: saving trainer at the end of training

---

torchrl/__init__.py
torchrl/trainers/helpers/recorder.py
torchrl/trainers/helpers/trainers.py
torchrl/trainers/trainers.py

- init
- amend
- amend
- amend

recorder_log_keys arg: enable logging of arbitrary keys from test rollouts

---

test/test_tensordict.py
torchrl/data/tensordict/memmap.py
torchrl/data/tensordict/metatensor.py
torchrl/data/tensordict/tensordict.py
torchrl/envs/libs/gym.py

Fix MemmapTensor metadata and indexing

---

.gitignore
test/test_transforms.py

PR for reward rescale tranform tests

Added test for RewardRescale transform

---

test/test_tensordictmodules.py
torchrl/modules/tensordict_module/sequence.py

[BugFix]: avoid deleting true in_keys in TensorDictSequence

---

test/test_tensordict.py
torchrl/data/tensordict/metatensor.py

[Test]: test squeezed TensorDict

---

torchrl/data/replay_buffers/replay_buffers.py

Small tweaks to make the replay buffer code more consistent
I was reading the code and how a few places where the code could be made more consistent.
- [x ] Minor change (e.g. style related change)

Small tweaks to make the replay buffer code more consistent

---

torchrl/envs/transforms/transforms.py
torchrl/modules/tensordict_module/actors.py
torchrl/modules/tensordict_module/deprec.py
torchrl/modules/tensordict_module/probabilistic.py
torchrl/modules/tensordict_module/sequence.py

Some imports in the docstrings are broken.
Doc changes (docstrings)

[BugFix]: Minor bugs in docstrings

---

README.md
tutorials/README.md
tutorials/demo.ipynb

[Doc]: TorchRL demo

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md

Correct wrong links in issue and pull request template

[BugFix]: update wrong links in issue and pull request template

---

.circleci/unittest/linux/scripts/environment.yml
.circleci/unittest/linux_stable/scripts/environment.yml
setup.py

[BugFix]: quickfix: force gym 0.24 installation until issue with rendering is resolved

---

test/test_distributions.py
torchrl/csrc/pybind.cpp
torchrl/csrc/utils.h
torchrl/modules/distributions/continuous.py

Implements a simple C++ function to compute a safe tanh transform.
Safe-tanh takes a considerable amount of time during training. Getting this down by a bit can bring a significant training speedup.
Our new function decreases the time it takes to execute safe tanh by 30% on cpu.

[Feature]: faster safetanh transform via C++ bindings

---

.circleci/unittest/linux/scripts/environment.yml
.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/linux/scripts/setup_env.sh
.circleci/unittest/linux_stable/scripts/environment.yml
.circleci/unittest/linux_stable/scripts/install.sh
.circleci/unittest/linux_stable/scripts/setup_env.sh

The latest mujoco bindings break our CI. 
The fix consists in setting MUJOCO_GL early in the code.

[BugFix]: fix GLFW3 error when installing dm_control

---

.github/PULL_REQUEST_TEMPLATE.md

Removes a bunch of fields in the PR template.
To simplify writing PRs.

[Doc] Simplify PR template

---

test/test_rb.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/storages.py
torchrl/data/tensordict/metatensor.py
torchrl/data/tensordict/tensordict.py

Corrects a few bugs in the RB, in particular when storage is instantiated with nested tensordicts.

[BugFix]: Replay buffer bugfixes

---

test/test_env.py
torchrl/data/tensordict/tensordict.py
torchrl/envs/utils.py
torchrl/modules/distributions/continuous.py
torchrl/objectives/costs/ddpg.py
torchrl/trainers/trainers.py

Provides a few tweaks to improve training efficiency: better creation of `TensorDict` instances during `select` and `exclude`, faster `step_tensordict` etc.

[Feature]: Improving training efficiency

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Update the wrong issue link and add label for bug report and feature request automatically.

[QuickFix]: update issue and pr template

---

torchrl/objectives/costs/ddpg.py
torchrl/objectives/costs/dqn.py
torchrl/objectives/costs/redq.py
torchrl/objectives/costs/sac.py

RB priority should be computed with the L2-norm, not L1.

[BugFix]: L2-priority for PRB

---

.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/linux/scripts/setup_env.sh
.circleci/unittest/linux_optdeps/scripts/install.sh
.circleci/unittest/linux_stable/scripts/install.sh
.circleci/unittest/linux_stable/scripts/setup_env.sh
test/test_transforms.py

Conda is broken for torch, using pip instead.
Aslo using mesalib (conda-forge) instead of osmesa (menpo) as suggested by @nairbv

[WIP, BugFix]: Conda to pip for circleci

---

test/test_cost.py
torchrl/objectives/costs/utils.py
torchrl/objectives/returns/advantages.py

Fixes bugs in gradient propagation in advantage classes when higher order gradients are needed

[BugFix]: gradient propagation in advantage estimates

---

.circleci/config.yml
.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/linux_stable/scripts/install.sh

Solves the functorch installation error occuring since functorch moved to PyTorch core

[BugFix] functorch installation in CircleCI

---

torchrl/envs/transforms/transforms.py

Makes it so that `VecNorm` always tracks the running stats of an environment. If one wants not to do so, she can call `vecnorm.to_observation_norm()` and get a transform that freezes the stats to their current state.

[Refactor] VecNorm inference API

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py
torchrl/version.py

`TransformedEnv` sets by default all transforms into eval mode.
close #318.

TransformedEnv sets added Transforms into eval mode

---

torchrl/envs/common.py

[Feature] Make default rollout tensordict contiguous

---

.circleci/unittest/linux/scripts/environment.yml
.circleci/unittest/linux_stable/scripts/environment.yml
test/test_libs.py

[CI] Using latest gym

---

torchrl/data/tensordict/tensordict.py

Solves a bunch of minor bugs needed to use tensordict in functorch functional settings.

[BugFix] Functorch-Tensordict bug fixes

---

torchrl/data/tensordict/tensordict.py

Reverts facebookresearch/rl#361

Revert "[BugFix] Functorch-Tensordict bug fixes"

---

test/test_cost.py
torchrl/objectives/returns/functional.py

This PR adds support for tensor-based decay to the vectorised TD-lambda objective function. I've added tests as suggested in the linked issue (#355).
There is one area which I will mark with an inline comment that needs careful checking as I'm not 100% sure I haven't misunderstood.
Fixes #355 

[Feature] Support tensor-based decay in TD-lambda

---

.circleci/unittest/linux/scripts/environment.yml
.circleci/unittest/linux_stable/scripts/environment.yml
examples/ddpg/ddpg.py
examples/dqn/dqn.py
examples/ppo/ppo.py
examples/redq/redq.py
examples/sac/sac.py
test/test_loggers.py
torchrl/trainers/helpers/__init__.py
torchrl/trainers/helpers/logger.py
torchrl/trainers/loggers/common.py
torchrl/trainers/loggers/csv.py
torchrl/trainers/loggers/tensorboard.py
torchrl/trainers/loggers/wandb.py

- Implements a CSVLogger, which requires no additional package
- Implements tests for loggers. Missing:

[Feature] CSVLogger

---

test/test_transforms.py
torchrl/data/tensor_specs.py
torchrl/envs/transforms/r3m.py
torchrl/envs/transforms/transforms.py
torchrl/trainers/trainers.py

Allows for a multi-image usage of R3M

[Feature] Multi-images R3M

---

test/test_transforms.py
torchrl/envs/transforms/r3m.py
torchrl/envs/transforms/transforms.py

Implements a flattening of the R3M output when multiple images are passed, as well as unsqueezing when required

[Feature] Flatten multi-images in R3M

---

.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/linux_optdeps/scripts/install.sh
.circleci/unittest/linux_stable/scripts/install.sh
packaging/build_wheels.sh
test/test_cost.py
test/test_exploration.py
test/test_functorch.py
test/test_helpers.py
test/test_transforms.py
torchrl/collectors/collectors.py
torchrl/data/tensor_specs.py
torchrl/data/tensordict/memmap.py
torchrl/data/tensordict/tensordict.py
torchrl/envs/common.py
torchrl/envs/gym_like.py
torchrl/envs/libs/dm_control.py
torchrl/envs/vec_env.py
torchrl/trainers/helpers/envs.py
torchrl/trainers/helpers/replay_buffer.py
torchrl/trainers/trainers.py

[Quality] Code cleanup for fbsync

---

.gitmodules

We don't have use for submodules anymore, removing them.

[BugFix] Remove submodules

---

.circleci/unittest/linux/scripts/environment.yml
.circleci/unittest/linux_stable/scripts/environment.yml

[Feature] Switch back to latest gym

---

test/test_trainer.py
torchrl/trainers/helpers/envs.py

Make image size a parameter in cfg
This changes allows to easily change image size resizing

[Features] Make image_size a cfg param

---

torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/tensordict/tensordict.py

We still have a couple of wrong calls to `tensordict.device` in the code. Moving to `device_safe`.

[BugFix] mixed device_safe vs device

---

test/test_loggers.py
torchrl/trainers/loggers/csv.py
torchrl/trainers/loggers/tensorboard.py
torchrl/trainers/loggers/wandb.py

https://github.com/facebookresearch/rl/issues/396
Added the tests for the log_video methods in Tensorboard, CSVLogger and WandbLogger.
Fixes an open issue, #396 

[Tests] Test loggers video saving

---

README.md
test/test_exploration.py
test/test_functorch.py
test/test_tensordictmodules.py
torchrl/modules/models/exploration.py
torchrl/modules/tensordict_module/actors.py
torchrl/modules/tensordict_module/sequence.py
torchrl/trainers/helpers/models.py
tutorials/demo.ipynb
tutorials/multi_task.ipynb
tutorials/tensordictmodule.ipynb

The TensorDictSequence class behaves like the nn.Sequential module, hence those names should match.
Closes #420 

[Refactor] Rename TensorDictSequence to TensorDictSequential

---

test/test_exploration.py
torchrl/modules/tensordict_module/exploration.py

Fix additive noise and tests like in #441
This change is required because additive noise wasn't doing what it was supposed to do, it never called _add_noise on actions.

[BugFix]: Fix additive noise

---

test/test_exploration.py

Fixes a test that was skipped in `test_exploration.py` following #447

[BugFix] Fix AdditiveGaussian exploration tests

---

torchrl/envs/common.py

Needed for #456
Cc @nicolas-dufour

[Feature] Allow for actions and rewards to be in the reset tensordict

---

knowledge_base/README.md
knowledge_base/RESOURCES.md

Adds a Readme to the knowledge base

[Doc] Readme for knowledge base

---

torchrl/envs/transforms/r3m.py
torchrl/envs/transforms/transforms.py

[BugFix] deepcopy specs before transforming

---

.circleci/unittest/linux/scripts/environment.yml
.circleci/unittest/linux_stable/scripts/environment.yml
examples/ddpg/ddpg.py
examples/dqn/dqn.py
examples/ppo/ppo.py
examples/redq/redq.py
examples/sac/sac.py
test/test_loggers.py
torchrl/trainers/loggers/mlflow.py

This diff enables torchrl to seamlessly use the MLFlow Tracking API through its internal `Logger` API. These changes are consistent with previous integrations such as the one with W&B.
A test suite for the new integration has been included in the diff.
close #395

[Logging]: implement MLFlow logging integration

---

torchrl/trainers/loggers/mlflow.py

The `MLFlow` script imports torchvision but this is an optional dependency.

[BugFix] MLFlow import fix

---

torchrl/trainers/trainers.py

[Feature] make ReplayBufferTrainer compatible with storing trajectories

---

torchrl/data/tensor_specs.py
torchrl/envs/common.py
torchrl/envs/gym_like.py

Introduces obs, action, done and reward reader hooks for gym-like environments

[Feature] reader hooks for GymLike

---

torchrl/data/tensor_specs.py

[BugFix] TensorSpec.zero(None) failure fix

---

torchrl/data/tensordict/tensordict.py

[BugFix] functorch _C import

---

torchrl/__init__.py

Adds an `erase()` function to `torchrl.timeit`.

[Feature]: `erase()` method for `torchrl.timeit`

---

test/test_modules.py
torchrl/data/tensordict/tensordict.py
torchrl/modules/planners/cem.py

[BugFix] removing unwanted device_safe()

---

torchrl/trainers/helpers/envs.py

Refactored get_stats_random_rollout to make it more efficient.

[Refactoring] Refactored get_stats_random_rollout

---

test/mocking_classes.py
test/test_collector.py
torchrl/collectors/collectors.py
torchrl/envs/transforms/r3m.py
torchrl/envs/transforms/transforms.py
torchrl/envs/vec_env.py

Allows collectors and batched environments to run steps when sub-envs are done.

[Feature] Optional auto-reset when done for collectors and batched envs

---

examples/configs/config.yaml
examples/configs/replay_buffer/circular.yaml
examples/configs/replay_buffer/prioritized.yaml
test/test_configs.py

Introduces config files for replay buffers

Structured configs for replay buffer

---

test/test_collector.py
torchrl/collectors/collectors.py

Reverts facebookresearch/rl#477

Revert "[BugFix] Defaulting `passing_devices` to `None`"

---

.github/workflows/wheels.yml
README.md

[Cleanup] Removing cuda 10.2 references

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
setup.py
torchrl/data/replay_buffers/storages.py
torchrl/data/tensor_specs.py
torchrl/envs/gym_like.py
torchrl/envs/transforms/r3m.py
torchrl/envs/transforms/vip.py
torchrl/modules/distributions/utils.py
torchrl/modules/functional_modules.py
torchrl/modules/tensordict_module/deprec.py
tutorials/coding_ddpg.ipynb
tutorials/coding_dqn.ipynb
tutorials/demo.ipynb
tutorials/envs.ipynb
tutorials/multi_task.ipynb
tutorials/tensordict.ipynb
tutorials/tensordictmodule.ipynb

changes the facebookresearch refs into pytorch

[BugFix] Migration to pytorch org

---

torchrl/modules/tensordict_module/sequence.py

Solves minor bugs in TensorDictSequential
- Compatibility with modules that don't inherit from `TenssorDictModule`
- Indexing with lists and slices

[BugFix] Minor bugfixes in TensorDictSequential

---

.circleci/config.yml

[BugFix] python version for linting checks

---

setup.cfg
torchrl/trainers/helpers/envs.py

[Lint] re-instantiate F821

---

torchrl/envs/common.py
torchrl/envs/transforms/transforms.py

Sets `run_type_checks` to be equal to the base_env in `TransformedEnv`

[BugFix] run_type_checks for TransformedEnvs

---

torchrl/envs/transforms/transforms.py
torchrl/trainers/helpers/envs.py

[BugFix] making first_dim and last_dim negative in FlattenObservation when a parent is set

---

.github/workflows/nightly_build.yml
README.md
setup.py

Introduces a nightly release workflow in github actions

[Feature] Nightly release

---

tutorials/coding_dqn.ipynb

[BugFix] Fix colab link of coding_dqn.ipynb

---

test/test_trainer.py
torchrl/trainers/trainers.py

Implements and tests RewardNorm checkpointing

[Feature] checkpointing RewardNormalization

---

test/test_trainer.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/storages.py
torchrl/data/tensordict/memmap.py
torchrl/trainers/trainers.py

[Feature] checkpointing ReplayBuffer

---

test/test_trainer.py
torchrl/trainers/trainers.py

[Feature] checkpointing SubSampler

---

torchrl/data/tensordict/utils.py

[BugFix] Fix ellipsis indexing of 2d TensorDicts

---

torchrl/trainers/loggers/wandb.py

Temporarily disables the step functionality of wandb video logger

[BugFix] Disabling video step for wandb

---

examples/qmix/networks.py

Fetching the architectures from QMIX by copy/pasting the pymarl framework and removing the use of configuration dictionnaries.
First step of QMIX implementation

Qmix networks

---

README.md

[Doc] Banners on README.md

---

torchrl/trainers/trainers.py

Add `eps` to the reward normalization hook to avoid exploding values.

[BugFix] Add eps to reward normalization

---

torchrl/objectives/costs/ppo.py

[BugFix] Fix argument for PPOLoss.get_entropy_bonus()

---

test/test_tensordict.py

Fixes a wrongful import in the tests

[BugFix] Wrong stack import in tests

---

docs/source/reference/data.rst
torchrl/data/replay_buffers/__init__.py

[Doc] Missing doc for prototype RB

---

torchrl/envs/utils.py

Updates the list of supported libraries in the envs utils.

[Feature] Update list of supported libraries

---

test/test_helpers.py
torchrl/_utils.py

[BugFix] Fix timeit count registration

---

tutorials/tensordict.ipynb

Typos in tensordict tutorial

---

README.md

[Doc] Correct M1 instructions

---

docs/requirements.txt
docs/source/conf.py

Updating docs requirements to solve #623 conflicts.
cc @hatala91

[Doc] Updating docs requirements

---

test/test_memmap.py
test/test_rb.py
test/test_shared.py
torchrl/data/tensordict/memmap.py

Creates sub-memmap tensors as memmap tensors with an index.
cc @adityagoel4512

[Feature] Sub-memmap tensors

---

test/test_tensor_spec.py
torchrl/data/tensor_specs.py

Implements nested keys and nested composite spec constructor

[Feature] Nested composite spec

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py
torchrl/envs/transforms/vip.py

Implements the reward transform for VIP.

[Feature] VIPRewardTransform

---

examples/ppo/ppo.py

In the PPO code example, there is a broken import of the GAE class
The example does not run out-of-the-box because of this broken import

[BugFix] PPO example GAE import

---

test/test_rb.py
torchrl/collectors/collectors.py
torchrl/envs/vec_env.py
torchrl/modules/models/model_based.py

This [PR](https://github.com/pytorch-labs/tensordict) on tensordict broken multiple usages of `tensordict.select` in TorchRL. This PR fixes them.

[BugFix] Update to strict select

---

docs/source/reference/envs.rst

More doc about env creation and usage.

[Doc] More doc about environments

---

test/test_rb.py
test/test_trainer.py
torchrl/data/replay_buffers/rb_prototype.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/storages.py

[Feature] Default collate_fn

---

test/test_cost.py

Fix wrong error message when functorch is installed in `test_costs.py`

[Test] Fix wrong skip message when functorch is installed

---

docs/source/conf.py
tutorials/sphinx-tutorials/coding_dqn.py
tutorials/sphinx-tutorials/tensordict_tutorial.py
tutorials/sphinx-tutorials/torchrl_demo.py

[Doc] Fix Tutos TODOs

---

tutorials/sphinx-tutorials/coding_ddpg.py
tutorials/sphinx-tutorials/coding_dqn.py
tutorials/sphinx-tutorials/multi_task.py
tutorials/sphinx-tutorials/tensordict_module.py

Fixes tutos now that modules are hosted by tensordict

[BugFix] Fix tutos

---

test/test_collector.py
torchrl/collectors/collectors.py
tutorials/sphinx-tutorials/coding_ddpg.py
tutorials/sphinx-tutorials/coding_dqn.py
tutorials/sphinx-tutorials/multi_task.py
tutorials/sphinx-tutorials/tensordict_module.py
tutorials/sphinx-tutorials/tensordict_tutorial.py
tutorials/sphinx-tutorials/torch_envs.py
tutorials/sphinx-tutorials/torchrl_demo.py

Fixes bugs in the torchrl canonical tutorial, due to the functional refactoring and the module dependency shift to tensordict.

[BugFix] Fix TorchRL demo tutorial

---

README.md

Adds a `Documentation` section in the readme.
cc @giadefa

[Doc] Link to doc in README

---

torchrl/collectors/collectors.py
torchrl/collectors/utils.py

Corrects the memory managements of data collectors in various places.

[BugFix] Better memory management for collectors

---

torchrl/envs/common.py

Revert "Minor cleaning in BaseEnv classes"

---

.github/workflows/docs.yml

Fixes the error appearing at the end of the doc builts:
```
error: [Errno 2] No such file or directory: 'cmake'
[end of output]
```

[BugFix] Doc built cmake error

---

docs/source/index.rst

Creates a "knowledge base" dedicates section in the doc

[Doc] Knowledge base section

---

test/test_transforms.py

[Format] Fix lint

---

tutorials/sphinx-tutorials/coding_dqn.py
tutorials/sphinx-tutorials/torchrl_demo.py

Fixes a couple of errors in the tutos

[Doc, BugFix] Fix tutos errors

---

tutorials/sphinx-tutorials/pretrained_models.py

Adds an example on how to use R3M on a replay buffer for offline RL applications.

[Doc] Using R3M with a replay buffer

---

.circleci/config.yml
.circleci/unittest/windows_optdepts/scripts/environment.yml
.circleci/unittest/windows_optdepts/scripts/install.sh
.circleci/unittest/windows_optdepts/scripts/install_conda.bat
.circleci/unittest/windows_optdepts/scripts/post_process.sh
.circleci/unittest/windows_optdepts/scripts/run_test.sh
.circleci/unittest/windows_optdepts/scripts/set_cuda_envs.sh
.circleci/unittest/windows_optdepts/scripts/setup_env.sh
.circleci/unittest/windows_optdepts/scripts/vc_env_helper.bat
packaging/windows/internal/driver_update.bat
test/test_collector.py
test/test_helpers.py
test/test_rb.py
test/test_rb_distributed.py
test/test_shared.py
torchrl/data/tensor_specs.py

- Add `unittest_windows_optdepts_cpu` workflow for `python_version=3.7, 3.8, 3.9, 3.10` and 
- Add `unittest_windows_optdepts_gpu` workflow for `python_version=3.7, 3.8, 3.9, 3.10` and `cuda=116` (workflows are not run for `cuda=117` [as done in the Torchvision repo](https://github.com/pytorch/vision/blob/35f68a09f94b2d7afb3f6adc2ba850216413f28e/.circleci/config.yml#L1496))
**Some unit tests are set to be skipped on Windows**:
- `test/test_rb_distributed.py::test_funcs`: `torch.distributed.rpc` support is unstable for Windows
- `test/test_rb.py:: TestPrototypeBuffers::{test_add,test_extend,test_sample,test_index}` with `rb_type= RemoteTensorDictReplayBuffer`: `torch.distributed.rpc` support is unstable for Windows 
- `test_timeit.py` is taking more time than allowed on Windows: …

[CI] Add unit test workflows for Windows

---

pyproject.toml

[Minor] Add ninja to deps in toml file

---

README.md

Small change to make @robandpdx a contributor
This will help @robandpdx develop workflows in GitHub Actions.

small change to make @robandpdx a contributor

---

knowledge_base/RESOURCES.md

Adds "A Succinct Summary of Reinforcement Learning" to the KB

[Doc] A Succinct Summary of Reinforcement Learning

---

torchrl/collectors/collectors.py

[BugFix] Improve done checking of collectors

---

test/test_shared.py
torchrl/collectors/utils.py
torchrl/envs/common.py

Sync with https://github.com/pytorch-labs/tensordict/pull/168

[BugFix] Sync with tensordict (meta-tensor deprecation)

---

torchrl/modules/models/model_based.py

Just a small typo fix of the dreamer link
Original https://arxiv.org/abs/1912.016034 doesn't exist it is https://arxiv.org/abs/1912.01603
Original https://arxiv.org/abs/1912.016034 doesn't exist it is https://arxiv.org/abs/1912.01603
- [x ] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)

Fix broken link Dreamer

---

torchrl/envs/transforms/transforms.py

Fixes the loading of uninitialized catframes buffers

[BugFix] Loading state_dict on uninitialized CatFrames

---

test/test_cost.py
test/test_shared.py
torchrl/objectives/value/functional.py
torchrl/objectives/value/utils.py

Refactors the advantages for situations where two trajectories follow each other, eg `done=[0, 0, 1, 0, 0]`

[Feature] Refactor advantages for continuous batches

---

torchrl/objectives/ppo.py
torchrl/objectives/value/advantages.py

Makes it possible to normalize the advantage in the PPO loss.

[Feature] PPO advantage normalization

---

torchrl/envs/common.py
torchrl/envs/gym_like.py

[Refactor] Minor refactorings to envs

---

torchrl/objectives/ppo.py

Turns off the advantage normalization in PPO

[Refactor] Turn off default advantage normalization in PPO

---

.circleci/unittest/linux_libs/scripts_habitat/run_test.sh
.circleci/unittest/linux_libs/scripts_habitat/setup_env.sh
torchrl/envs/libs/habitat.py

[CI] Fix habitat-gym imports

---

.circleci/config.yml

[CI] Fix cuda versions

---

.circleci/config.yml
.circleci/unittest/windows_optdepts/scripts/install.sh

Fixes the failing windows installs

[CI] Fix windows install

---

.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/linux/scripts/setup_env.sh
.github/workflows/test-linux-cpu.yml
.github/workflows/test-macos-cpu.yml

Migrate unit tests from CircleCI to GitHub Actions. This change is stacked on top of https://github.com/pytorch/rl/pull/826. 
Passing workflow run:
https://github.com/pytorch/rl/actions/runs/4059585438
The direction is to move unit tests to GitHub Actions.
No change to functionality.

MacOS CPU unit test workflow using GitHub Actions

---

.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/linux/scripts/setup_env.sh
.github/workflows/test-linux-cpu.yml
.github/workflows/test-linux-gpu.yml

Migrate unit tests from CircleCI to GitHub Actions. This change is stacked on top of #826. The GPU unit tests fail, and I am not able to get them to work. [Here is a gist](https://gist.github.com/robandpdx/aad10f5fde67bf0998e30c08a4ef2bdc) showing how I am testing the workflow and how to recreate the failure so you can fix it.
The direction is to move unit tests to GitHub Actions.
No change to functionality.

[WIP] Linux GPU unit test workflow using GitHub Actions

---

.github/workflows/docs.yml

[BugFix] Deploy doc

---

.github/workflows/docs.yml

Runs the doc build on cpu as a quick fix of gpu machines non working with docker

[BugFix] Nvidia not found fix

---

test/test_specs.py
torchrl/data/tensor_specs.py
torchrl/envs/vec_env.py

Fix issue #929 by simply replacing `_to_numpy` with `to_numpy` and add unit tests.

[BugFix] Fix CompositeSpec.to_numpy method

---

.github/workflows/nightly_build.yml

Prevents the nightly built to be triggered for forked repos

[CI] Do not run nightly workflows on forked repos

---

test/mocking_classes.py
test/test_collector.py
torchrl/collectors/collectors.py

[BugFix] Step and maybe reset

---

docs/source/reference/envs.rst

Some very minor doc improvements

[Doc] Minor doc improvements

---

test/test_rb.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/storages.py

Refactors the replay buffer constructors and solves state_dict bugs

[Quality] RB constuctors cleanup

---

torchrl/envs/transforms/transforms.py

Upgrade vision's resize import

[BugFix] Upgrade vision's functional import

---

torchrl/collectors/collectors.py
torchrl/envs/common.py
torchrl/envs/libs/vmas.py
torchrl/envs/transforms/transforms.py
torchrl/objectives/value/advantages.py

[BugFix] Upgrade tensordict deps

---

test/test_specs.py
torchrl/collectors/collectors.py
torchrl/data/tensor_specs.py
torchrl/envs/common.py
torchrl/envs/gym_like.py
torchrl/envs/libs/gym.py
torchrl/envs/transforms/r3m.py
torchrl/envs/transforms/transforms.py
torchrl/envs/transforms/vip.py
torchrl/envs/utils.py
torchrl/envs/vec_env.py
torchrl/modules/planners/common.py
torchrl/modules/tensordict_module/common.py
torchrl/modules/tensordict_module/probabilistic.py
torchrl/trainers/helpers/envs.py

Refactors the call to `CompositeSpec.keys` to match `TensorDict`'s

[Refactor] Refactor composite spec keys to match tensordict

---

torchrl/data/tensor_specs.py

Upgrades and cleans up lazy stacks of specs

[Upgrading] Stack specs

---

docs/source/reference/envs.rst
test/mocking_classes.py
test/test_collector.py
test/test_transforms.py
torchrl/envs/__init__.py
torchrl/envs/common.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

Introduces an `InitTracker` transform following suggestion from https://github.com/pytorch/rl/issues/937#issuecomment-1454675720

[Feature] InitTracker transform

---

docs/source/reference/envs.rst
test/test_transforms.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

Introduces the RenameTransform.

[Feature] RenameTransform

---

test/test_rb.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/samplers.py

[Feature, Refactor] Iterable replay buffers

---

README.md
torchrl/data/replay_buffers/__init__.py

[Doc] README rewrite

---

test/test_libs.py
torchrl/collectors/collectors.py
torchrl/envs/libs/vmas.py

Vmas api has gone through a small change.
This PR takes care of that and introduces some small efficiency boosts using new vmas features

[BugFix] VMAS api fix

---

.circleci/config.yml
.circleci/unittest/linux_libs/scripts_d4rl/run_test.sh
knowledge_base/MUJOCO_INSTALLATION.md
setup.py
test/test_libs.py
torchrl/data/datasets/d4rl.py

[CI] Fix D4RL tests in CI

---

test/test_collector.py
torchrl/collectors/collectors.py
torchrl/objectives/sac.py

[BugFix] Quickfix

---

tutorials/sphinx-tutorials/coding_ppo.py

[BugFix] Fix sampling in PPO tutorial

---

test/test_rb.py

Fixes bug on GPU machines from #1008

[BugFix] Patch tests in 1008

---

test/test_cost.py
torchrl/collectors/collectors.py
torchrl/objectives/value/advantages.py
torchrl/objectives/value/functional.py
torchrl/objectives/value/utils.py

Multidimensional value function.

[Feature] Multidim value functions

---

torchrl/modules/distributions/continuous.py
torchrl/modules/distributions/utils.py

Attempt to make faster distributions

[Refactor] Faster transformed distributions

---

torchrl/collectors/collectors.py

Remove avoidable clones and tensor instantiations in collector

Improve collector performance

---

test/test_collector.py
torchrl/collectors/collectors.py

[BugFix] Fix params and buffer casting for policies

---

torchrl/data/tensor_specs.py
torchrl/objectives/sac.py

Minor changes for compatibility with https://github.com/pytorch-labs/tensordict/pull/321

[Refactor] Minor changes in tensordict construction

---

benchmarks/test_objectives_benchmarks.py

Fix done in advantage benchmark

[Benchmark] Fix adv benchmark

---

torchrl/collectors/distributed/generic.py
torchrl/collectors/distributed/rpc.py
torchrl/collectors/distributed/sync.py

Fix the slurm kwargs update in distributed collectors

[BugFix] kwargs update in distributed collectors

---

docs/source/reference/envs.rst
test/test_env.py
torchrl/envs/utils.py

Introduces `make_composite_from_td` to create specs from empirical data

[Feature] `make_composite_from_td`

---

torchrl/collectors/collectors.py

[Minor] Fix a typo

---

test/test_cost.py
torchrl/objectives/ppo.py

@albertbou92 should be useful for you
@apbard

[Feature] Deduplicate calls to common layers in PPO

---

torchrl/collectors/collectors.py

[Refactor] resetting envs in collectors always passes the _reset entry

---

knowledge_base/MUJOCO_INSTALLATION.md

I fixed a indented/intendedtypo.
There was a typo.

MUJOCO_INSTALLATION.md: Fix typo

---

test/test_collector.py
test/test_env.py
test/test_helpers.py
test/test_libs.py
test/test_transforms.py
torchrl/envs/common.py
torchrl/envs/utils.py
torchrl/modules/planners/cem.py
torchrl/modules/planners/mppi.py
torchrl/modules/tensordict_module/sequence.py

Removes "reward" key from root tensordicts.
Closes #990

[Refactor] Removes "reward" from root tensordicts

---

.circleci/config.yml

This removes jobs that were migrated as part of #886, this PR finally removes it

[CI] Remove migrated CircleCI macOS jobs

---

.circleci/unittest/linux/scripts/environment.yml
.circleci/unittest/linux_distributed/scripts/environment.yml
.circleci/unittest/linux_examples/scripts/environment.yml
.circleci/unittest/linux_stable/scripts/environment.yml

Temporary fix on tensorboard log_video issue

[Test] Fix tensorboard tests with ImageIO 2.26

---

test/test_cost.py
torchrl/objectives/common.py
torchrl/objectives/utils.py

[BugFix] Remove false warnings in losses

---

.circleci/unittest/linux_libs/scripts_habitat/environment.yml

It fixes the failure of the circleci habitat test
It fixes the failure of the circleci habitat test

Added the entry for skip-tests in the environment.yml

---

.circleci/unittest/windows_optdepts/scripts/environment.yml
.circleci/unittest/windows_optdepts/scripts/setup_env.sh

Changes on conda environment for windows machines since latest version is causing an issue.
Unit tests on windows machines are failing due to issues

Fix in windows unit test

---

.circleci/unittest/windows_optdepts/scripts/environment.yml
.circleci/unittest/windows_optdepts/scripts/setup_env.sh

Revert "Fix in windows unit test"

---

.github/workflows/lint.yml

Creating a lint job on GHA via Nova. If this runs well for some time, we can deprecate the old CircleCI job.

[Nova] Lint job on GHA

---

torchrl/objectives/ppo.py

- fix bug: issue #1097
- Update ppo.py, parameter doc

[BugFix] Instruct the value key to PPOLoss

---

torchrl/envs/libs/vmas.py

Performs a vectorized reset in vmas when possible instead of a per env reset

[Performance] Vmas vectorized reset

---

.circleci/unittest/linux_libs/scripts_gym/setup_env.sh
.github/workflows/test-linux-gym.yml

Linux Gym Unittests
Job passing link: https://github.com/pytorch/rl/actions/runs/4996184458/jobs/8949048472?pr=1139

Linux Gym Unittests to GHA

---

.circleci/config.yml

Already moved these to GHA. We can now remove them from CCI.

Removing CircleCI Gym Unittests

---

torchrl/objectives/sac.py

[BugFix] Fix SAC

---

test/test_transforms.py
torchrl/data/__init__.py
torchrl/data/replay_buffers/__init__.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/utils.py
torchrl/data/replay_buffers/writers.py

Fixing the issue mentioned in #1163 

[BugFix] Fix KeyError in inverse transform replay buffer

---

test/test_modules.py
torchrl/modules/distributions/continuous.py
torchrl/modules/distributions/utils.py

[BugFix] Fix tanh/atanh vmap compatibility

---

docs/source/reference/modules.rst
test/test_modules.py
torchrl/modules/__init__.py
torchrl/modules/tensordict_module/__init__.py
torchrl/modules/tensordict_module/actors.py

[Feature] TanhModule

---

.circleci/unittest/linux_examples/scripts/run_test.sh
test/test_cost.py
torchrl/objectives/common.py
torchrl/objectives/td3.py

[BugFix] Fix TD3 inplace updates

---

test/test_cost.py
torchrl/objectives/iql.py

Enable dispatching arguments for the `.forward()` method of the IQL loss module.

[Feature] Distpatch IQL loss module

---

test/test_rb.py
torchrl/data/replay_buffers/replay_buffers.py
torchrl/data/replay_buffers/samplers.py
torchrl/data/replay_buffers/storages.py
torchrl/data/replay_buffers/writers.py

[Feature] ReplayBuffer.empty

---

docs/source/index.rst
knowledge_base/RESOURCES.md

[Doc] Add paper refs in doc and KB

---

test/test_cost.py
torchrl/objectives/sac.py

Enable dispatching arguments for the `.forward()` method of the SAC loss module.

[Feature] Dispatch SAC loss module

---

test/test_cost.py
torchrl/objectives/a2c.py
torchrl/objectives/common.py
torchrl/objectives/ddpg.py
torchrl/objectives/iql.py
torchrl/objectives/sac.py

Depends on https://github.com/pytorch-labs/tensordict/pull/409
cc @Blonck

[Feature] Make losses inherit from TDMBase

---

test/test_cost.py
torchrl/objectives/ddpg.py
torchrl/objectives/iql.py
torchrl/objectives/sac.py

Enable dispatching arguments for the `.forward()` method of the DiscreteSAC loss module.

[Feature] Dispatch DiscreteSAC loss module

---

test/test_cost.py
torchrl/objectives/redq.py

Enable dispatching arguments for the `.forward()` method of the REDQ loss module.

[Feature] Dispatch REDQ loss module

---

test/test_cost.py
torchrl/objectives/reinforce.py

Enable dispatching arguments for the `.forward()` method of the Reinforce loss module.

[Feature] Dispatch reinforce loss module

---

test/test_cost.py
torchrl/objectives/td3.py

Enable dispatching arguments for the `.forward()` method of the TD3 loss module.

[Feature] Dispatch TD3 loss module

---

test/test_cost.py
torchrl/objectives/value/advantages.py

Revert "[Feature] Single call to value network in advantages"

---

.github/workflows/test-linux-jumanji.yml

Passing job: https://github.com/pytorch/rl/actions/runs/5272695639/jobs/9535264579?pr=1282

[Nova] Jumanji Tests to GHA

---

test/test_cost.py
torchrl/objectives/dqn.py

Dispatch of `.forward` of the DQN loss module respects configured tensordict keys.
Solves #1274 

[BugFix] DQN loss dispatch respect configured tensordict keys

---

.github/workflows/test-linux-d4rl.yml

Passing Job: https://github.com/pytorch/rl/actions/runs/5293000361/jobs/9580569149?pr=1293

d4rl Test to Nova

---

.github/workflows/test-linux-optdeps.yml

Passing Job: https://github.com/pytorch/rl/actions/runs/5283269694/jobs/9559292586?pr=1290

OptDeps Tests to Nova

---

README.md

[Doc] Add link to paper in readme

---

setup.py

Fixes #1297 
cc @skandermoalla

[CI] Fix nightly build dependency on tensordict

---

.circleci/unittest/linux_libs/scripts_brax/install.sh
.circleci/unittest/linux_libs/scripts_brax/run_all.sh
.circleci/unittest/linux_libs/scripts_brax/run_test.sh
.circleci/unittest/linux_libs/scripts_brax/setup_env.sh
.github/workflows/test-linux-brax.yml
torchrl/envs/libs/brax.py

Moving Linux Brax Unittests to Nova. 
Job is passing: https://github.com/pytorch/rl/actions/runs/5094108150/jobs/9157530612?pr=1133

Linux GPU Brax Unittests

---

setup.py

Follow-up to #1300. They were swapped.

[BugFix] Fix nightly tensordict dependency

---

tutorials/sphinx-tutorials/coding_ppo.py

This PR includes corrections of several typos and a minor rephrasing in the PPO tutorial.
The motivation for this change is to improve the readability and clarity of the PPO tutorial. It addresses some minor spelling errors and rephrases sentences to enhance comprehension. This doesn't fix an open issue but contributes to the overall quality of the tutorial content.

[Doc] fixed typos in ppo tutorial

---

torchrl/modules/models/exploration.py

[Doc] Fix exploration modules docstrings

---

torchrl/collectors/collectors.py
torchrl/envs/utils.py
torchrl/envs/vec_env.py

[Refactor,Performance] Faster collectors

---

torchrl/collectors/collectors.py
torchrl/envs/utils.py
torchrl/envs/vec_env.py

Revert "[Refactor,Performance] Faster collectors"

---

test/test_rlhf.py
torchrl/modules/models/rlhf.py

See https://github.com/pytorch/rl/pull/1315 for discussion

[Feature] RLHF Reward Model (reopened)

---

test/test_env.py
torchrl/envs/utils.py

Fixes #1333 with solution 1
[WIP] compatibility with nested keys

[BugFix] Fix `step_mdp()`

---

.github/workflows/benchmarks.yml
benchmarks/test_collectors_benchmark.py
benchmarks/test_envs_benchmark.py
benchmarks/test_replaybuffer_benchmark.py
torchrl/envs/libs/dm_control.py

[Benchmark] Improve benchmark precision + step_mdp + fix GPU

---

test/test_actors.py
test/test_cost.py
torchrl/modules/tensordict_module/actors.py
torchrl/modules/utils/utils.py

[BugFix] QValue modules and nested action

---

.circleci/config.yml
.circleci/unittest/linux/scripts/10_nvidia.json
.circleci/unittest/linux/scripts/environment.yml
.circleci/unittest/linux/scripts/run_all.sh
.circleci/unittest/linux/scripts/setup_env.sh
.circleci/unittest/linux_libs/scripts_gym/batch_scripts.sh
.circleci/unittest/linux_libs/scripts_gym/install.sh
.github/workflows/test-linux-cpu.yml
.github/workflows/test-linux-gpu.yml
.github/workflows/test-macos-cpu.yml
test/test_loggers.py

[CI] Fix GHA gpu tests

---

test/test_tensordictmodules.py
torchrl/_utils.py
torchrl/data/tensor_specs.py
torchrl/envs/transforms/rlhf.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py
torchrl/envs/vec_env.py
torchrl/modules/tensordict_module/common.py
torchrl/modules/tensordict_module/probabilistic.py
torchrl/modules/tensordict_module/rnn.py

[Refactor] Follow-up on tensordict PR 473

---

test/test_libs.py
test/test_transforms.py
torchrl/envs/libs/vmas.py
torchrl/envs/transforms/transforms.py

According to all the changes in the lib for multiagent, here is the new version of vmas using nested keys.
Done is not nested as it is shared by all.
All the other specs are nested

[Refactor] Vmas nested

---

torchrl/envs/utils.py
torchrl/envs/vec_env.py
torchrl/objectives/common.py

[Refactor] Remove private calls to _set

---

.circleci/unittest/linux/scripts/run_all.sh
.circleci/unittest/linux/scripts/run_test.sh

Runs the distributed tests as part of the Linux CPU/GPU jobs. Confirmed the distributed tests are passing. Failing tests seen on this PR for the Linux jobs are also failing on master.

[CI] Merge Distributed and Linux GPU job

---

torchrl/envs/utils.py

[Refactor] Remove pkg_resources import

---

torchrl/collectors/collectors.py

[Doc] Fix doctest examples

---

docs/requirements.txt

The vmas dep was missing in the docs requirement

[CI] Fix tuto deps

---

torchrl/envs/libs/vmas.py

VMAS has recently introduced the possibility of agents having dicts of tensors as observations (reminds me of a certain class...) https://github.com/proroklab/VectorizedMultiAgentSimulator/pull/49
this pr is a simple change to allow them to be converted to that certain class

[Feature] VMAS obs dict

---

test/test_transforms.py
torchrl/envs/transforms/rlhf.py

[BugFix] Fix KLTransform execution with LSTM

---

torchrl/envs/libs/gym.py
torchrl/envs/libs/vmas.py

[Feature] Optional mapping of "state" in gym specs

---

test/mocking_classes.py
test/test_env.py
test/test_libs.py
test/test_specs.py
torchrl/data/tensor_specs.py
torchrl/envs/libs/gym.py
torchrl/envs/transforms/transforms.py

Makes sure that one-hot and categorical work ok when a gym env expects an integer.

[BugFix] Fix Gym Categorical/One-hot issues

---

tutorials/sphinx-tutorials/coding_ppo.py

fix typo in coding_ppo tutorial
minor typo fix
maintenance

[Doc] Update coding_ppo.py

---

torchrl/data/replay_buffers/replay_buffers.py

Added the flexibility to use a nested key in the replay buffer for priority

[BugFix] Nested key in replay buffer

---

examples/multiagent/sac.py

There is a typo in the examples which is fixed by this PR

[CI] Fix examples CI

---

torchrl/envs/transforms/transforms.py

[BugFix] Fix typo in CatFrames Transform error message.

---

tutorials/sphinx-tutorials/pendulum.py

[Doc] correct typos in pendulum tutorial

---

benchmarks/test_objectives_benchmarks.py
docs/source/reference/envs.rst
examples/a2c/utils.py
examples/cql/utils.py
examples/multiagent/maddpg_iddpg.py
examples/multiagent/mappo_ippo.py
examples/multiagent/sac.py
examples/ppo/utils.py
examples/sac/utils.py
test/mocking_classes.py
test/test_actors.py
test/test_cost.py
test/test_helpers.py
test/test_modules.py
test/test_specs.py
test/test_transforms.py
torchrl/data/tensor_specs.py
torchrl/envs/__init__.py
torchrl/envs/common.py
torchrl/envs/libs/brax.py
torchrl/envs/libs/dm_control.py
torchrl/envs/libs/jumanji.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py
torchrl/modules/tensordict_module/actors.py
torchrl/objectives/td3.py
torchrl/trainers/helpers/models.py
tutorials/sphinx-tutorials/multiagent_ppo.py
tutorials/sphinx-tutorials/pendulum.py

Clips observations, actions and rewrards.
cc @albertbou92 
We also rename maximum and minimum in the specs to low and high and raise deprecation warnings when necessary.

[Feature] ClipTransform + rename `min/maximum` -> `low/high`

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py
torchrl/objectives/sac.py

[BugFix] Fix ClipTransform device

---

.github/unittest/linux_libs/scripts_pettingzoo/run_test.sh
.github/workflows/test-linux-pettingzoo.yml
setup.py

Fixes the CI still referencing to the old circleci folder

[CI] Fix CI PettingZoo

---

torchrl/envs/libs/smacv2.py

Patched a bug in SMAC rendering and removes deprecation warnings

[BugFix] Small patches to SMAC

---

test/test_distributions.py
torchrl/modules/distributions/truncated_normal.py

[BugFIx] Fix entropy signature in truncated normal

---

test/test_libs.py
torchrl/__init__.py
torchrl/envs/libs/robohive.py

- Fixes robohive import that occured at root level
- Fixes the mujoco device annoying print

[Refactor] Fix imports

---

torchrl/envs/libs/pettingzoo.py

Prior to this PR, in PettingZoo, groups with one agent only had the multiagent dimension removed.
This PR adds the multiagent dimension to those groups for consistency purposes.

[Feature] Pettingzoo: add multiagent dimension to single agent groups

---

test/_utils_internal.py
test/test_collector.py
test/test_env.py

This PR removes the import of `test_env` from the `test_collector` file

[Test] Remove import of test class

---

torchrl/envs/libs/pettingzoo.py

Make the `set_seed()` function call reset as per gym convention

[BugFix] PettingZoo seeding

---

docs/source/reference/envs.rst
examples/a2c/a2c_atari.py
examples/a2c/utils_atari.py
examples/ppo/ppo_atari.py
examples/ppo/utils_atari.py
test/test_transforms.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/gym_transforms.py
torchrl/envs/transforms/transforms.py

Introduces a gym-specific end-of-life transform to modify the behaviour of losses when facing envs that have lives.

[Feature] End-of-life transform

---

test/test_cost.py
torchrl/objectives/sac.py

[BugFix] Patch SAC to allow state_dict manipulation before exec

---

torchrl/data/replay_buffers/storages.py

#1639 was overwritten by #1611, resetting it

[BugFix] Fix storage device

---

.github/unittest/linux_examples/scripts/run_test.sh
examples/EXAMPLES.md
examples/cql/cql_offline.py
examples/cql/cql_online.py
examples/cql/online_config.yaml
examples/cql/utils.py
examples/ddpg/config.yaml
examples/ddpg/utils.py
examples/decision_transformer/utils.py
examples/discrete_sac/discrete_sac.py
examples/dqn/config.yaml
examples/dqn/dqn.py
examples/dreamer/dreamer_utils.py
examples/iql/iql_online.py
examples/iql/online_config.yaml
examples/redq/config.yaml
examples/redq/redq.py
examples/redq/utils.py
examples/sac/config.yaml
examples/sac/utils.py
examples/td3/config.yaml
examples/td3/utils.py
torchrl/envs/batched_envs.py
torchrl/envs/transforms/transforms.py
torchrl/objectives/value/functional.py
torchrl/record/loggers/utils.py
torchrl/trainers/helpers/losses.py
torchrl/trainers/helpers/models.py
torchrl/trainers/trainers.py

Fixes the EXAMPLES.md file (quick fix)
Will be followed by a more in-depth fix which will re-run all the scripts, incl. redq and sac across classic control, atari and dm_control.

[BugFix] Fix EXAMPLES.md

---

examples/a2c/a2c_atari.py
examples/a2c/a2c_mujoco.py
examples/ppo/ppo_atari.py
examples/ppo/ppo_mujoco.py

Minor fix in the logging of PPO and A2C examples

[Fix] Minor fix in the logging of PPO and A2C examples

---

.github/pytorch-probot.yml

Enabled retry mechanism for GitHub workflows.
The goal of the retry mechanism is to reduce flakiness. The bot will re-run failed jobs once if the number of failed jobs is less than 5.

[CI] Enable retry mechanism

---

test/test_libs.py
test/test_rb_distributed.py
test/test_rlhf.py
torchrl/data/replay_buffers/storages.py
torchrl/data/rlhf/dataset.py
torchrl/data/rlhf/prompt.py
torchrl/data/rlhf/reward.py

Revert "[Refactor] Deprecate direct usage of memmap tensors"

---

.github/unittest/linux_libs/scripts_d4rl/run_test.sh
.github/unittest/linux_libs/scripts_roboset/environment.yml
.github/unittest/linux_libs/scripts_roboset/install.sh
.github/unittest/linux_libs/scripts_roboset/post_process.sh
.github/unittest/linux_libs/scripts_roboset/run-clang-format.py
.github/unittest/linux_libs/scripts_roboset/run_test.sh
.github/unittest/linux_libs/scripts_roboset/setup_env.sh
.github/workflows/test-linux-roboset.yml
docs/source/reference/data.rst
setup.py
test/conftest.py
test/test_libs.py
torchrl/_utils.py
torchrl/data/datasets/__init__.py
torchrl/data/datasets/minari_data.py
torchrl/data/datasets/roboset.py

cc @vikashplus 
Example usage:
```python
from torchrl.data.datasets.roboset import RobosetExperienceReplay
d = RobosetExperienceReplay("FK1-v4(expert)/FK1_MicroOpenRandom_v2d-v4", batch_size=32)
for batch in d:
break
# data is organised by seed and episode, but stored contiguously
print(batch["seed"])
print(batch["episode"])
print(batch)
```
Prints
```
TensorDict(
fields={
action: Tensor(shape=torch.Size([32, 9]), device=cpu, dtype=torch.float64, is_shared=False),
done: Tensor(shape=torch.Size([32]), device=cpu, dtype=torch.bool, is_shared=False),
env_infos: TensorDict(
fields={
done: Tensor(shape=torch.Size([32]), device=cpu, dtype=torch.bool, is_shared=False),
obs_dict: TensorDict(
fields={
approach_err: Tensor(shape=torch.Size([32, 3]), device=cpu, dtype=torch.float64, …
```

[Feature] Roboset datasets

---

test/test_tensordictmodules.py
torchrl/objectives/sac.py

[BugFix] Fix discrete SAC log-prob

---

torchrl/envs/libs/brax.py
torchrl/envs/libs/dm_control.py
torchrl/envs/libs/envpool.py
torchrl/envs/libs/gym.py
torchrl/envs/libs/habitat.py
torchrl/envs/libs/isaacgym.py
torchrl/envs/libs/jax_utils.py
torchrl/envs/libs/jumanji.py
torchrl/envs/libs/openml.py
torchrl/envs/libs/pettingzoo.py
torchrl/envs/libs/robohive.py
torchrl/envs/libs/smacv2.py
torchrl/envs/libs/vmas.py

[Doc] Revamp envs doc

---

README.md

Update README.md to fix CI banner 

---

test/test_rb.py

Fixes bug in MaxValueWriter tests

[BugFix] Fixes bug in MaxValueWriter tests

---

torchrl/envs/transforms/transforms.py

Corrected done update from intersection/conjunction (incorrect) to union/disjunction (correct)

[Doc] Update StepCounter doc

---

.github/unittest/linux/scripts/run_all.sh
torchrl/_utils.py

[BugFix, CI] Fix snapshop imports in stable CI

---

torchrl/envs/transforms/transforms.py

https://github.com/pytorch/rl/blob/a10cdbfc3643fd10c14432ab0dfb89fc2326a755/torchrl/envs/transforms/transforms.py#L1224

[Docs] Fix doc of ToTensorImage transforms.py

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

[BugFix] Fix sequential step counts

---

examples/a2c/utils_atari.py
examples/cql/utils.py
examples/ddpg/utils.py
examples/decision_transformer/utils.py
examples/discrete_sac/utils.py
examples/distributed/collectors/single_machine/generic.py
examples/distributed/collectors/single_machine/rpc.py
examples/distributed/collectors/single_machine/sync.py
examples/dreamer/dreamer_utils.py
examples/iql/utils.py
examples/ppo/utils_atari.py
examples/redq/utils.py
examples/sac/utils.py
examples/td3/utils.py
test/test_env.py
torchrl/_utils.py
torchrl/collectors/collectors.py
torchrl/envs/batched_envs.py
torchrl/envs/gym_like.py
torchrl/objectives/dqn.py
torchrl/trainers/helpers/collectors.py
torchrl/trainers/helpers/losses.py

Makes it possible to avoid creating purposeless parallel envs when only one env is executed.
cc @albertbou92 @BY571 since we have a lot of these in the examples

[Feature] `serial_for_single` arg in batched envs

---

torchrl/data/datasets/vd4rl.py

This was originally aimed at solving #1833 but it feels like it is a data inconsistency on vd4rl side.
Not sure how to patch it on torchrl side in a safe way...
Nevertheless there was some housekeeping to do so here it is.

[BugFix] Fix VD4RL

---

torchrl/objectives/ppo.py
tutorials/sphinx-tutorials/coding_ddpg.py
tutorials/sphinx-tutorials/coding_dqn.py
tutorials/sphinx-tutorials/coding_ppo.py
tutorials/sphinx-tutorials/dqn_with_rnn.py
tutorials/sphinx-tutorials/multi_task.py
tutorials/sphinx-tutorials/multiagent_ppo.py
tutorials/sphinx-tutorials/pendulum.py
tutorials/sphinx-tutorials/pretrained_models.py
tutorials/sphinx-tutorials/rb_tutorial.py
tutorials/sphinx-tutorials/torchrl_demo.py
tutorials/sphinx-tutorials/torchrl_envs.py

Similar solution to https://github.com/pytorch/tutorials/pull/2750

[Doc] Make tutos runnable without colab

---

torchrl/collectors/collectors.py

If an environment has gradients coming out of the reset function, these will be present in the shuttle

[BugFix] No grad on collector reset

---

test/test_helpers.py
test/test_modules.py
torchrl/modules/models/multiagent.py

cc @matteobettini  @kfu02
TODO:

[Refactor] Faster and more generic multi-agent nets

---

.github/unittest/linux_libs/scripts_habitat/setup_env.sh
test/test_env.py
torchrl/envs/libs/habitat.py

[BugFix] Fix habitat

---

torchrl/objectives/common.py

Related to https://github.com/pytorch/rl/issues/1957

[BugFix] Fix batch-size expansion in functionalization

---

test/test_cost.py
torchrl/objectives/ddpg.py
torchrl/objectives/deprecated.py
torchrl/objectives/dqn.py
torchrl/objectives/redq.py
torchrl/objectives/sac.py
torchrl/objectives/td3.py

Same as https://github.com/pytorch/rl/pull/1890, but for Off-Policy losses.

[Feature] Add reduction parameter to Off-Policy losses.

---

test/test_env.py
torchrl/_utils.py
torchrl/envs/batched_envs.py

[Feature] Use non-default mp start method in ParallelEnv

---

test/test_cost.py
torchrl/objectives/cql.py
torchrl/objectives/decision_transformer.py
torchrl/objectives/iql.py

Same as https://github.com/pytorch/rl/pull/1890, but for Offline losses.

[Feature] Offline objectives reduction parameter

---

.github/unittest/linux/scripts/run_all.sh
.github/unittest/linux_distributed/scripts/install.sh
.github/unittest/linux_examples/scripts/run_all.sh

Related to https://github.com/pytorch/torchsnapshot/issues/169

[CI] Temporarily remove snapshot from CI

---

test/test_env.py
torchrl/envs/batched_envs.py

[BugFix] Fix mp_start_method for ParallelEnv with single_for_serial

---

test/test_cost.py
torchrl/objectives/a2c.py
torchrl/objectives/cql.py
torchrl/objectives/decision_transformer.py
torchrl/objectives/deprecated.py
torchrl/objectives/dqn.py
torchrl/objectives/dreamer.py
torchrl/objectives/functional.py
torchrl/objectives/iql.py
torchrl/objectives/ppo.py
torchrl/objectives/redq.py
torchrl/objectives/reinforce.py
torchrl/objectives/sac.py
torchrl/objectives/td3.py
torchrl/objectives/utils.py

This PR add a value clipping option in ClipPPOLoss loss.
This PR is related to https://github.com/pytorch/rl/issues/1977.

[Feature] Adds value clipping in ClipPPOLoss loss

---

sota-implementations/cql/cql_offline.py
sota-implementations/iql/iql_offline.py

[BugFix] Fix CQL/IQL pbar update

---

test/test_env.py
test/test_transforms.py
torchrl/envs/utils.py

[BugFix] More robust _StepMDP and multi-purpose envs

---

.github/unittest/linux_libs/scripts_robohive/setup_env.sh

Still failing but not because of ffmpeg anymore
#2062 will take over

[CI] Install ffmpeg in Robohive tests

---

test/test_libs.py
torchrl/envs/libs/robohive.py

[BugFix] Fix robohive

---

test/test_cost.py
torchrl/objectives/value/functional.py

[BugFix] Fix reward2go for nd tensors

---

test/test_libs.py
torchrl/envs/libs/gym.py
torchrl/envs/libs/isaacgym.py
torchrl/envs/libs/jumanji.py

Revert "[BugFix] Fix Isaac"

---

.github/scripts/m1_script.sh
.github/workflows/wheels.yml
setup.py

Closing https://github.com/pytorch/rl/issues/2124

[Versioning] Allow any torch version for local builds

---

torchrl/modules/tensordict_module/exploration.py

[MINOR] Fix unclear language

---

torchrl/objectives/ppo.py

This PR adds KL approximation in PPO loss metadata, which provides an idea of the distance between the policy that collected the data and the current policy.

[Feature] Add KL approximation in PPO loss metadata

---

test/test_libs.py
torchrl/envs/libs/brax.py

[BugFix] Fix brax wrapping

---

test/test_modules.py
torchrl/modules/models/multiagent.py

Example:
```python
from torchrl.modules import MultiAgentConvNet
n_agents = 2
cnn = MultiAgentConvNet(
n_agents,
centralised = True,
share_params = True
)
print(cnn)
```
prints
```
MultiAgentConvNet(
ConvNet(
(0): LazyConv2d(0, 32, kernel_size=(5, 5), stride=(2, 2))
(1): ELU(alpha=1.0)
(2): Conv2d(32, 32, kernel_size=(5, 5), stride=(2, 2))
(3): ELU(alpha=1.0)
(4): Conv2d(32, 32, kernel_size=(5, 5), stride=(2, 2))
(5): ELU(alpha=1.0)
(6): SquashDims()
),
n_agents=2,
share_params=True,
centralized=True,
agent_dim=-4)
```
I also switched to American english for centralized
cc @TheRisenPhoenix

[Quality] Fix repr of MARL modules

---

docs/source/_static/js/theme.js
docs/source/_templates/layout.html

From https://github.com/pytorch/audio/blob/main/docs/source/_templates/layout.html#L61

[Doc] Restore colab links

---

test/test_specs.py
torchrl/data/tensor_specs.py

Fixes typo from #2203
close #2203

[BugFix] Fix `to` in MultiDiscreteTensorSpec 

---

test/test_specs.py
torchrl/data/tensor_specs.py

[Quality] better error message for CompositeSpec shape mismatch

---

torchrl/data/replay_buffers/samplers.py

Relates to https://github.com/pytorch/rl/pull/2239#discussion_r1647603264
cc @wertyuilife2

[BugFix] Fix typo in weight assignment in PRB

---

test/test_actors.py
test/test_cost.py
test/test_distributions.py
test/test_exploration.py
test/test_tensordictmodules.py
torchrl/collectors/collectors.py
torchrl/collectors/distributed/generic.py
torchrl/collectors/distributed/ray.py
torchrl/collectors/distributed/rpc.py
torchrl/collectors/distributed/sync.py
torchrl/data/replay_buffers/samplers.py
torchrl/modules/distributions/continuous.py
torchrl/modules/distributions/discrete.py
torchrl/modules/distributions/truncated_normal.py
torchrl/modules/models/exploration.py
torchrl/modules/tensordict_module/actors.py
torchrl/modules/tensordict_module/probabilistic.py
torchrl/objectives/common.py
torchrl/objectives/sac.py
torchrl/trainers/helpers/models.py
torchrl/trainers/trainers.py

Solves #2186, please post comments about the feature in that discussion.
Related PR: https://github.com/pytorch/tensordict/pull/824

[BugFix] Fix tanh normal mode

---

test/test_cost.py
torchrl/envs/batched_envs.py
torchrl/envs/transforms/transforms.py

Revert "[BugFix] Fix tensordict private imports"

---

test/test_env.py
torchrl/envs/common.py

Fix the logic in `EnvBase._complete_done` to properly complete the "terminated" key.
close #2291

[BugFix] `EnvBase._complete_done` to complete "terminated" key properly

---

docs/source/reference/envs.rst
docs/source/reference/modules.rst
test/test_env.py
test/test_exploration.py
test/test_specs.py
torchrl/data/tensor_specs.py
torchrl/envs/__init__.py
torchrl/envs/common.py
torchrl/envs/custom/__init__.py
torchrl/envs/custom/tictactoeenv.py
torchrl/modules/__init__.py
torchrl/modules/tensordict_module/__init__.py
torchrl/modules/tensordict_module/exploration.py

* #2303
* #2302
* __->__ #2301

[Feature] TicTacToeEnv

---

docs/source/reference/envs.rst
test/test_env.py
torchrl/envs/__init__.py
torchrl/envs/custom/__init__.py
torchrl/envs/custom/pendulum.py
torchrl/envs/utils.py
tutorials/sphinx-tutorials/pendulum.py

* #2303
* __->__ #2302
* #2301

[Feature] PendulumEnv

---

test/test_env.py
torchrl/envs/custom/tictactoeenv.py

* __->__ #2303
* #2302
* #2301

[Feature] single player for TicTacToe

---

docs/source/reference/modules.rst
test/test_modules.py
torchrl/modules/__init__.py
torchrl/modules/models/__init__.py
torchrl/modules/models/multiagent.py

* #2311
* #2310
* __->__ #2309

[Feature,Doc] `get_stateful_net` and document MARL initialization

---

docs/source/reference/objectives.rst
test/test_cost.py
torchrl/modules/models/multiagent.py
torchrl/objectives/common.py

* #2311
* __->__ #2310
* #2309

[Feature,Doc] `get_stateful_net` and document loss initialization

---

test/test_cost.py
torchrl/objectives/a2c.py
torchrl/objectives/common.py
torchrl/objectives/cql.py
torchrl/objectives/crossq.py
torchrl/objectives/ddpg.py
torchrl/objectives/deprecated.py
torchrl/objectives/iql.py
torchrl/objectives/ppo.py
torchrl/objectives/redq.py
torchrl/objectives/reinforce.py
torchrl/objectives/sac.py
torchrl/objectives/td3.py
torchrl/objectives/td3_bc.py
torchrl/objectives/value/advantages.py

[Feature] Construct loss by providing lists of modules

---

test/test_cost.py
torchrl/objectives/common.py
torchrl/objectives/cql.py
torchrl/objectives/crossq.py
torchrl/objectives/deprecated.py
torchrl/objectives/iql.py
torchrl/objectives/redq.py
torchrl/objectives/sac.py
torchrl/objectives/td3.py
torchrl/objectives/td3_bc.py

* #2317
* #2316
* __->__ #2315

[BugFix] Reinitialize vmap callers after reset of vmap randomness

---

docs/source/reference/objectives.rst
torchrl/objectives/common.py

* #2317
* __->__ #2316
* #2315

[Doc] Add doc about vmap randomness

---

docs/source/reference/objectives.rst
torchrl/objectives/common.py

* __->__ #2317
* #2316
* #2315

[Feature] Allow users to add random modules for vmap randomness detection

---

torchrl/collectors/collectors.py

[BugFix] `done = done | truncated` in collector

---

torchrl/envs/transforms/transforms.py

[Docs] InitTracker cleanup

---

torchrl/data/replay_buffers/checkpointers.py
torchrl/data/replay_buffers/storages.py

Fixes regular dumps and loads with lazy memmap storages when the dest dir matches the storage dir.

[BugFix] Better dumps/loads

---

.github/unittest/linux/scripts/environment.yml
.github/unittest/linux/scripts/run_all.sh
.github/unittest/linux_distributed/scripts/environment.yml
.github/unittest/linux_examples/scripts/environment.yml
.github/unittest/linux_examples/scripts/run_test.sh
.github/unittest/linux_libs/scripts_envpool/environment.yml
.github/unittest/linux_olddeps/scripts_gym_0_13/environment.yml
.github/workflows/benchmarks.yml
.github/workflows/benchmarks_pr.yml
docs/requirements.txt

Temporarily disable dm_control

[CI] pin DMC and mujoco

---

.github/workflows/benchmarks.yml
.github/workflows/benchmarks_pr.yml
.github/workflows/docs.yml
.github/workflows/nightly_build.yml
.github/workflows/test-linux.yml
.github/workflows/wheels-legacy.yml

[CI] Remove 3.8 jobs

---

.github/unittest/linux_libs/scripts_gym/environment.yml
test/test_libs.py
torchrl/envs/gym_like.py
torchrl/envs/libs/gym.py

Support MiniGrid gymnasium environments.
close #1467

[BugFix] Fix support for MiniGrid envs

---

torchrl/envs/custom/tictactoeenv.py

[BugFix] Fix tictactoeenv.py

---

torchrl/envs/libs/vmas.py

I had this feature in my fork for a long time and di not realize it was not in main.
This allows dictionaries as observations in VMAS

[Feature] Dict specs in vmas

---

tutorials/sphinx-tutorials/torchrl_demo.py

[Doc] Fix tutorials for release

---

torchrl/objectives/value/advantages.py

Fixes a few typos in some docstrings from `advantages.py`.
Improve doc.

[Minor] Fix typos in `advantages.py`

---

test/test_collector.py

[CI] Disable compile tests on windows

---

.github/unittest/linux_libs/scripts_minari/environment.yml
.github/unittest/linux_libs/scripts_robohive/environment.yml
.github/unittest/linux_libs/scripts_robohive/install_and_run_test.sh

[CI] Fix gymnasium version in minari

---

test/smoke_test_deps.py
test/test_actors.py
test/test_collector.py
test/test_cost.py
test/test_distributions.py
test/test_env.py
test/test_exploration.py
test/test_helpers.py
test/test_libs.py
test/test_modules.py
test/test_postprocs.py
test/test_rb.py
test/test_rlhf.py
test/test_specs.py
test/test_trainer.py
test/test_transforms.py
test/test_utils.py

[Minor] Make fbcode happy with imports

---

test/test_env.py
torchrl/envs/custom/pendulum.py

[BugFix] Fix pendulum device

---

torchrl/_extension.py

[BugFix] Fix version parsing in extensions

---

test/test_storage_map.py

[BugFix] Fix call to tree.plot in tests

---

torchrl/modules/tensordict_module/actors.py

[Doc] Typo in docs for actors.py

---

tutorials/sphinx-tutorials/export.py
tutorials/sphinx-tutorials/torchrl_demo.py

[Doc] torchrl_demo.py revamp

---

examples/rlhf/utils.py
sota-implementations/a2c/a2c_atari.py
sota-implementations/a2c/a2c_mujoco.py
sota-implementations/cql/cql_online.py
sota-implementations/impala/impala_multi_node_ray.py
sota-implementations/impala/impala_multi_node_submitit.py
sota-implementations/impala/impala_single_node.py
sota-implementations/ppo/ppo_atari.py
sota-implementations/ppo/ppo_mujoco.py
sota-implementations/sac/sac.py
test/mocking_classes.py
test/test_env.py
test/test_modules.py
test/test_rb.py
test/test_transforms.py
torchrl/data/datasets/atari_dqn.py
torchrl/data/datasets/minari_data.py
torchrl/data/datasets/roboset.py
torchrl/data/replay_buffers/samplers.py
torchrl/data/replay_buffers/storages.py
torchrl/data/replay_buffers/utils.py
torchrl/envs/libs/robohive.py
torchrl/envs/model_based/common.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py
torchrl/modules/tensordict_module/rnn.py
tutorials/sphinx-tutorials/pendulum.py
tutorials/sphinx-tutorials/torchrl_envs.py

[Quality] Better TD construction in codebase

---

.github/unittest/linux_olddeps/scripts_gym_0_13/install.sh
.github/workflows/test-linux.yml
test/test_distributions.py
test/test_transforms.py
torchrl/data/tensor_specs.py
torchrl/envs/transforms/transforms.py

[CI, BugFix] Py3.8 for old deps

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/test-linux-examples.yml
.github/workflows/test-linux-habitat.yml
.github/workflows/test-linux-libs.yml
.github/workflows/test-linux-rlhf.yml
.github/workflows/test-linux.yml

[CI] linux_job_v2.yml

---

torchrl/_utils.py

* #2578
* #2577
* __->__ #2576
* #2575

[Minor,Feature] Add `prefix` arg to `timeit.todict`

---

docs/source/reference/objectives.rst
torchrl/objectives/__init__.py
torchrl/objectives/utils.py

* #2578
* __->__ #2577
* #2576
* #2575

[Minor,Feature] `group_optimizers`

---

torchrl/collectors/collectors.py
torchrl/envs/common.py
torchrl/envs/libs/gym.py
torchrl/envs/libs/meltingpot.py
torchrl/modules/tensordict_module/actors.py
torchrl/objectives/dqn.py
torchrl/objectives/iql.py
torchrl/objectives/sac.py
torchrl/record/recorder.py
torchrl/trainers/helpers/envs.py

[BE] Add trailing spaces when necessary

---

torchrl/modules/distributions/continuous.py

[Refactor] Allow safe-tanh for torch >= 2.6.0

---

torchrl/collectors/distributed/generic.py
torchrl/collectors/distributed/rpc.py
torchrl/collectors/distributed/sync.py

[BugFix] requested_frames_per_batch in distributed collectors

---

.github/workflows/docs.yml
sota-implementations/ddpg/utils.py
sota-implementations/dreamer/dreamer_utils.py
sota-implementations/multiagent/maddpg_iddpg.py
sota-implementations/redq/config.yaml
sota-implementations/redq/redq.py
sota-implementations/redq/utils.py
sota-implementations/td3/utils.py
sota-implementations/td3_bc/utils.py
test/_utils_internal.py
test/test_actors.py
test/test_collector.py
test/test_exploration.py
test/test_transforms.py
torchrl/collectors/collectors.py
torchrl/envs/__init__.py
torchrl/modules/distributions/continuous.py
torchrl/modules/tensordict_module/exploration.py
torchrl/objectives/__init__.py
torchrl/objectives/crossq.py

[BugFix] Fix failing tests

---

.github/workflows/docs.yml

[CI] Revert upgrade of upload image in docs

---

benchmarks/test_objectives_benchmarks.py
torchrl/envs/libs/vmas.py
torchrl/objectives/utils.py
torchrl/objectives/value/advantages.py

[BugFix] Fix get_default_device calls in older PT versions

---

benchmarks/test_objectives_benchmarks.py

[BugFix,Test,Benchmark] Fix graph breaks induced by device context manager

---

torchrl/data/tensor_specs.py

* #2601
* #2600
* #2599
* __->__ #2598
* #2597
* #2596

[Feature] Composite.pop

---

torchrl/envs/common.py

* #2601
* __->__ #2600
* #2599
* #2598
* #2597
* #2596

[Feature] EnvBase.check_env_specs

---

torchrl/envs/common.py

Maybe we need some tests that check these automatically with all the variations: full, unbatched, etc

[BugFix] Wrong spec returned

---

torchrl/objectives/ppo.py
torchrl/objectives/utils.py
torchrl/objectives/value/advantages.py

* __->__ #2622
Happy to massage this a little bit if the API isn't optimal!
Do you think we're covering all (edge) cases?
cc @louisfaury @albertbou92

[BugFix] Better account of composite distributions in PPO

---

torchrl/modules/distributions/continuous.py

Fixed typo in torchrl/modules/distributions/continuous.py, in the TanhNormal module
I saw this thing when I got the exception

[Doc] Fix typo in torchrl/modules/distributions/continuous.py

---

.github/unittest/linux_sota/scripts/test_sota.py
sota-implementations/dreamer/dreamer.py

[CI] Fix dreamer run in SOTA tests

---

tutorials/sphinx-tutorials/export.py

[BugFix] Fix export aoti_compile_and_package API change

---

examples/replay-buffers/filter-imcomplete-trajs.py

[Example] Efficient Trajectory Sampling with CompletedTrajRepertoire

---

test/test_collector.py
torchrl/collectors/collectors.py

[BugFix] Fix init_random_frames=0

---

torchrl/envs/custom/chess.py

[BugFix] Fix typing in chess env

---

torchrl/envs/custom/llm.py

[BugFix] Fix typing in llm env

---

torchrl/data/tensor_specs.py

[BugFix] Remove raisers in specs

---

sota-implementations/sac/config.yaml
sota-implementations/sac/sac.py
sota-implementations/sac/utils.py

* #2657
* #2656
* __->__ #2655

[Feature] SAC compatibility with compile

---

torchrl/record/loggers/csv.py
torchrl/record/loggers/mlflow.py
torchrl/record/loggers/wandb.py
torchrl/record/recorder.py

[BugFix, BE] Document and fix fps passing in recorder and loggers

---

torchrl/objectives/a2c.py
torchrl/objectives/common.py
torchrl/objectives/cql.py
torchrl/objectives/crossq.py
torchrl/objectives/ddpg.py
torchrl/objectives/decision_transformer.py
torchrl/objectives/deprecated.py
torchrl/objectives/dqn.py
torchrl/objectives/dreamer.py
torchrl/objectives/gail.py
torchrl/objectives/iql.py
torchrl/objectives/multiagent/qmixer.py
torchrl/objectives/ppo.py
torchrl/objectives/redq.py
torchrl/objectives/reinforce.py
torchrl/objectives/sac.py
torchrl/objectives/td3.py
torchrl/objectives/td3_bc.py
torchrl/objectives/value/advantages.py

[BE] Add type annotation for tensor_keys to facilitate auto-complete

---

torchrl/envs/batched_envs.py

[BugFix,Doc] Fix BATCHED_PIPE_TIMEOUT refs and doc

---

test/test_collector.py
torchrl/collectors/collectors.py

* #2705
* #2704
* __->__ #2703

[BugFix] Fix partial device transfers in collector

---

torchrl/collectors/collectors.py

* #2705
* __->__ #2704
* #2703

[BugFix] Fix device transfer for collectors with init_random_frames mixed devices

---

examples/collectors/collector_device.py

* __->__ #2705
* #2704
* #2703

[Example] Using Collector's device args

---

.github/workflows/benchmarks.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/nightly_build.yml
.github/workflows/test-linux-habitat.yml
.github/workflows/test-linux-libs.yml
.github/workflows/test-linux-rlhf.yml
.github/workflows/test-linux-sota.yml
.github/workflows/test-linux.yml
.github/workflows/test-windows-optdepts.yml
.github/workflows/wheels-legacy.yml

[CI] workflow permissions

---

test/test_transforms.py

[Test] Add tests for CatFrames with PermuteTransform

---

test/test_collector.py
test/test_env.py
torchrl/envs/common.py

[Feature] Ensure out-place policy compatibility in rollout and collectors

---

torchrl/modules/distributions/discrete.py

* #2711
* #2709
* __->__ #2708
* #2702

[Feature] Add deterministic_sample to masked categorical

---

test/test_libs.py

[CI] Remove gym import in test_libs.py

---

test/test_libs.py
torchrl/envs/custom/chess.py

[CI] Local import of PIL

---

.github/unittest/linux_libs/scripts_chess/environment.yml
.github/unittest/linux_libs/scripts_chess/install.sh
test/test_env.py
torchrl/envs/custom/chess.py

[BugFix,Test] test chess rendering

---

.github/unittest/linux_libs/scripts_minari/environment.yml

[CI] minari[hf]

---

test/test_env.py
torchrl/envs/common.py

* #2730
* #2729
* #2728
* #2726
* #2725
* __->__ #2724

[Feature] automatically determine return_contiguous

---

test/mocking_classes.py
test/test_env.py
torchrl/data/tensor_specs.py

* #2730
* #2729
* #2728
* #2726
* __->__ #2725
* #2724

[Test] Str2StrEnv test

---

docs/source/reference/envs.rst
test/test_libs.py
torchrl/envs/__init__.py
torchrl/envs/libs/__init__.py
torchrl/envs/libs/gym.py

* #2730
* #2729
* #2728
* __->__ #2726
* #2725
* #2724

[Feature] Custom conversion tool for gym specs

---

.github/unittest/linux_olddeps/scripts_gym_0_13/environment.yml
.github/unittest/linux_olddeps/scripts_gym_0_13/run_test.sh
.github/unittest/linux_olddeps/scripts_gym_0_13/setup_env.sh

[CI] Fix olddeps dm_control

---

.github/workflows/benchmarks.yml
.github/workflows/benchmarks_pr.yml
.github/workflows/wheels-legacy.yml

[CI] Upgrade GHA versions

---

.github/workflows/benchmarks.yml
.github/workflows/benchmarks_pr.yml
benchmarks/test_objectives_benchmarks.py
torchrl/objectives/a2c.py
torchrl/objectives/common.py
torchrl/objectives/cql.py
torchrl/objectives/crossq.py
torchrl/objectives/ddpg.py
torchrl/objectives/decision_transformer.py
torchrl/objectives/deprecated.py
torchrl/objectives/dqn.py
torchrl/objectives/dreamer.py
torchrl/objectives/gail.py
torchrl/objectives/iql.py
torchrl/objectives/ppo.py
torchrl/objectives/redq.py
torchrl/objectives/reinforce.py
torchrl/objectives/sac.py
torchrl/objectives/td3.py
torchrl/objectives/td3_bc.py

[BugFix] Fix compile weakrefs errors

---

.github/unittest/linux_libs/scripts_chess/environment.yml
.github/unittest/linux_libs/scripts_chess/setup_env.sh

[CI] Fix Cairo-2 Chess import error

---

test/test_transforms.py

[Test] Skip tokenizer tests if transformers is not in workspace

---

.github/unittest/linux/scripts/run_all.sh
.github/unittest/linux_distributed/scripts/setup_env.sh
.github/unittest/linux_libs/scripts_d4rl/setup_env.sh
.github/unittest/linux_libs/scripts_gym/setup_env.sh
.github/unittest/linux_libs/scripts_habitat/run_test.sh
.github/unittest/linux_libs/scripts_habitat/setup_env.sh
.github/unittest/linux_libs/scripts_robohive/setup_env.sh
.github/unittest/linux_olddeps/scripts_gym_0_13/setup_env.sh
.github/unittest/linux_sota/scripts/run_all.sh
torchrl/collectors/collectors.py

[CI] Make MAX_IDLE_COUNT a feature of tests

---

.github/unittest/linux_libs/scripts_ataridqn/install.sh
.github/unittest/linux_libs/scripts_brax/install.sh
.github/unittest/linux_libs/scripts_chess/install.sh
.github/unittest/linux_libs/scripts_d4rl/install.sh
.github/unittest/linux_libs/scripts_envpool/install.sh
.github/unittest/linux_libs/scripts_gen-dgrl/install.sh
.github/unittest/linux_libs/scripts_habitat/install.sh
.github/unittest/linux_libs/scripts_jumanji/install.sh
.github/unittest/linux_libs/scripts_meltingpot/install.sh
.github/unittest/linux_libs/scripts_minari/install.sh
.github/unittest/linux_libs/scripts_open_spiel/install.sh
.github/unittest/linux_libs/scripts_openx/install.sh
.github/unittest/linux_libs/scripts_pettingzoo/install.sh
.github/unittest/linux_libs/scripts_rlhf/install.sh
.github/unittest/linux_libs/scripts_robohive/install_and_run_test.sh
.github/unittest/linux_libs/scripts_roboset/install.sh
.github/unittest/linux_libs/scripts_sklearn/install.sh
.github/unittest/linux_libs/scripts_smacv2/install.sh
.github/unittest/linux_libs/scripts_unity_mlagents/install.sh
.github/unittest/linux_libs/scripts_vd4rl/install.sh
.github/unittest/linux_libs/scripts_vmas/install.sh

[CI] Upgrade cu121 to cu124

---

.github/workflows/test-windows-optdepts.yml

[CI] Longer timeout for windows

---

torchrl/data/tensor_specs.py
torchrl/envs/transforms/transforms.py

[BugFix] Fix composite setitem

---

.github/workflows/docs.yml
docs/requirements.txt
docs/source/conf.py
docs/source/content_generation.py
tutorials/sphinx-tutorials/coding_ddpg.py
tutorials/sphinx-tutorials/coding_dqn.py
tutorials/sphinx-tutorials/dqn_with_rnn.py
tutorials/sphinx-tutorials/getting-started-3.py
tutorials/sphinx-tutorials/multiagent_competitive_ddpg.py
tutorials/sphinx-tutorials/pretrained_models.py
tutorials/sphinx-tutorials/rb_tutorial.py

[Doc] Fix (and deactivate) tutorials

---

test/test_env.py
torchrl/envs/transforms/transforms.py

[BugFix] Apply inverse transform to input of `TransformedEnv._reset`

---

torchrl/data/tensor_specs.py

[BE] Ensure abstractmethods are implemented for specs

---

torchrl/data/map/query.py
torchrl/envs/transforms/transforms.py

[BugFix] Fix MultiAction reset

---

test/_utils_internal.py
test/test_env.py
test/test_exploration.py
test/test_specs.py
torchrl/data/datasets/d4rl.py
torchrl/data/datasets/gen_dgrl.py
torchrl/data/datasets/openx.py
torchrl/data/datasets/vd4rl.py
torchrl/data/rlhf/dataset.py

* __->__ #2799
* #2798
* #2797
* #2793
* #2792

[Test] Capture deprec warnings

---

torchrl/objectives/value/utils.py

[BugFix] correct dim for resolving dtype in _split_and_pad_sequence

---

torchrl/envs/common.py

[BugFix] Refactor _skip_tensordict to avoid update calls

---

test/test_env.py
torchrl/envs/transforms/rlhf.py
torchrl/envs/transforms/transforms.py

[Feature] Capture wrong spec transforms (1/N)

---

docs/source/reference/envs.rst
test/test_transforms.py
torchrl/envs/__init__.py
torchrl/envs/transforms/__init__.py
torchrl/envs/transforms/transforms.py

[Feature] Timer transform

---

test/test_transforms.py
torchrl/envs/transforms/transforms.py

[Feature] reset_time in Timer

---

torchrl/envs/common.py

[BugFix] Fix forced batch-size in _skip_tensordict

---

test/test_collector.py
torchrl/collectors/collectors.py

[BugFix] Fix collector with no buffers and devices

---

.github/unittest/linux_libs/scripts_ataridqn/install.sh
.github/unittest/linux_libs/scripts_brax/install.sh
.github/unittest/linux_libs/scripts_chess/install.sh
.github/unittest/linux_libs/scripts_d4rl/install.sh
.github/unittest/linux_libs/scripts_envpool/install.sh
.github/unittest/linux_libs/scripts_gen-dgrl/install.sh
.github/unittest/linux_libs/scripts_habitat/install.sh
.github/unittest/linux_libs/scripts_jumanji/install.sh
.github/unittest/linux_libs/scripts_meltingpot/install.sh
.github/unittest/linux_libs/scripts_minari/install.sh
.github/unittest/linux_libs/scripts_open_spiel/install.sh
.github/unittest/linux_libs/scripts_openx/install.sh
.github/unittest/linux_libs/scripts_pettingzoo/install.sh
.github/unittest/linux_libs/scripts_rlhf/install.sh
.github/unittest/linux_libs/scripts_robohive/install_and_run_test.sh
.github/unittest/linux_libs/scripts_roboset/install.sh
.github/unittest/linux_libs/scripts_sklearn/install.sh
.github/unittest/linux_libs/scripts_smacv2/install.sh
.github/unittest/linux_libs/scripts_unity_mlagents/install.sh
.github/unittest/linux_libs/scripts_vd4rl/install.sh
.github/unittest/linux_libs/scripts_vmas/install.sh
.github/workflows/benchmarks.yml
.github/workflows/benchmarks_pr.yml
.github/workflows/docs.yml
.github/workflows/test-linux-habitat.yml
.github/workflows/test-linux-libs.yml
.github/workflows/test-linux-rlhf.yml
.github/workflows/test-linux-sota.yml
.github/workflows/test-linux.yml

[CI] Upgrade to cuda 12.8

---

test/test_env.py
torchrl/envs/utils.py

[Feature] Dynamic specs for make_composite_from_td

---

docs/source/_static/js/torchrl_theme.js
docs/source/_templates/layout.html
tutorials/sphinx-tutorials/rb_tutorial.py

[BugFix] Fix gc import

---

torchrl/envs/env_creator.py

Minor update to the doc of the `EnvCreator` method `make_variant`.

[Doc] Fix `EnvCreator`'s doc

---

test/test_actors.py
torchrl/modules/__init__.py
torchrl/modules/llm/__init__.py
torchrl/modules/llm/common.py
torchrl/modules/llm/transformers_policy.py
torchrl/modules/llm/vllm_wrapper.py

[Refactor] vLLMWrapper class

---

pytree.ipynb
test/test_actors.py
torchrl/modules/__init__.py
torchrl/modules/llm/__init__.py
torchrl/modules/llm/transformers_policy.py
torchrl/modules/llm/transformers_wrapper.py
torchrl/modules/llm/vllm_policy.py
torchrl/modules/llm/vllm_wrapper.py

[Refactor] TransformersWrapper class

---

torchrl/data/replay_buffers/storages.py

[BugFix] Keep original class in LazyStackStorage through lazy_stack

---

docs/source/reference/envs.rst
test/test_env.py
test/test_tensordictmodules.py
torchrl/envs/__init__.py
torchrl/envs/async_envs.py
torchrl/envs/common.py

[Feature] Async environments

---

test/test_actors.py
torchrl/modules/llm/vllm_wrapper.py

[Feature] Allow vLLMWrapper to generate multiple samples

---

torchrl/data/replay_buffers/storages.py
torchrl/data/replay_buffers/utils.py

[BugFix] Fix lazy-stack in RBs

---

test/test_cost.py
torchrl/objectives/common.py

* #2889
* #2888
* #2887
* #2886
* __->__ #2885

[BugFix] Fix .item() warning on tensors that require grad

---

test/test_cost.py
torchrl/envs/custom/chess.py
torchrl/objectives/ppo.py

* #2889
* #2888
* #2887
* __->__ #2886
* #2885

[Test] Fix warnings in tests

---

test/mocking_classes.py
test/test_env.py
torchrl/collectors/collectors.py
torchrl/collectors/distributed/generic.py
torchrl/collectors/distributed/ray.py
torchrl/collectors/distributed/rpc.py
torchrl/collectors/distributed/sync.py
torchrl/collectors/weight_update.py
torchrl/envs/custom/llm.py
torchrl/envs/utils.py

* #2889
* __->__ #2888
* #2887
* #2886
* #2885

[Feature] Pass lists of policy_factory

---

torchrl/objectives/ppo.py

* __->__ #2889
* #2888
* #2887
* #2886
* #2885

[BugFix] Fix compile compatibility of PPO losses

---

docs/source/reference/collectors.rst
test/test_collector.py
test/test_cost.py
torchrl/collectors/llm_collector.py

Add LLM Collector, which is a subset of the SyncDatacollector aimed at trimming to core funcionality in an easy to consume API for LLM devs
#2872 
```
python test/test_collector.py TestLLMCollector
```

[Feature] LLM collector

---

test/test_cost.py
test/test_rb.py
torchrl/data/llm/chat.py

[Feature] History.default_spec

---

.github/unittest/linux/scripts/run_all.sh
.github/unittest/linux_distributed/scripts/setup_env.sh
.github/unittest/linux_libs/scripts_gym/batch_scripts.sh
.github/unittest/linux_sota/scripts/run_all.sh
test/_utils_internal.py
test/test_libs.py
torchrl/envs/common.py
torchrl/envs/gym_like.py
torchrl/envs/libs/_gym_utils.py
torchrl/envs/libs/gym.py

[Feature] Gymnasium 1.1 compatibility

---

test/mocking_classes.py
test/test_actors.py
test/test_collector.py
test/test_cost.py
test/test_env.py
test/test_transforms.py
torchrl/collectors/llm.py
torchrl/envs/common.py
torchrl/envs/custom/llm.py
torchrl/envs/transforms/llm.py
torchrl/envs/transforms/transforms.py
torchrl/envs/utils.py
torchrl/modules/llm/transformers_wrapper.py
torchrl/modules/llm/vllm_wrapper.py

[Refactor] Simplify LLMEnv

---

test/test_libs.py
test/test_transforms.py
torchrl/envs/common.py
torchrl/envs/transforms/vecnorm.py

[Feature] VecNormV2: Usage with batched envs

---

torchrl/data/tensor_specs.py

* #2907
* __->__ #2906
* #2905

[BugFix] Remove neg dim checks in expand for all specs

---

torchrl/collectors/collectors.py
torchrl/data/tensor_specs.py
torchrl/envs/common.py
torchrl/envs/gym_like.py
torchrl/envs/utils.py

* __->__ #2907
* #2906
* #2905

[Performance] Memoize calls to encode and related methods within step

---

.github/unittest/linux_libs/scripts_llm/run_test.sh

* #2921
* #2915
* #2920
* #2919
* __->__ #2918
* #2917
* #2916

[CI] Fix LLM tests

---

.github/workflows/docs.yml

* #2923
* __->__ #2922
* #2921

[Docs] Fix doc setup

---

test/test_env.py
torchrl/envs/batched_envs.py

[BugFix] Fix slow and flaky non-tensor parallel env test

---

.github/scripts/td_script.sh
.github/unittest/linux_libs/scripts_gym/batch_scripts.sh
.github/unittest/linux_libs/scripts_gym/install.sh
.github/unittest/linux_libs/scripts_gym/run_test.sh
.github/unittest/linux_libs/scripts_gym/setup_env.sh
.github/unittest/linux_olddeps/scripts_gym_0_13/setup_env.sh
.github/workflows/test-linux-libs.yml
sota-implementations/a2c/utils_atari.py
torchrl/data/datasets/atari_dqn.py
torchrl/envs/libs/smacv2.py
torchrl/envs/transforms/transforms.py

[Environment] Fix lib CI failures

---

.github/scripts/pre-build-script-win.sh
.github/scripts/td_script.sh
.github/unittest/linux_libs/scripts_gym/setup_env.sh
.github/unittest/linux_olddeps/scripts_gym_0_13/environment.yml
.github/unittest/linux_olddeps/scripts_gym_0_13/setup_env.sh
.github/unittest/windows_optdepts/scripts/environment.yml
.github/unittest/windows_optdepts/scripts/unittest.sh
.github/workflows/benchmarks.yml
.github/workflows/benchmarks_pr.yml
.github/workflows/nightly_build.yml
.github/workflows/test-linux.yml
test/test_collector.py
test/test_storage_map.py

[CI] Fix nightly and benchmark CIs

---

CONTRIBUTING.md
README.md

[Minor] Quick edits to .md files

---

.github/workflows/build-wheels-m1.yml

[CI] Build wheels on osx 15

---

torchrl/_utils.py
torchrl/data/replay_buffers/checkpointers.py
torchrl/data/replay_buffers/writers.py

[Quality] Local dtype maps

---

tutorials/sphinx-tutorials/multiagent_ppo.py

Fixing a typo in the docs.
I was reading this page and noticed what appears to be a typo (form vs from)

Fix typo in "Multi-Agent Reinforcement Learning (PPO) with TorchRL Tutorial" docs

---

tutorials/sphinx-tutorials/multiagent_ppo.py

Another leftover bug from https://github.com/pytorch/rl/pull/2917
2 questions:
- do we still have a CI for tutos?
- Will this update the docs when merged or we are stuck w the bug until next release?

[BugFix] Multiagent PPO tutorial

---

torchrl/envs/gym_like.py

[BugFix] Fix single action pass to gym when action key is not "action"

---

test/test_specs.py
torchrl/data/tensor_specs.py

[BugFix] Fix encode overrides

---

.gitignore
examples/distributed/replay_buffers/ray_buffer.py
torchrl/collectors/distributed/ray.py

[Example] RayReplayBuffer usage

---

torchrl/__init__.py
torchrl/_utils.py
torchrl/modules/distributions/continuous.py

[BugFix] Robust torch.cuda.is_current_stream_capturing calls

---

.gitignore

[Minor] gitignore ipynb

---

test/test_cost.py
torchrl/objectives/value/advantages.py

[BugFix] Enable ndim done states in GAE with shifted=True

---

test/test_rb.py
torchrl/data/replay_buffers/samplers.py

[BugFix] Fix PRB serialization

---

torchrl/objectives/ppo.py

[Quality] Warning composite mismatch when we should

---

torchrl/_utils.py

[Feature] Colored logger

---

docs/source/reference/llms.rst
test/llm/test_objectives.py
torchrl/objectives/llm/__init__.py
torchrl/objectives/llm/grpo.py

* #2969
* __->__ #2968
* #2966
* #2965

[Feature] Losses (GRPO)

---

torchrl/objectives/llm/grpo.py
torchrl/objectives/ppo.py

* __->__ #2969
* #2968
* #2966
* #2965

[BugFix] device in args of PPO losses

---

test/test_cost.py
torchrl/objectives/ppo.py

[Test] Fix device in PPO tests

---

test/test_specs.py
torchrl/data/tensor_specs.py

[Performance] Hold a single copy of low/high in bounded specs

---

torchrl/objectives/a2c.py

I came across an inconsistency in the documentation for _AcceptedKeys in A2CLoss class inside /objectives/a2c.py. It didn't mention anything about sample_log_prob. To maintain consistency I have copied it from PPO.

[Doc] Update documentation for _AcceptedKeys in a2c.py

---

torchrl/collectors/weight_update.py

Is it possible that the class was renamed and the docs need this minor change?

[Doc] WeightUpdaterBase docs update after renaming

---

torchrl/objectives/sac.py

[Feature] public methods for SAC

---

test/llm/test_wrapper.py
torchrl/modules/llm/policies/common.py
torchrl/modules/llm/policies/transformers_wrapper.py
torchrl/modules/llm/policies/vllm_wrapper.py

This PR introduces standardized generation parameters across vLLM and Transformers wrappers, enabling cross-backend compatibility while maintaining full backward compatibility.
- Introduced common parameter names that work across both vLLM and Transformers wrappers
- **Core parameters**: `max_new_tokens`, `num_return_sequences`, `temperature`, `top_p`, `top_k`, `repetition_penalty`, `do_sample`, `num_beams`, `length_penalty`, `early_stopping`, `stop_sequences`, `skip_special_tokens`, `logprobs`
- Automatic conversion of legacy parameter names:
- `max_tokens` → `max_new_tokens`
- `n` → `num_return_sequences`
- Ensures existing code continues to work without modification
- **Silent override behavior**: When both legacy and standardized names are provided, legacy names prevail
- Example: …

[Feature] Common kwargs for generate across vLLM and Transformers

---

torchrl/modules/distributions/discrete.py

replace reduce to reduction, better error message for invalid mask
